/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Thu Jun  4 21:58:12 BST 2026
 * 
 */

/* Generation options: */
#ifndef __mkDPipeline_h__
#define __mkDPipeline_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkDPipeline module */
class MOD_mkDPipeline : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_m_dataRam_0_bram;
  MOD_Reg<tUInt8> INST_m_dataRam_0_currentWriteAddr;
  MOD_Reg<tUWide> INST_m_dataRam_0_currentWriteData;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_0_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_0_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_0_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_dataRam_0_readAddr;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_m_dataRam_1_bram;
  MOD_Reg<tUInt8> INST_m_dataRam_1_currentWriteAddr;
  MOD_Reg<tUWide> INST_m_dataRam_1_currentWriteData;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_1_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_1_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_1_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_dataRam_1_readAddr;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_m_dataRam_2_bram;
  MOD_Reg<tUInt8> INST_m_dataRam_2_currentWriteAddr;
  MOD_Reg<tUWide> INST_m_dataRam_2_currentWriteData;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_2_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_2_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_2_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_dataRam_2_readAddr;
  MOD_BRAM<tUInt8,tUWide,tUInt8> INST_m_dataRam_3_bram;
  MOD_Reg<tUInt8> INST_m_dataRam_3_currentWriteAddr;
  MOD_Reg<tUWide> INST_m_dataRam_3_currentWriteData;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_3_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_dataRam_3_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_dataRam_3_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_dataRam_3_readAddr;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_m_infoRam_0_bram;
  MOD_Reg<tUInt8> INST_m_infoRam_0_currentWriteAddr;
  MOD_Reg<tUInt64> INST_m_infoRam_0_currentWriteData;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_0_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_0_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_0_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_infoRam_0_readAddr;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_m_infoRam_1_bram;
  MOD_Reg<tUInt8> INST_m_infoRam_1_currentWriteAddr;
  MOD_Reg<tUInt64> INST_m_infoRam_1_currentWriteData;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_1_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_1_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_1_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_infoRam_1_readAddr;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_m_infoRam_2_bram;
  MOD_Reg<tUInt8> INST_m_infoRam_2_currentWriteAddr;
  MOD_Reg<tUInt64> INST_m_infoRam_2_currentWriteData;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_2_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_2_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_2_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_infoRam_2_readAddr;
  MOD_BRAM<tUInt8,tUInt64,tUInt8> INST_m_infoRam_3_bram;
  MOD_Reg<tUInt8> INST_m_infoRam_3_currentWriteAddr;
  MOD_Reg<tUInt64> INST_m_infoRam_3_currentWriteData;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_3_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_infoRam_3_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_infoRam_3_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_infoRam_3_readAddr;
  MOD_Reg<tUInt8> INST_m_initDone;
  MOD_Reg<tUInt8> INST_m_initIndex;
  MOD_Wire<tUWide> INST_m_pipe_enq2Mat_lat_0;
  MOD_Wire<tUWide> INST_m_pipe_enq2Mat_lat_1;
  MOD_Reg<tUWide> INST_m_pipe_enq2Mat_rl;
  MOD_Wire<tUWide> INST_m_pipe_mat2Out_lat_0;
  MOD_Wire<tUWide> INST_m_pipe_mat2Out_lat_1;
  MOD_Reg<tUWide> INST_m_pipe_mat2Out_rl;
  MOD_BRAM<tUInt8,tUInt8,tUInt8> INST_m_queueRam_bram;
  MOD_Reg<tUInt8> INST_m_queueRam_currentWriteAddr;
  MOD_Reg<tUInt8> INST_m_queueRam_currentWriteData;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_queueRam_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_queueRam_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_queueRam_rdReqQ_full_rl;
  MOD_CReg<tUInt8> INST_m_queueRam_readAddr;
  MOD_Reg<tUInt8> INST_m_randRep_randWay;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_deqP_lat_0;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_deqP_lat_1;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_empty_lat_0;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_empty_lat_1;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_empty_lat_2;
  MOD_Reg<tUInt8> INST_m_repRam_rdReqQ_empty_rl;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_enqP_lat_0;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_enqP_lat_1;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_full_lat_0;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_full_lat_1;
  MOD_Wire<tUInt8> INST_m_repRam_rdReqQ_full_lat_2;
  MOD_Reg<tUInt8> INST_m_repRam_rdReqQ_full_rl;
 
 /* Constructor */
 public:
  MOD_mkDPipeline(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_send_r;
  tUWide PORT_deqWrite_wrRam;
  tUWide PORT_first;
 
 /* Publicly accessible definitions */
 public:
  tUInt64 DEF_x__h34405;
  tUInt8 DEF_way__h54236;
  tUInt8 DEF_m_randRep_randWay___d217;
  tUWide DEF_m_pipe_enq2Mat_rl___d227;
  tUWide DEF_m_pipe_enq2Mat_lat_0_wget____d225;
  tUInt8 DEF_y__h53717;
  tUInt8 DEF_x__h53716;
  tUInt8 DEF_y__h53110;
  tUInt8 DEF_x__h53109;
  tUInt8 DEF_y__h52492;
  tUInt8 DEF_x__h52491;
  tUInt8 DEF_y__h51313;
  tUInt8 DEF_x__h51312;
  tUInt8 DEF_m_pipe_enq2Mat_lat_0_whas____d224;
  tUInt8 DEF_m_initDone__h30502;
  tUInt8 DEF_m_queueRam_rdReqQ_full_rl__h76663;
  tUInt8 DEF_m_queueRam_rdReqQ_full_lat_0_whas____d203;
  tUInt8 DEF_m_queueRam_rdReqQ_full_lat_0_wget____d204;
  tUInt8 DEF_m_queueRam_rdReqQ_empty_rl__h29493;
  tUInt8 DEF_m_dataRam_3_rdReqQ_full_rl__h72295;
  tUInt8 DEF_m_dataRam_3_rdReqQ_full_lat_0_whas____d182;
  tUInt8 DEF_m_dataRam_3_rdReqQ_full_lat_0_wget____d183;
  tUInt8 DEF_m_dataRam_3_rdReqQ_empty_rl__h25247;
  tUInt8 DEF_m_dataRam_2_rdReqQ_full_rl__h71429;
  tUInt8 DEF_m_dataRam_2_rdReqQ_full_lat_0_whas____d161;
  tUInt8 DEF_m_dataRam_2_rdReqQ_full_lat_0_wget____d162;
  tUInt8 DEF_m_dataRam_2_rdReqQ_empty_rl__h21028;
  tUInt8 DEF_m_dataRam_1_rdReqQ_full_rl__h70563;
  tUInt8 DEF_m_dataRam_1_rdReqQ_full_lat_0_whas____d140;
  tUInt8 DEF_m_dataRam_1_rdReqQ_full_lat_0_wget____d141;
  tUInt8 DEF_m_dataRam_1_rdReqQ_empty_rl__h16809;
  tUInt8 DEF_m_dataRam_0_rdReqQ_full_rl__h69697;
  tUInt8 DEF_m_dataRam_0_rdReqQ_full_lat_0_whas____d119;
  tUInt8 DEF_m_dataRam_0_rdReqQ_full_lat_0_wget____d120;
  tUInt8 DEF_m_dataRam_0_rdReqQ_empty_rl__h12587;
  tUInt8 DEF_m_repRam_rdReqQ_full_rl__h76247;
  tUInt8 DEF_m_repRam_rdReqQ_full_lat_0_whas____d99;
  tUInt8 DEF_m_repRam_rdReqQ_full_lat_0_wget____d100;
  tUInt8 DEF_m_repRam_rdReqQ_empty_rl__h10523;
  tUInt8 DEF_m_infoRam_3_rdReqQ_full_rl__h71871;
  tUInt8 DEF_m_infoRam_3_rdReqQ_full_lat_0_whas____d78;
  tUInt8 DEF_m_infoRam_3_rdReqQ_full_lat_0_wget____d79;
  tUInt8 DEF_m_infoRam_3_rdReqQ_empty_rl__h8326;
  tUInt8 DEF_m_infoRam_2_rdReqQ_full_rl__h71005;
  tUInt8 DEF_m_infoRam_2_rdReqQ_full_lat_0_whas____d57;
  tUInt8 DEF_m_infoRam_2_rdReqQ_full_lat_0_wget____d58;
  tUInt8 DEF_m_infoRam_2_rdReqQ_empty_rl__h6042;
  tUInt8 DEF_m_infoRam_1_rdReqQ_full_rl__h70139;
  tUInt8 DEF_m_infoRam_1_rdReqQ_full_lat_0_whas____d36;
  tUInt8 DEF_m_infoRam_1_rdReqQ_full_lat_0_wget____d37;
  tUInt8 DEF_m_infoRam_1_rdReqQ_empty_rl__h3758;
  tUInt8 DEF_m_infoRam_0_rdReqQ_full_rl__h69273;
  tUInt8 DEF_m_infoRam_0_rdReqQ_full_lat_0_whas____d15;
  tUInt8 DEF_m_infoRam_0_rdReqQ_full_lat_0_wget____d16;
  tUInt8 DEF_m_infoRam_0_rdReqQ_empty_rl__h1453;
  tUInt64 DEF_x__h33601;
  tUInt64 DEF_x__h34007;
  tUInt64 DEF_x__h34803;
  tUInt64 DEF_tag__h49751;
  tUInt64 DEF_addr__h49750;
  tUInt64 DEF_x_b_read_tag__h53747;
  tUInt64 DEF__read_tag__h53737;
  tUInt64 DEF_x_b_read_tag__h53140;
  tUInt64 DEF__read_tag__h53130;
  tUInt64 DEF_x_b_read_tag__h52522;
  tUInt64 DEF__read_tag__h52512;
  tUInt64 DEF__read_tag__h51333;
  tUInt64 DEF_x_b_read_tag__h51343;
  tUInt64 DEF_t__h50439;
  tUInt64 DEF_t__h52358;
  tUInt64 DEF_t__h52976;
  tUInt64 DEF_t__h53583;
  tUInt64 DEF_x_rdResp_tag__h53752;
  tUInt64 DEF_x_rdResp_tag__h53145;
  tUInt64 DEF_x_rdResp_tag__h52527;
  tUInt64 DEF_x_rdResp_tag__h51348;
  tUInt8 DEF_y_avValue_way__h54222;
  tUInt8 DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d1146;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833___d228;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d664;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d653;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe__ETC___d495;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d646;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d461;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d627;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe__ETC___d589;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831___d245;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe_enq_ETC___d644;
  tUInt8 DEF_IF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pi_ETC___d633;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d610;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d556;
  tUInt8 DEF_SEL_ARR_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_ETC___d678;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d655;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d682;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe__ETC___d531;
  tUWide DEF_m_pipe_mat2Out_rl___d359;
  tUWide DEF_m_pipe_mat2Out_lat_0_wget____d357;
  tUInt64 DEF_m_infoRam_3_currentWriteData___d595;
  tUInt64 DEF_m_infoRam_3_bram_b_read____d597;
  tUInt64 DEF_m_infoRam_2_currentWriteData___d541;
  tUInt64 DEF_m_infoRam_2_bram_b_read____d543;
  tUInt64 DEF_m_infoRam_1_currentWriteData___d501;
  tUInt64 DEF_m_infoRam_1_bram_b_read____d503;
  tUInt64 DEF_m_infoRam_0_currentWriteData___d446;
  tUInt64 DEF_m_infoRam_0_bram_b_read____d448;
  tUInt8 DEF_m_pipe_mat2Out_lat_0_whas____d356;
  tUInt8 DEF_x__h32698;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_763___d569;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_708___d608;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_704___d533;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_649___d554;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_645___d481;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_590___d510;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_586___d436;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_531___d459;
  tUInt8 DEF_m_pipe_enq2Mat_lat_0_wget__25_BIT_833___d226;
  tUInt8 DEF_m_pipe_mat2Out_rl_59_BIT_651___d360;
  tUInt8 DEF_m_infoRam_3_bram_b_read__97_BIT_3___d606;
  tUInt8 DEF_m_infoRam_3_currentWriteData_95_BIT_3___d605;
  tUInt8 DEF_m_infoRam_2_bram_b_read__43_BIT_3___d552;
  tUInt8 DEF_m_infoRam_2_currentWriteData_41_BIT_3___d551;
  tUInt8 DEF_m_infoRam_1_bram_b_read__03_BIT_3___d514;
  tUInt8 DEF_m_infoRam_1_currentWriteData_01_BIT_3___d512;
  tUInt8 DEF_m_infoRam_0_currentWriteData_46_BIT_3___d456;
  tUInt8 DEF_m_infoRam_0_bram_b_read__48_BIT_3___d457;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d453;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d508;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d548;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d602;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d670;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d658;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_586_36_THEN_m_pipe_ETC___d634;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_645_81_THEN_m_pipe_ETC___d638;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe_enq_ETC___d440;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_pipe_ETC___d591;
  tUInt8 DEF_m_infoRam_3_readAddr_port0__read__92_EQ_m_info_ETC___d594;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_pipe_ETC___d537;
  tUInt8 DEF_m_infoRam_2_readAddr_port0__read__38_EQ_m_info_ETC___d540;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_pipe_ETC___d497;
  tUInt8 DEF_m_infoRam_1_readAddr_port0__read__98_EQ_m_info_ETC___d500;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_pipe_ETC___d442;
  tUInt8 DEF_m_infoRam_0_readAddr_port0__read__43_EQ_m_info_ETC___d445;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ__ETC___d719;
  tUInt8 DEF_IF_IF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_ETC___d745;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d667;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ_2___d248;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe__ETC___d568;
  tUInt8 DEF_IF_m_infoRam_3_readAddr_port0__read__92_EQ_m_i_ETC___d673;
  tUInt8 DEF_IF_m_infoRam_3_readAddr_port0__read__92_EQ_m_i_ETC___d607;
  tUInt8 DEF_NOT_m_pipe_enq2Mat_rl_27_BIT_708_08___d674;
  tUInt8 DEF_IF_m_infoRam_2_readAddr_port0__read__38_EQ_m_i_ETC___d583;
  tUInt8 DEF_IF_m_infoRam_2_readAddr_port0__read__38_EQ_m_i_ETC___d553;
  tUInt8 DEF_NOT_m_pipe_enq2Mat_rl_27_BIT_649_54___d580;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_m_pipe__ETC___d479;
  tUInt8 DEF_IF_m_infoRam_1_readAddr_port0__read__98_EQ_m_i_ETC___d625;
  tUInt8 DEF_IF_m_infoRam_1_readAddr_port0__read__98_EQ_m_i_ETC___d516;
  tUInt8 DEF_NOT_m_pipe_enq2Mat_rl_27_BIT_590_10___d511;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d630;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d478;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d587;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d588;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d528;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d529;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d493;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d494;
  tUInt8 DEF_IF_m_infoRam_0_readAddr_port0__read__43_EQ_m_i_ETC___d489;
  tUInt8 DEF_IF_m_infoRam_0_readAddr_port0__read__43_EQ_m_i_ETC___d458;
  tUInt8 DEF_NOT_m_pipe_enq2Mat_rl_27_BIT_531_59___d486;
  tUInt8 DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d361;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ_0___d246;
  tUInt8 DEF_NOT_m_pipe_enq2Mat_rl_27_BIT_833_28___d435;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ_1___d247;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d619;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d565;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d526;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d476;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d603;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d549;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d509;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_m_p_ETC___d454;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d624;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d604;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d586;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d550;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d527;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d492;
  tUInt8 DEF_NOT_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_NOT_ETC___d455;
 
 /* Local definitions */
 private:
  tUWide DEF_m_pipe_enq2Mat_lat_1_wget____d222;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_IF_m_pip_ETC___d263;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_whas__24_THEN_IF_m_pip_ETC___d262;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pipe_e_ETC___d291;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_whas__24_THEN_m_pipe_e_ETC___d290;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_IF_m_pip_ETC___d281;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_9_TO_8___d316;
  tUWide DEF_m_pipe_mat2Out_lat_1_wget____d354;
  tUWide DEF_m_dataRam_3_currentWriteData___d859;
  tUWide DEF_m_dataRam_3_bram_b_read____d861;
  tUWide DEF_m_dataRam_2_currentWriteData___d851;
  tUWide DEF_m_dataRam_2_bram_b_read____d853;
  tUWide DEF_m_dataRam_1_currentWriteData___d843;
  tUWide DEF_m_dataRam_1_bram_b_read____d845;
  tUWide DEF_m_dataRam_0_currentWriteData___d835;
  tUWide DEF_m_dataRam_0_bram_b_read____d837;
  tUWide DEF_m_pipe_mat2Out_rl_59_BITS_581_TO_0___d421;
  tUWide DEF_m_pipe_mat2Out_lat_1_wget__54_BITS_581_TO_0___d419;
  tUWide DEF_m_pipe_mat2Out_lat_0_wget__57_BITS_581_TO_0___d420;
  tUWide DEF_m_pipe_mat2Out_rl_59_BITS_519_TO_0___d1143;
  tUWide DEF_m_pipe_mat2Out_lat_0_wget__57_BITS_519_TO_0___d1140;
  tUWide DEF_m_pipe_enq2Mat_rl_27_BITS_526_TO_10___d299;
  tUWide DEF_m_pipe_enq2Mat_lat_1_wget__22_BITS_526_TO_10___d297;
  tUWide DEF_m_pipe_enq2Mat_lat_0_wget__25_BITS_526_TO_10___d298;
  tUWide DEF_send_r_BITS_518_TO_2___d1070;
  tUWide DEF_m_pipe_enq2Mat_rl_27_BITS_525_TO_10___d831;
  tUWide DEF_deqWrite_wrRam_BITS_515_TO_0___d1180;
  tUWide DEF_m_pipe_enq2Mat_rl_27_BITS_763_TO_528___d289;
  tUWide DEF_m_pipe_enq2Mat_lat_1_wget__22_BITS_763_TO_528___d287;
  tUWide DEF_m_pipe_enq2Mat_lat_0_wget__25_BITS_763_TO_528___d288;
  tUWide DEF_m_pipe_enq2Mat_rl_27_BITS_832_TO_764___d774;
  tUWide DEF_m_pipe_enq2Mat_rl_27_BITS_830_TO_764___d260;
  tUWide DEF_m_pipe_enq2Mat_lat_1_wget__22_BITS_830_TO_764___d256;
  tUWide DEF_m_pipe_enq2Mat_lat_0_wget__25_BITS_830_TO_764___d258;
  tUWide DEF_m_pipe_mat2Out_rl_59_BITS_648_TO_582___d392;
  tUWide DEF_m_pipe_mat2Out_lat_1_wget__54_BITS_648_TO_582___d388;
  tUWide DEF_m_pipe_mat2Out_lat_0_wget__57_BITS_648_TO_582___d390;
  tUWide DEF_send_r_BITS_66_TO_0___d1058;
  tUWide DEF_m_pipe_enq2Mat_rl_27_BITS_829_TO_764___d270;
  tUWide DEF_m_pipe_enq2Mat_lat_1_wget__22_BITS_829_TO_764___d266;
  tUWide DEF_m_pipe_enq2Mat_lat_0_wget__25_BITS_829_TO_764___d268;
  tUWide DEF_m_pipe_mat2Out_rl_59_BITS_647_TO_582___d402;
  tUWide DEF_m_pipe_mat2Out_lat_1_wget__54_BITS_647_TO_582___d398;
  tUWide DEF_m_pipe_mat2Out_lat_0_wget__57_BITS_647_TO_582___d400;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_7_TO_5___d331;
  tUInt8 DEF_m_pipe_mat2Out_rl_59_BITS_650_TO_649___d377;
  tUInt8 DEF_m_pipe_mat2Out_lat_0_wget__57_BITS_650_TO_649___d370;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_m_pipe_m_ETC___d423;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d422;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d1145;
  tUWide DEF_m_pipe_mat2Out_lat_0_wget__57_BITS_581_TO_521__ETC___d1141;
  tUWide DEF_m_pipe_mat2Out_rl_59_BITS_581_TO_521_142_CONCA_ETC___d1144;
  tUWide DEF_IF_send_r_BITS_587_TO_586_041_EQ_0_042_OR_send_ETC___d1071;
  tUWide DEF__0_CONCAT_DONTCARE___d1069;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pipe_e_ETC___d301;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_whas__24_THEN_m_pipe_e_ETC___d300;
  tUWide DEF_IF_m_pipe_enq2Mat_rl_27_BIT_526_69_THEN_m_pipe_ETC___d1026;
  tUWide DEF_SEL_ARR_IF_m_dataRam_0_readAddr_port0__read__3_ETC___d1025;
  tUWide DEF_IF_send_r_BITS_587_TO_586_041_EQ_0_042_THEN_0__ETC___d1065;
  tUWide DEF__0_CONCAT_send_r_BITS_66_TO_0_058___d1059;
  tUWide DEF_send_r_BITS_587_TO_586_041_CONCAT_send_r_BITS__ETC___d1060;
  tUWide DEF__2_CONCAT_DONTCARE_CONCAT_send_r_BITS_585_TO_52_ETC___d1063;
  tUWide DEF_IF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_m_pip_ETC___d417;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_IF_m_pip_ETC___d395;
  tUWide DEF_IF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_m_pip_ETC___d416;
  tUWide DEF_DONTCARE_CONCAT_IF_m_pipe_mat2Out_lat_1_whas___ETC___d406;
  tUWide DEF_IF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_m_pip_ETC___d415;
  tUWide DEF_DONTCARE_CONCAT_IF_m_pipe_mat2Out_lat_1_whas___ETC___d414;
  tUWide DEF_IF_m_pipe_mat2Out_rl_59_BITS_650_TO_649_77_EQ__ETC___d393;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_wget__57_BITS_650_TO_6_ETC___d391;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_wget__54_BITS_650_TO_6_ETC___d389;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_IF_m_pip_ETC___d394;
  tUWide DEF_IF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pip_ETC___d285;
  tUWide DEF_IF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pip_ETC___d284;
  tUWide DEF_DONTCARE_CONCAT_IF_m_pipe_enq2Mat_lat_1_whas___ETC___d274;
  tUWide DEF_IF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pip_ETC___d283;
  tUWide DEF_DONTCARE_CONCAT_IF_m_pipe_enq2Mat_lat_1_whas___ETC___d282;
  tUWide DEF_IF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ__ETC___d261;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_wget__25_BITS_832_TO_8_ETC___d259;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_wget__22_BITS_832_TO_8_ETC___d257;
  tUWide DEF_IF_m_pipe_mat2Out_rl_59_BITS_650_TO_649_77_EQ__ETC___d411;
  tUWide DEF_IF_m_pipe_mat2Out_rl_59_BITS_650_TO_649_77_EQ__ETC___d403;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_wget__57_BITS_650_TO_6_ETC___d410;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_wget__57_BITS_650_TO_6_ETC___d401;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_wget__54_BITS_650_TO_6_ETC___d409;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_wget__54_BITS_650_TO_6_ETC___d399;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_IF_m_pip_ETC___d413;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_IF_m_pip_ETC___d412;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_IF_m_pip_ETC___d405;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_IF_m_pip_ETC___d404;
  tUWide DEF_IF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ__ETC___d279;
  tUWide DEF_IF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ__ETC___d271;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_wget__25_BITS_832_TO_8_ETC___d278;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_wget__25_BITS_832_TO_8_ETC___d269;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_wget__22_BITS_832_TO_8_ETC___d277;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_wget__22_BITS_832_TO_8_ETC___d267;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_IF_m_pip_ETC___d273;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_whas__24_THEN_IF_m_pip_ETC___d272;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_0_whas__24_THEN_IF_m_pip_ETC___d280;
  tUInt8 DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d1122;
  tUInt8 DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d1129;
  tUInt8 DEF_IF_m_pipe_enq2Mat_rl_27_BITS_9_TO_8_16_EQ_2_19_ETC___d339;
  tUInt8 DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d386;
  tUInt8 DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d396;
  tUInt8 DEF_m_pipe_enq2Mat_rl_27_BITS_9_TO_8_16_EQ_1___d318;
  tUWide DEF__1_CONCAT_IF_send_r_BITS_587_TO_586_041_EQ_0_04_ETC___d1079;
  tUWide DEF__0_CONCAT_DONTCARE_066_CONCAT_0_CONCAT_DONTCARE_ETC___d1078;
  tUWide DEF__0_CONCAT_DONTCARE___d1040;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pipe_e_ETC___d352;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_IF_m_pip_ETC___d286;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pipe_e_ETC___d351;
  tUWide DEF_IF_m_pipe_enq2Mat_lat_1_whas__21_THEN_m_pipe_e_ETC___d350;
  tUWide DEF__0_CONCAT_DONTCARE_066_CONCAT_0_CONCAT_DONTCARE_ETC___d1067;
  tUWide DEF_IF_send_r_BITS_587_TO_586_041_EQ_0_042_OR_send_ETC___d1077;
  tUWide DEF__1_CONCAT_m_pipe_enq2Mat_rl_27_BITS_832_TO_764__ETC___d1039;
  tUWide DEF_IF_m_pipe_enq2Mat_rl_27_BITS_832_TO_831_45_EQ__ETC___d1038;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_m_pipe_m_ETC___d424;
  tUWide DEF_IF_m_pipe_mat2Out_lat_1_whas__53_THEN_IF_m_pip_ETC___d418;
  tUWide DEF_deqWrite_swapRq_BIT_3_181_CONCAT_0_CONCAT_IF_I_ETC___d1187;
  tUWide DEF__0_CONCAT_IF_IF_m_pipe_mat2Out_lat_0_whas__56_T_ETC___d1183;
  tUWide DEF_IF_m_pipe_mat2Out_lat_0_whas__56_THEN_m_pipe_m_ETC___d1186;
  tUWide DEF_SEL_ARR_IF_m_pipe_enq2Mat_rl_27_BIT_833_28_AND_ETC___d1037;
  tUWide DEF_deqWrite_wrRam_BITS_573_TO_516_176_CONCAT_1_CO_ETC___d1185;
  tUWide DEF__1_CONCAT_deqWrite_wrRam_BITS_515_TO_0_180___d1184;
  tUWide DEF__1_CONCAT_IF_m_pipe_enq2Mat_rl_27_BIT_526_69_TH_ETC___d1027;
  tUWide DEF_SEL_ARR_IF_m_dataRam_0_readAddr_port0__read__3_ETC___d995;
  tUWide DEF_SEL_ARR_IF_m_dataRam_0_readAddr_port0__read__3_ETC___d1024;
  tUWide DEF_SEL_ARR_IF_m_dataRam_0_readAddr_port0__read__3_ETC___d937;
  tUWide DEF_SEL_ARR_IF_m_dataRam_0_readAddr_port0__read__3_ETC___d966;
  tUWide DEF_send_r_BITS_585_TO_522_053_CONCAT_send_r_BITS__ETC___d1062;
 
 /* Rules */
 public:
  void RL_m_infoRam_0_rdReqQ_empty_canon();
  void RL_m_infoRam_0_rdReqQ_full_canon();
  void RL_m_infoRam_0_doRead();
  void RL_m_infoRam_1_rdReqQ_empty_canon();
  void RL_m_infoRam_1_rdReqQ_full_canon();
  void RL_m_infoRam_1_doRead();
  void RL_m_infoRam_2_rdReqQ_empty_canon();
  void RL_m_infoRam_2_rdReqQ_full_canon();
  void RL_m_infoRam_2_doRead();
  void RL_m_infoRam_3_rdReqQ_empty_canon();
  void RL_m_infoRam_3_rdReqQ_full_canon();
  void RL_m_infoRam_3_doRead();
  void RL_m_repRam_rdReqQ_empty_canon();
  void RL_m_repRam_rdReqQ_full_canon();
  void RL_m_dataRam_0_rdReqQ_empty_canon();
  void RL_m_dataRam_0_rdReqQ_full_canon();
  void RL_m_dataRam_0_doRead();
  void RL_m_dataRam_1_rdReqQ_empty_canon();
  void RL_m_dataRam_1_rdReqQ_full_canon();
  void RL_m_dataRam_1_doRead();
  void RL_m_dataRam_2_rdReqQ_empty_canon();
  void RL_m_dataRam_2_rdReqQ_full_canon();
  void RL_m_dataRam_2_doRead();
  void RL_m_dataRam_3_rdReqQ_empty_canon();
  void RL_m_dataRam_3_rdReqQ_full_canon();
  void RL_m_dataRam_3_doRead();
  void RL_m_queueRam_rdReqQ_empty_canon();
  void RL_m_queueRam_rdReqQ_full_canon();
  void RL_m_queueRam_doRead();
  void RL_m_doInit();
  void RL_m_randRep_tick();
  void RL_m_pipe_enq2Mat_canon();
  void RL_m_pipe_mat2Out_canon();
  void RL_m_pipe_doTagMatch();
 
 /* Methods */
 public:
  void METH_send(tUWide ARG_send_r);
  tUInt8 METH_RDY_send();
  tUWide METH_first();
  tUInt8 METH_RDY_first();
  void METH_deqWrite(tUInt8 ARG_deqWrite_swapRq,
		     tUWide ARG_deqWrite_wrRam,
		     tUInt8 ARG_deqWrite_nextInQueue,
		     tUInt8 ARG_deqWrite_updateRep);
  tUInt8 METH_RDY_deqWrite();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkDPipeline &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkDPipeline &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkDPipeline &backing);
};

#endif /* ifndef __mkDPipeline_h__ */
