/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Thu Jun  4 21:58:12 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_prepareBoundsCheck.h"


/* Constructor */
MOD_module_prepareBoundsCheck::MOD_module_prepareBoundsCheck(tSimStateHdl simHdl,
							     char const *name,
							     Module *parent)
  : Module(simHdl, name, parent),
    DEF_ret__h1263(65u),
    DEF_ret__h3069(65u),
    DEF_x__h2870(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125(65u),
    DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152(65u),
    DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159(65u),
    DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163(65u),
    DEF_x__h1249(65u),
    DEF_result__h1854(65u),
    DEF_result__h3603(65u),
    DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67(65u),
    DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132(65u),
    DEF_addTop__h1261(65u),
    DEF_addTop__h3067(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161(65u),
    DEF__0_CONCAT_prepareBoundsCheck_size___d162(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158(65u),
    DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50(65u),
    DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131(65u),
    DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172(201u),
    DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171(130u)
{
  PORT_prepareBoundsCheck_a.setSize(161u);
  PORT_prepareBoundsCheck_a.clear();
  PORT_prepareBoundsCheck_b.setSize(161u);
  PORT_prepareBoundsCheck_b.clear();
  PORT_prepareBoundsCheck_pcc.setSize(161u);
  PORT_prepareBoundsCheck_pcc.clear();
  PORT_prepareBoundsCheck_ddc.setSize(161u);
  PORT_prepareBoundsCheck_ddc.clear();
  PORT_prepareBoundsCheck.setSize(266u);
  PORT_prepareBoundsCheck.clear();
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_prepareBoundsCheck::init_symbols_0()
{
  init_symbol(&symbols[0u], "prepareBoundsCheck", SYM_PORT, &PORT_prepareBoundsCheck, 266u);
  init_symbol(&symbols[1u], "prepareBoundsCheck_a", SYM_PORT, &PORT_prepareBoundsCheck_a, 161u);
  init_symbol(&symbols[2u], "prepareBoundsCheck_b", SYM_PORT, &PORT_prepareBoundsCheck_b, 161u);
  init_symbol(&symbols[3u], "prepareBoundsCheck_ddc", SYM_PORT, &PORT_prepareBoundsCheck_ddc, 161u);
  init_symbol(&symbols[4u], "prepareBoundsCheck_pcc", SYM_PORT, &PORT_prepareBoundsCheck_pcc, 161u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_prepareBoundsCheck::METH_prepareBoundsCheck(tUWide ARG_prepareBoundsCheck_a,
							      tUWide ARG_prepareBoundsCheck_b,
							      tUWide ARG_prepareBoundsCheck_pcc,
							      tUWide ARG_prepareBoundsCheck_ddc,
							      tUInt64 ARG_prepareBoundsCheck_vaddr,
							      tUInt8 ARG_prepareBoundsCheck_size,
							      tUInt64 ARG_prepareBoundsCheck_toCheck)
{
  tUInt64 DEF_x__h127;
  tUInt64 DEF_mask__h2476;
  tUInt64 DEF_mask__h311;
  tUInt64 DEF_mask__h3068;
  tUInt64 DEF_mask__h1262;
  tUInt64 DEF_addBase__h2475;
  tUInt64 DEF_addBase__h310;
  tUInt8 DEF_x__h1813;
  tUInt8 DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101;
  tUInt8 DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23;
  tUInt32 DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53;
  tUInt32 DEF_x__h1323;
  tUInt32 DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29;
  tUInt32 DEF_x__h1033;
  tUInt64 DEF_x__h2025;
  tUInt8 DEF_prepareBoundsCheck_toCheck_BIT_21___d1;
  tUInt32 DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75;
  tUInt8 DEF__1__h3533;
  tUInt8 DEF__1__h1784;
  tUInt8 DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2;
  tUInt8 DEF_x__h3562;
  tUInt8 DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30;
  tUInt8 DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33;
  tUInt8 DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36;
  tUInt8 DEF_topTip__h3070;
  tUInt8 DEF_topTip__h1264;
  tUInt8 DEF_thin_otype__h3952;
  tUInt8 DEF__theResult___fst_authority_idx__h1926;
  tUInt8 DEF__theResult___fst_authority_idx__h1920;
  tUInt8 DEF_x__h3591;
  tUInt32 DEF_a_capFat_bounds_baseBits__h831;
  tUInt32 DEF_a_capFat_bounds_topBits__h830;
  tUInt32 DEF_b_capFat_bounds_baseBits__h837;
  tUInt32 DEF_b_capFat_bounds_topBits__h836;
  tUInt32 DEF_pcc_capFat_bounds_baseBits__h843;
  tUInt32 DEF_pcc_capFat_bounds_topBits__h842;
  tUInt32 DEF_ddc_capFat_bounds_baseBits__h849;
  tUInt32 DEF_ddc_capFat_bounds_topBits__h848;
  tUInt64 DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105;
  tUInt64 DEF__theResult___snd_capFat_address__h744;
  tUInt64 DEF_x_BITS_63_TO_14___h1810;
  tUInt64 DEF_cap_address__h3912;
  tUInt64 DEF_cap_address__h4105;
  tUInt64 DEF_pcc_capFat_address__h676;
  tUInt64 DEF_ddc_capFat_address__h700;
  PORT_prepareBoundsCheck_a = ARG_prepareBoundsCheck_a;
  PORT_prepareBoundsCheck_b = ARG_prepareBoundsCheck_b;
  PORT_prepareBoundsCheck_pcc = ARG_prepareBoundsCheck_pcc;
  PORT_prepareBoundsCheck_ddc = ARG_prepareBoundsCheck_ddc;
  DEF_ddc_capFat_address__h700 = primExtract64(64u,
					       161u,
					       ARG_prepareBoundsCheck_ddc,
					       32u,
					       159u,
					       32u,
					       96u);
  DEF_pcc_capFat_address__h676 = primExtract64(64u,
					       161u,
					       ARG_prepareBoundsCheck_pcc,
					       32u,
					       159u,
					       32u,
					       96u);
  DEF_cap_address__h4105 = primExtract64(64u, 161u, ARG_prepareBoundsCheck_b, 32u, 159u, 32u, 96u);
  DEF_cap_address__h3912 = primExtract64(64u, 161u, ARG_prepareBoundsCheck_a, 32u, 159u, 32u, 96u);
  DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105 = primExtract64(50u,
								  161u,
								  ARG_prepareBoundsCheck_a,
								  32u,
								  159u,
								  32u,
								  110u);
  DEF_ddc_capFat_bounds_topBits__h848 = primExtract32(14u,
						      161u,
						      ARG_prepareBoundsCheck_ddc,
						      32u,
						      37u,
						      32u,
						      24u);
  DEF_ddc_capFat_bounds_baseBits__h849 = ARG_prepareBoundsCheck_ddc.get_bits_in_word32(0u, 10u, 14u);
  DEF_pcc_capFat_bounds_topBits__h842 = primExtract32(14u,
						      161u,
						      ARG_prepareBoundsCheck_pcc,
						      32u,
						      37u,
						      32u,
						      24u);
  DEF_pcc_capFat_bounds_baseBits__h843 = ARG_prepareBoundsCheck_pcc.get_bits_in_word32(0u, 10u, 14u);
  DEF_b_capFat_bounds_topBits__h836 = primExtract32(14u,
						    161u,
						    ARG_prepareBoundsCheck_b,
						    32u,
						    37u,
						    32u,
						    24u);
  DEF_b_capFat_bounds_baseBits__h837 = ARG_prepareBoundsCheck_b.get_bits_in_word32(0u, 10u, 14u);
  DEF_a_capFat_bounds_topBits__h830 = primExtract32(14u,
						    161u,
						    ARG_prepareBoundsCheck_a,
						    32u,
						    37u,
						    32u,
						    24u);
  DEF_a_capFat_bounds_baseBits__h831 = ARG_prepareBoundsCheck_a.get_bits_in_word32(0u, 10u, 14u);
  DEF_x__h3591 = ARG_prepareBoundsCheck_a.get_bits_in_word8(1u, 6u, 6u);
  DEF__theResult___fst_authority_idx__h1920 = (tUInt8)((tUInt8)63u & (ARG_prepareBoundsCheck_toCheck >> 6u));
  DEF__theResult___fst_authority_idx__h1926 = (tUInt8)((tUInt8)63u & ARG_prepareBoundsCheck_toCheck);
  DEF_thin_otype__h3952 = ARG_prepareBoundsCheck_a.get_bits_in_word8(1u, 13u, 4u);
  DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36 = ARG_prepareBoundsCheck_ddc.get_bits_in_word8(0u,
											      0u,
											      2u);
  DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33 = ARG_prepareBoundsCheck_pcc.get_bits_in_word8(0u,
											      0u,
											      2u);
  DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30 = ARG_prepareBoundsCheck_b.get_bits_in_word8(0u, 0u, 2u);
  DEF_prepareBoundsCheck_toCheck_BIT_21___d1 = (tUInt8)((tUInt8)1u & (ARG_prepareBoundsCheck_toCheck >> 21u));
  DEF_x__h3562 = ARG_prepareBoundsCheck_a.get_bits_in_word8(0u, 0u, 2u);
  DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2 = (tUInt8)((tUInt8)3u & (ARG_prepareBoundsCheck_toCheck >> 19u));
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF__theResult___snd_capFat_address__h744 = DEF_cap_address__h3912;
    break;
  case (tUInt8)1u:
    DEF__theResult___snd_capFat_address__h744 = DEF_cap_address__h4105;
    break;
  case (tUInt8)2u:
    DEF__theResult___snd_capFat_address__h744 = DEF_pcc_capFat_address__h676;
    break;
  default:
    DEF__theResult___snd_capFat_address__h744 = DEF_ddc_capFat_address__h700;
  }
  DEF_x_BITS_63_TO_14___h1810 = (tUInt64)(DEF__theResult___snd_capFat_address__h744 >> 14u);
  DEF__1__h3533 = (tUInt8)((1125899906842623llu & (DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105 + primShiftL64(50u,
														  50u,
														  (tUInt64)(primSignExt64(50u,
																	  2u,
																	  (tUInt8)(DEF_x__h3562))),
														  6u,
														  (tUInt8)(DEF_x__h3591)))) >> 49u);
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_a_capFat_bounds_baseBits__h831;
    break;
  case (tUInt8)1u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_b_capFat_bounds_baseBits__h837;
    break;
  case (tUInt8)2u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_pcc_capFat_bounds_baseBits__h843;
    break;
  default:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 = DEF_ddc_capFat_bounds_baseBits__h849;
  }
  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)((DEF_cap_address__h3912 + 2llu) >> 32u))),
									      32u,
									      33u).set_whole_word((tUInt32)(DEF_cap_address__h3912 + 2llu),
												  0u);
  DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154.set_bits_in_word((tUInt8)(0llu),
									      2u,
									      0u,
									      1u).set_whole_word((tUInt32)(0llu),
												 1u).set_whole_word((((tUInt32)(268435455u & 0llu)) << 4u) | (tUInt32)(DEF_thin_otype__h3952),
														    0u);
  DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)(DEF_cap_address__h4105 >> 32u))),
									  32u,
									  33u).set_whole_word((tUInt32)(DEF_cap_address__h4105),
											      0u);
  DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29 = 65535u & ((((tUInt32)(DEF_x__h3562)) << 14u) | DEF_a_capFat_bounds_baseBits__h831);
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_x__h1033 = DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29;
    break;
  case (tUInt8)1u:
    DEF_x__h1033 = 65535u & ((((tUInt32)(DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30)) << 14u) | DEF_b_capFat_bounds_baseBits__h837);
    break;
  case (tUInt8)2u:
    DEF_x__h1033 = 65535u & ((((tUInt32)(DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33)) << 14u) | DEF_pcc_capFat_bounds_baseBits__h843);
    break;
  default:
    DEF_x__h1033 = 65535u & ((((tUInt32)(DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36)) << 14u) | DEF_ddc_capFat_bounds_baseBits__h849);
  }
  DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_a.get_bits_in_word8(0u,
																  2u,
																  2u))) << 14u) | DEF_a_capFat_bounds_topBits__h830);
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_x__h1323 = DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53;
    break;
  case (tUInt8)1u:
    DEF_x__h1323 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_b.get_bits_in_word8(0u,
										    2u,
										    2u))) << 14u) | DEF_b_capFat_bounds_topBits__h836);
    break;
  case (tUInt8)2u:
    DEF_x__h1323 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_pcc.get_bits_in_word8(0u,
										      2u,
										      2u))) << 14u) | DEF_pcc_capFat_bounds_topBits__h842);
    break;
  default:
    DEF_x__h1323 = 65535u & ((((tUInt32)(ARG_prepareBoundsCheck_ddc.get_bits_in_word8(0u,
										      2u,
										      2u))) << 14u) | DEF_ddc_capFat_bounds_topBits__h848);
  }
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = DEF_x__h3591;
    break;
  case (tUInt8)1u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = ARG_prepareBoundsCheck_b.get_bits_in_word8(1u,
													      6u,
													      6u);
    break;
  case (tUInt8)2u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = ARG_prepareBoundsCheck_pcc.get_bits_in_word8(1u,
														6u,
														6u);
    break;
  default:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 = ARG_prepareBoundsCheck_ddc.get_bits_in_word8(1u,
														6u,
														6u);
  }
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = DEF__theResult___fst_authority_idx__h1920;
    break;
  case (tUInt8)1u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = DEF__theResult___fst_authority_idx__h1926;
    break;
  case (tUInt8)2u:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = (tUInt8)32u;
    break;
  default:
    DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101 = (tUInt8)33u;
  }
  switch (DEF_prepareBoundsCheck_toCheck_BITS_20_TO_19___d2) {
  case (tUInt8)0u:
    DEF_x__h1813 = DEF_x__h3562;
    break;
  case (tUInt8)1u:
    DEF_x__h1813 = DEF_prepareBoundsCheck_b_BITS_1_TO_0___d30;
    break;
  case (tUInt8)2u:
    DEF_x__h1813 = DEF_prepareBoundsCheck_pcc_BITS_1_TO_0___d33;
    break;
  default:
    DEF_x__h1813 = DEF_prepareBoundsCheck_ddc_BITS_1_TO_0___d36;
  }
  DEF__1__h1784 = (tUInt8)((1125899906842623llu & (DEF_x_BITS_63_TO_14___h1810 + primShiftL64(50u,
											      50u,
											      (tUInt64)(primSignExt64(50u,
														      2u,
														      (tUInt8)(DEF_x__h1813))),
											      6u,
											      (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23)))) >> 49u);
  wop_primSignExtWide(65u,
		      16u,
		      (tUInt32)(DEF_x__h1323),
		      DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67);
  wop_primSignExtWide(65u,
		      16u,
		      (tUInt32)(DEF_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_prep_ETC___d53),
		      DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132);
  wop_primShiftLWide(65u,
		     65u,
		     DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67,
		     6u,
		     (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23),
		     DEF_addTop__h1261);
  wop_primShiftLWide(65u,
		     65u,
		     DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132,
		     6u,
		     (tUInt8)(DEF_x__h3591),
		     DEF_addTop__h3067);
  DEF_addBase__h310 = primShiftL64(64u,
				   64u,
				   (tUInt64)(primSignExt64(64u, 16u, (tUInt32)(DEF_x__h1033))),
				   6u,
				   (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23));
  DEF_addBase__h2475 = primShiftL64(64u,
				    64u,
				    (tUInt64)(primSignExt64(64u,
							    16u,
							    (tUInt32)(DEF_prepareBoundsCheck_a_BITS_1_TO_0_7_CONCAT_prep_ETC___d29))),
				    6u,
				    (tUInt8)(DEF_x__h3591));
  DEF_mask__h1262 = primShiftL64(51u,
				 51u,
				 2251799813685247llu,
				 6u,
				 (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23));
  DEF_mask__h311 = primShiftL64(50u,
				50u,
				1125899906842623llu,
				6u,
				(tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23));
  DEF_mask__h3068 = primShiftL64(51u, 51u, 2251799813685247llu, 6u, (tUInt8)(DEF_x__h3591));
  DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)(ARG_prepareBoundsCheck_vaddr >> 32u))),
							       32u,
							       33u).set_whole_word((tUInt32)(ARG_prepareBoundsCheck_vaddr),
										   0u);
  DEF_mask__h2476 = primShiftL64(50u, 50u, 1125899906842623llu, 6u, (tUInt8)(DEF_x__h3591));
  switch ((tUInt8)((tUInt8)7u & (ARG_prepareBoundsCheck_toCheck >> 16u))) {
  case (tUInt8)0u:
    DEF_x__h2025 = DEF_cap_address__h3912;
    break;
  case (tUInt8)1u:
    DEF_x__h2025 = (((DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105 & DEF_mask__h2476) << 14u) | (tUInt64)(0u)) + DEF_addBase__h2475;
    break;
  case (tUInt8)2u:
    DEF_x__h2025 = (tUInt64)(DEF_thin_otype__h3952);
    break;
  case (tUInt8)3u:
    DEF_x__h2025 = DEF_cap_address__h4105;
    break;
  default:
    DEF_x__h2025 = ARG_prepareBoundsCheck_vaddr;
  }
  DEF__0_CONCAT_prepareBoundsCheck_size___d162.set_bits_in_word((tUInt8)(0llu),
								2u,
								0u,
								1u).set_whole_word((tUInt32)(0llu),
										   1u).set_whole_word((((tUInt32)(33554431u & 0llu)) << 7u) | (tUInt32)(ARG_prepareBoundsCheck_size),
												      0u);
  wop_add(DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161,
	  DEF__0_CONCAT_prepareBoundsCheck_size___d162,
	  DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163);
  DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158.build_concat(8589934591llu & ((((tUInt64)((tUInt8)0u)) << 32u) | (tUInt64)((tUInt32)(DEF_cap_address__h3912 >> 32u))),
									  32u,
									  33u).set_whole_word((tUInt32)(DEF_cap_address__h3912),
											      0u);
  wop_add(DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158,
	  DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156,
	  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159);
  DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50.set_bits_in_word((tUInt8)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_x_BITS_63_TO_14___h1810)) & DEF_mask__h1262) >> 50u),
										 2u,
										 0u,
										 1u).set_whole_word((tUInt32)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_x_BITS_63_TO_14___h1810)) & DEF_mask__h1262) >> 18u),
												    1u).set_whole_word(((tUInt32)(262143u & ((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_x_BITS_63_TO_14___h1810)) & DEF_mask__h1262))) << 14u,
														       0u);
  wop_add(DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50,
	  DEF_addTop__h1261,
	  DEF_ret__h1263);
  DEF_topTip__h1264 = primExtract8(2u, 65u, DEF_ret__h1263, 32u, 64u, 32u, 63u);
  DEF_result__h1854.build_concat(8589934591llu & ((((tUInt64)((tUInt8)1u & ~DEF_ret__h1263.get_bits_in_word8(2u,
													     0u,
													     1u))) << 32u) | (tUInt64)(DEF_ret__h1263.get_whole_word(1u))),
				 32u,
				 33u).set_whole_word(DEF_ret__h1263.get_whole_word(0u), 0u);
  DEF_x__h1249 = DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 < (tUInt8)51u && !(((tUInt8)3u & (DEF_topTip__h1264 - ((tUInt8)3u & (DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d23 == (tUInt8)50u ? (tUInt8)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d75 >> 13u) : DEF__1__h1784)))) <= (tUInt8)1u) ? DEF_result__h1854 : DEF_ret__h1263;
  DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131.set_bits_in_word((tUInt8)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105)) & DEF_mask__h3068) >> 50u),
										  2u,
										  0u,
										  1u).set_whole_word((tUInt32)(((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105)) & DEF_mask__h3068) >> 18u),
												     1u).set_whole_word(((tUInt32)(262143u & ((2251799813685247llu & ((((tUInt64)((tUInt8)0u)) << 50u) | DEF_prepareBoundsCheck_a_BITS_159_TO_110___d105)) & DEF_mask__h3068))) << 14u,
															0u);
  wop_add(DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131,
	  DEF_addTop__h3067,
	  DEF_ret__h3069);
  DEF_topTip__h3070 = primExtract8(2u, 65u, DEF_ret__h3069, 32u, 64u, 32u, 63u);
  DEF_result__h3603.build_concat(8589934591llu & ((((tUInt64)((tUInt8)1u & ~DEF_ret__h3069.get_bits_in_word8(2u,
													     0u,
													     1u))) << 32u) | (tUInt64)(DEF_ret__h3069.get_whole_word(1u))),
				 32u,
				 33u).set_whole_word(DEF_ret__h3069.get_whole_word(0u), 0u);
  DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152 = DEF_x__h3591 < (tUInt8)51u && !(((tUInt8)3u & (DEF_topTip__h3070 - ((tUInt8)3u & (DEF_x__h3591 == (tUInt8)50u ? ARG_prepareBoundsCheck_a.get_bits_in_word8(0u,
																											     23u,
																											     1u) : DEF__1__h3533)))) <= (tUInt8)1u) ? DEF_result__h3603 : DEF_ret__h3069;
  switch ((tUInt8)((tUInt8)7u & (ARG_prepareBoundsCheck_toCheck >> 13u))) {
  case (tUInt8)0u:
    DEF_x__h2870 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
    break;
  case (tUInt8)1u:
    DEF_x__h2870 = DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
    break;
  case (tUInt8)2u:
    DEF_x__h2870 = DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154;
    break;
  case (tUInt8)3u:
    DEF_x__h2870 = DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
    break;
  case (tUInt8)4u:
    DEF_x__h2870 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
    break;
  default:
    DEF_x__h2870 = DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
  }
  DEF_x__h127 = (((DEF_x_BITS_63_TO_14___h1810 & DEF_mask__h311) << 14u) | (tUInt64)(0u)) + DEF_addBase__h310;
  DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.set_bits_in_word((tUInt8)(DEF_x__h2025 >> 62u),
										 4u,
										 0u,
										 2u).set_whole_word((tUInt32)(DEF_x__h2025 >> 30u),
												    3u).set_whole_word((((tUInt32)(1073741823u & DEF_x__h2025)) << 2u) | (tUInt32)(primExtract8(2u,
																								65u,
																								DEF_x__h2870,
																								32u,
																								64u,
																								32u,
																								63u)),
														       2u).set_whole_word(primExtract32(32u,
																			65u,
																			DEF_x__h2870,
																			32u,
																			62u,
																			32u,
																			31u),
																	  1u).set_whole_word((DEF_x__h2870.get_bits_in_word32(0u,
																							      0u,
																							      31u) << 1u) | (tUInt32)((tUInt8)((tUInt8)1u & (ARG_prepareBoundsCheck_toCheck >> 12u))),
																			     0u);
  DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.set_bits_in_word(primExtract32(9u,
											       65u,
											       DEF_x__h1249,
											       32u,
											       64u,
											       32u,
											       56u),
										 6u,
										 0u,
										 9u).set_whole_word(primExtract32(32u,
														  65u,
														  DEF_x__h1249,
														  32u,
														  55u,
														  32u,
														  24u),
												    5u).set_whole_word(((DEF_x__h1249.get_bits_in_word32(0u,
																			 0u,
																			 24u) << 8u) | (((tUInt32)(DEF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_EQ_ETC___d101)) << 2u)) | (tUInt32)(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_bits_in_word8(4u,
																																										       0u,
																																										       2u)),
														       4u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(3u),
																	  3u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(2u),
																			     2u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(1u),
																						1u).set_whole_word(DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171.get_whole_word(0u),
																								   0u);
  PORT_prepareBoundsCheck.set_bits_in_word(1023u & ((((tUInt32)(DEF_prepareBoundsCheck_toCheck_BIT_21___d1)) << 9u) | (tUInt32)(DEF_x__h127 >> 55u)),
					   8u,
					   0u,
					   10u).set_whole_word((tUInt32)(DEF_x__h127 >> 23u),
							       7u).set_whole_word((((tUInt32)(8388607u & DEF_x__h127)) << 9u) | DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_bits_in_word32(6u,
																										 0u,
																										 9u),
										  6u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(5u),
												     5u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(4u),
															4u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(3u),
																	   3u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(2u),
																			      2u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(1u),
																						 1u).set_whole_word(DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172.get_whole_word(0u),
																								    0u);
  return PORT_prepareBoundsCheck;
}

tUInt8 MOD_module_prepareBoundsCheck::METH_RDY_prepareBoundsCheck()
{
  tUInt8 PORT_RDY_prepareBoundsCheck;
  tUInt8 DEF_CAN_FIRE_prepareBoundsCheck;
  DEF_CAN_FIRE_prepareBoundsCheck = (tUInt8)1u;
  PORT_RDY_prepareBoundsCheck = DEF_CAN_FIRE_prepareBoundsCheck;
  return PORT_RDY_prepareBoundsCheck;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_prepareBoundsCheck::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_prepareBoundsCheck::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 29u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172", 201u);
  vcd_write_def(sim_hdl, num++, "IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152", 65u);
  vcd_write_def(sim_hdl, num++, "IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164", 65u);
  vcd_write_def(sim_hdl, num++, "IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171", 130u);
  vcd_write_def(sim_hdl, num++, "SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67", 65u);
  vcd_write_def(sim_hdl, num++, "SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132", 65u);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154", 65u);
  vcd_write_def(sim_hdl, num++, "_0_CONCAT_prepareBoundsCheck_size___d162", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163", 65u);
  vcd_write_def(sim_hdl, num++, "_0b0_CONCAT_prepareBoundsCheck_vaddr___d161", 65u);
  vcd_write_def(sim_hdl, num++, "addTop__h1261", 65u);
  vcd_write_def(sim_hdl, num++, "addTop__h3067", 65u);
  vcd_write_def(sim_hdl, num++, "result__h1854", 65u);
  vcd_write_def(sim_hdl, num++, "result__h3603", 65u);
  vcd_write_def(sim_hdl, num++, "ret__h1263", 65u);
  vcd_write_def(sim_hdl, num++, "ret__h3069", 65u);
  vcd_write_def(sim_hdl, num++, "x__h1249", 65u);
  vcd_write_def(sim_hdl, num++, "x__h2870", 65u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck", 266u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_a", 161u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_b", 161u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_ddc", 161u);
  vcd_write_def(sim_hdl, num++, "prepareBoundsCheck_pcc", 161u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_prepareBoundsCheck::dump_VCD(tVCDDumpType dt,
					     unsigned int levels,
					     MOD_module_prepareBoundsCheck &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_prepareBoundsCheck::vcd_defs(tVCDDumpType dt,
					     MOD_module_prepareBoundsCheck &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 201u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 130u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 65u);
    vcd_write_x(sim_hdl, num++, 266u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172) != DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172, 201u);
	backing.DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172 = DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172;
      }
      ++num;
      if ((backing.DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152) != DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152, 65u);
	backing.DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152 = DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
      }
      ++num;
      if ((backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164) != DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164, 65u);
	backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164 = DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
      }
      ++num;
      if ((backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171) != DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171, 130u);
	backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171 = DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171;
      }
      ++num;
      if ((backing.DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67) != DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67, 65u);
	backing.DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67 = DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67;
      }
      ++num;
      if ((backing.DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132) != DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132)
      {
	vcd_write_val(sim_hdl, num, DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132, 65u);
	backing.DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132 = DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154) != DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154, 65u);
	backing.DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154 = DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154;
      }
      ++num;
      if ((backing.DEF__0_CONCAT_prepareBoundsCheck_size___d162) != DEF__0_CONCAT_prepareBoundsCheck_size___d162)
      {
	vcd_write_val(sim_hdl, num, DEF__0_CONCAT_prepareBoundsCheck_size___d162, 65u);
	backing.DEF__0_CONCAT_prepareBoundsCheck_size___d162 = DEF__0_CONCAT_prepareBoundsCheck_size___d162;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50) != DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50, 65u);
	backing.DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50 = DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158) != DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156) != DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156 = DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163) != DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
      }
      ++num;
      if ((backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161) != DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161)
      {
	vcd_write_val(sim_hdl, num, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161, 65u);
	backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161;
      }
      ++num;
      if ((backing.DEF_addTop__h1261) != DEF_addTop__h1261)
      {
	vcd_write_val(sim_hdl, num, DEF_addTop__h1261, 65u);
	backing.DEF_addTop__h1261 = DEF_addTop__h1261;
      }
      ++num;
      if ((backing.DEF_addTop__h3067) != DEF_addTop__h3067)
      {
	vcd_write_val(sim_hdl, num, DEF_addTop__h3067, 65u);
	backing.DEF_addTop__h3067 = DEF_addTop__h3067;
      }
      ++num;
      if ((backing.DEF_result__h1854) != DEF_result__h1854)
      {
	vcd_write_val(sim_hdl, num, DEF_result__h1854, 65u);
	backing.DEF_result__h1854 = DEF_result__h1854;
      }
      ++num;
      if ((backing.DEF_result__h3603) != DEF_result__h3603)
      {
	vcd_write_val(sim_hdl, num, DEF_result__h3603, 65u);
	backing.DEF_result__h3603 = DEF_result__h3603;
      }
      ++num;
      if ((backing.DEF_ret__h1263) != DEF_ret__h1263)
      {
	vcd_write_val(sim_hdl, num, DEF_ret__h1263, 65u);
	backing.DEF_ret__h1263 = DEF_ret__h1263;
      }
      ++num;
      if ((backing.DEF_ret__h3069) != DEF_ret__h3069)
      {
	vcd_write_val(sim_hdl, num, DEF_ret__h3069, 65u);
	backing.DEF_ret__h3069 = DEF_ret__h3069;
      }
      ++num;
      if ((backing.DEF_x__h1249) != DEF_x__h1249)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1249, 65u);
	backing.DEF_x__h1249 = DEF_x__h1249;
      }
      ++num;
      if ((backing.DEF_x__h2870) != DEF_x__h2870)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2870, 65u);
	backing.DEF_x__h2870 = DEF_x__h2870;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck) != PORT_prepareBoundsCheck)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck, 266u);
	backing.PORT_prepareBoundsCheck = PORT_prepareBoundsCheck;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_a) != PORT_prepareBoundsCheck_a)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_a, 161u);
	backing.PORT_prepareBoundsCheck_a = PORT_prepareBoundsCheck_a;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_b) != PORT_prepareBoundsCheck_b)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_b, 161u);
	backing.PORT_prepareBoundsCheck_b = PORT_prepareBoundsCheck_b;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_ddc) != PORT_prepareBoundsCheck_ddc)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_ddc, 161u);
	backing.PORT_prepareBoundsCheck_ddc = PORT_prepareBoundsCheck_ddc;
      }
      ++num;
      if ((backing.PORT_prepareBoundsCheck_pcc) != PORT_prepareBoundsCheck_pcc)
      {
	vcd_write_val(sim_hdl, num, PORT_prepareBoundsCheck_pcc, 161u);
	backing.PORT_prepareBoundsCheck_pcc = PORT_prepareBoundsCheck_pcc;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172, 201u);
      backing.DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172 = DEF_IF_IF_prepareBoundsCheck_toCheck_BITS_20_TO_19_ETC___d172;
      vcd_write_val(sim_hdl, num++, DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152, 65u);
      backing.DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152 = DEF_IF_prepareBoundsCheck_a_BITS_43_TO_38_6_ULT_51_ETC___d152;
      vcd_write_val(sim_hdl, num++, DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164, 65u);
      backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164 = DEF_IF_prepareBoundsCheck_toCheck_BITS_15_TO_13_22_ETC___d164;
      vcd_write_val(sim_hdl, num++, DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171, 130u);
      backing.DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171 = DEF_IF_prepareBoundsCheck_toCheck_BITS_18_TO_16_02_ETC___d171;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67, 65u);
      backing.DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67 = DEF_SEXT_IF_prepareBoundsCheck_toCheck_BITS_20_TO__ETC___d67;
      vcd_write_val(sim_hdl, num++, DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132, 65u);
      backing.DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132 = DEF_SEXT_prepareBoundsCheck_a_BITS_3_TO_2_1_CONCAT_ETC___d132;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154, 65u);
      backing.DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154 = DEF__0_CONCAT_prepareBoundsCheck_a_BITS_48_TO_45_13___d154;
      vcd_write_val(sim_hdl, num++, DEF__0_CONCAT_prepareBoundsCheck_size___d162, 65u);
      backing.DEF__0_CONCAT_prepareBoundsCheck_size___d162 = DEF__0_CONCAT_prepareBoundsCheck_size___d162;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50, 65u);
      backing.DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50 = DEF__0b0_CONCAT_IF_prepareBoundsCheck_toCheck_BITS__ETC___d50;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_11_ETC___d131;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d125;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96_ETC___d159;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158 = DEF__0b0_CONCAT_prepareBoundsCheck_a_BITS_159_TO_96___d158;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156 = DEF__0b0_CONCAT_prepareBoundsCheck_b_BITS_159_TO_96___d156;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr_61_PLUS_0__ETC___d163;
      vcd_write_val(sim_hdl, num++, DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161, 65u);
      backing.DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161 = DEF__0b0_CONCAT_prepareBoundsCheck_vaddr___d161;
      vcd_write_val(sim_hdl, num++, DEF_addTop__h1261, 65u);
      backing.DEF_addTop__h1261 = DEF_addTop__h1261;
      vcd_write_val(sim_hdl, num++, DEF_addTop__h3067, 65u);
      backing.DEF_addTop__h3067 = DEF_addTop__h3067;
      vcd_write_val(sim_hdl, num++, DEF_result__h1854, 65u);
      backing.DEF_result__h1854 = DEF_result__h1854;
      vcd_write_val(sim_hdl, num++, DEF_result__h3603, 65u);
      backing.DEF_result__h3603 = DEF_result__h3603;
      vcd_write_val(sim_hdl, num++, DEF_ret__h1263, 65u);
      backing.DEF_ret__h1263 = DEF_ret__h1263;
      vcd_write_val(sim_hdl, num++, DEF_ret__h3069, 65u);
      backing.DEF_ret__h3069 = DEF_ret__h3069;
      vcd_write_val(sim_hdl, num++, DEF_x__h1249, 65u);
      backing.DEF_x__h1249 = DEF_x__h1249;
      vcd_write_val(sim_hdl, num++, DEF_x__h2870, 65u);
      backing.DEF_x__h2870 = DEF_x__h2870;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck, 266u);
      backing.PORT_prepareBoundsCheck = PORT_prepareBoundsCheck;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_a, 161u);
      backing.PORT_prepareBoundsCheck_a = PORT_prepareBoundsCheck_a;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_b, 161u);
      backing.PORT_prepareBoundsCheck_b = PORT_prepareBoundsCheck_b;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_ddc, 161u);
      backing.PORT_prepareBoundsCheck_ddc = PORT_prepareBoundsCheck_ddc;
      vcd_write_val(sim_hdl, num++, PORT_prepareBoundsCheck_pcc, 161u);
      backing.PORT_prepareBoundsCheck_pcc = PORT_prepareBoundsCheck_pcc;
    }
}
