/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Thu Jun  4 21:58:12 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_specialRWALU.h"


/* Constructor */
MOD_module_specialRWALU::MOD_module_specialRWALU(tSimStateHdl simHdl,
						 char const *name,
						 Module *parent)
  : Module(simHdl, name, parent),
    DEF_specialRWALU_oldCap_BITS_81_TO_10___d122(72u),
    DEF_specialRWALU_cap_BITS_81_TO_10___d123(72u),
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124(72u),
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125(150u)
{
  PORT_specialRWALU_cap.setSize(161u);
  PORT_specialRWALU_cap.clear();
  PORT_specialRWALU_oldCap.setSize(161u);
  PORT_specialRWALU_oldCap.clear();
  PORT_specialRWALU.setSize(161u);
  PORT_specialRWALU.clear();
  symbol_count = 3u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_specialRWALU::init_symbols_0()
{
  init_symbol(&symbols[0u], "specialRWALU", SYM_PORT, &PORT_specialRWALU, 161u);
  init_symbol(&symbols[1u], "specialRWALU_cap", SYM_PORT, &PORT_specialRWALU_cap, 161u);
  init_symbol(&symbols[2u], "specialRWALU_oldCap", SYM_PORT, &PORT_specialRWALU_oldCap, 161u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_specialRWALU::METH_specialRWALU(tUWide ARG_specialRWALU_cap,
						  tUWide ARG_specialRWALU_oldCap,
						  tUInt8 ARG_specialRWALU_scrType)
{
  tUInt8 DEF__0b0_CONCAT_specialRWALU_oldCap_BIT_4_5___d26;
  tUInt8 DEF__0b0_CONCAT_specialRWALU_cap_BIT_4_5___d76;
  tUInt64 DEF_specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34;
  tUInt64 DEF_mask__h1289;
  tUInt64 DEF_y__h1568;
  tUInt8 DEF_repBound__h3348;
  tUInt8 DEF_x__h150;
  tUInt8 DEF_x__h1296;
  tUInt8 DEF_x__h1759;
  tUInt8 DEF_x__h2188;
  tUInt8 DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d133;
  tUInt8 DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d146;
  tUInt8 DEF_NOT_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_ETC___d171;
  tUInt8 DEF_NOT_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_ETC___d182;
  tUInt8 DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129;
  tUInt8 DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131;
  tUInt8 DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144;
  tUInt8 DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130;
  tUInt8 DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169;
  tUInt8 DEF_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180;
  tUInt8 DEF_specialRWALU_oldCap_BITS_48_TO_45_7_EQ_15___d38;
  tUInt8 DEF_specialRWALU_cap_BITS_48_TO_45_1_EQ_15___d82;
  tUInt64 DEF_deltaAddrUpper__h144;
  tUInt64 DEF_deltaAddrHi__h142;
  tUInt64 DEF_deltaAddrUpper__h1290;
  tUInt64 DEF_deltaAddrHi__h1288;
  tUInt64 DEF_deltaAddrHi__h1751;
  tUInt64 DEF_deltaAddrHi__h2180;
  tUInt8 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104;
  tUInt8 DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166;
  tUInt8 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d168;
  tUInt8 DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163;
  tUInt8 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d165;
  tUInt8 DEF_repBound__h3370;
  tUInt8 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d161;
  tUInt8 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_THE_ETC___d193;
  tUInt32 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197;
  tUInt32 DEF_res_capFat_addrBits__h2809;
  tUInt64 DEF_new_csr__h77;
  tUInt64 DEF_res_capFat_address__h2808;
  tUInt64 DEF_new_csr__h1275;
  tUInt64 DEF_specialRWALU_oldCap_BITS_159_TO_96_AND_INV_spe_ETC___d12;
  tUInt64 DEF_specialRWALU_oldCap_BITS_159_TO_96_OR_specialR_ETC___d9;
  tUInt64 DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d68;
  tUInt64 DEF_new_csr__h2167;
  tUInt8 DEF_specialRWALU_cap_BIT_96___d67;
  tUInt8 DEF_specialRWALU_cap_BIT_160___d84;
  tUInt8 DEF_specialRWALU_oldCap_BIT_160___d40;
  tUInt8 DEF_specialRWALU_scrType_BITS_1_TO_0___d3;
  tUInt8 DEF_specialRWALU_scrType_BITS_4_TO_2___d1;
  tUInt8 DEF_cap_tempFields_repBoundTopBits__h2022;
  tUInt8 DEF_bb__h3368;
  tUInt8 DEF_tb__h3367;
  tUInt8 DEF_oldCap_tempFields_repBoundTopBits__h1124;
  tUInt8 DEF_bb__h3346;
  tUInt8 DEF_tb__h3345;
  tUInt8 DEF_x_BITS_13_TO_11___h1117;
  tUInt8 DEF_x_BITS_13_TO_11___h1607;
  tUInt8 DEF_x_BITS_13_TO_11___h2015;
  tUInt8 DEF_x_BITS_13_TO_11___h2251;
  tUInt8 DEF_x__h2324;
  tUInt8 DEF_x__h1680;
  tUInt32 DEF_cap_capFat_addrBits__h410;
  tUInt64 DEF_x__h170;
  tUInt32 DEF_x_BITS_13_TO_0___h2868;
  tUInt64 DEF_x__h1316;
  tUInt32 DEF_x_BITS_13_TO_0___h2869;
  tUInt64 DEF_x__h1779;
  tUInt32 DEF_x_BITS_13_TO_0___h2870;
  tUInt64 DEF_x__h2208;
  tUInt32 DEF_x_BITS_13_TO_0___h2871;
  tUInt64 DEF_x__h1682;
  tUInt64 DEF_x__h1183;
  tUInt64 DEF_x__h1652;
  tUInt64 DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15;
  tUInt64 DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d49;
  tUInt64 DEF_val__h1330;
  tUInt64 DEF_oldAddr__h23;
  PORT_specialRWALU_cap = ARG_specialRWALU_cap;
  PORT_specialRWALU_oldCap = ARG_specialRWALU_oldCap;
  wop_primExtractWide(72u,
		      161u,
		      ARG_specialRWALU_oldCap,
		      32u,
		      81u,
		      32u,
		      10u,
		      DEF_specialRWALU_oldCap_BITS_81_TO_10___d122);
  wop_primExtractWide(72u,
		      161u,
		      ARG_specialRWALU_cap,
		      32u,
		      81u,
		      32u,
		      10u,
		      DEF_specialRWALU_cap_BITS_81_TO_10___d123);
  DEF_oldAddr__h23 = primExtract64(64u, 161u, ARG_specialRWALU_oldCap, 32u, 159u, 32u, 96u);
  DEF_val__h1330 = primExtract64(64u, 161u, ARG_specialRWALU_cap, 32u, 159u, 32u, 96u);
  DEF_x__h1682 = primExtract64(50u, 161u, ARG_specialRWALU_oldCap, 32u, 159u, 32u, 110u);
  DEF_cap_capFat_addrBits__h410 = ARG_specialRWALU_cap.get_bits_in_word32(2u, 18u, 14u);
  DEF_x__h1680 = ARG_specialRWALU_oldCap.get_bits_in_word8(1u, 6u, 6u);
  DEF_x__h2324 = ARG_specialRWALU_cap.get_bits_in_word8(1u, 6u, 6u);
  DEF_tb__h3345 = ARG_specialRWALU_oldCap.get_bits_in_word8(1u, 3u, 3u);
  DEF_bb__h3346 = ARG_specialRWALU_oldCap.get_bits_in_word8(0u, 21u, 3u);
  DEF_oldCap_tempFields_repBoundTopBits__h1124 = ARG_specialRWALU_oldCap.get_bits_in_word8(0u,
											   7u,
											   3u);
  DEF_tb__h3367 = ARG_specialRWALU_cap.get_bits_in_word8(1u, 3u, 3u);
  DEF_bb__h3368 = ARG_specialRWALU_cap.get_bits_in_word8(0u, 21u, 3u);
  DEF_cap_tempFields_repBoundTopBits__h2022 = ARG_specialRWALU_cap.get_bits_in_word8(0u, 7u, 3u);
  DEF_specialRWALU_scrType_BITS_4_TO_2___d1 = (tUInt8)(ARG_specialRWALU_scrType >> 2u);
  DEF_specialRWALU_scrType_BITS_1_TO_0___d3 = (tUInt8)((tUInt8)3u & ARG_specialRWALU_scrType);
  DEF_specialRWALU_oldCap_BIT_160___d40 = ARG_specialRWALU_oldCap.get_bits_in_word8(5u, 0u, 1u);
  DEF_specialRWALU_cap_BIT_160___d84 = ARG_specialRWALU_cap.get_bits_in_word8(5u, 0u, 1u);
  DEF_specialRWALU_cap_BIT_96___d67 = ARG_specialRWALU_cap.get_bits_in_word8(3u, 0u, 1u);
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)0u:
  case (tUInt8)1u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124 = DEF_specialRWALU_oldCap_BITS_81_TO_10___d122;
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124 = DEF_specialRWALU_cap_BITS_81_TO_10___d123;
  }
  DEF_new_csr__h2167 = (primExtract64(63u,
				      161u,
				      ARG_specialRWALU_cap,
				      32u,
				      159u,
				      32u,
				      97u) << 1u) | (tUInt64)((tUInt8)0u);
  DEF_x__h2208 = primShiftR64(64u, 64u, (tUInt64)(DEF_new_csr__h2167), 6u, (tUInt8)(DEF_x__h2324));
  DEF_x_BITS_13_TO_0___h2871 = (tUInt32)(16383u & DEF_x__h2208);
  DEF_x_BITS_13_TO_11___h2251 = (tUInt8)((tUInt8)7u & (DEF_x__h2208 >> 11u));
  DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d68 = ((primExtract64(62u,
										 161u,
										 ARG_specialRWALU_cap,
										 32u,
										 159u,
										 32u,
										 98u) << 2u) | (((tUInt64)((tUInt8)0u)) << 1u)) | (tUInt64)(DEF_specialRWALU_cap_BIT_96___d67);
  DEF_x__h1779 = primShiftR64(64u,
			      64u,
			      (tUInt64)(DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d68),
			      6u,
			      (tUInt8)(DEF_x__h2324));
  DEF_x_BITS_13_TO_0___h2870 = (tUInt32)(16383u & DEF_x__h1779);
  DEF_x_BITS_13_TO_11___h2015 = (tUInt8)((tUInt8)7u & (DEF_x__h1779 >> 11u));
  DEF_specialRWALU_oldCap_BITS_159_TO_96_OR_specialR_ETC___d9 = DEF_oldAddr__h23 | DEF_val__h1330;
  DEF_repBound__h3370 = (tUInt8)7u & (DEF_bb__h3368 - (tUInt8)1u);
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)2u:
  case (tUInt8)3u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d161 = DEF_repBound__h3370;
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d161 = DEF_cap_tempFields_repBoundTopBits__h2022;
  }
  DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 = DEF_tb__h3367 < DEF_repBound__h3370;
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)2u:
  case (tUInt8)3u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d165 = DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163;
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d165 = ARG_specialRWALU_cap.get_bits_in_word8(0u,
													   6u,
													   1u);
  }
  DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 = DEF_bb__h3368 < DEF_repBound__h3370;
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)2u:
  case (tUInt8)3u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d168 = DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166;
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d168 = ARG_specialRWALU_cap.get_bits_in_word8(0u,
													   5u,
													   1u);
  }
  DEF_specialRWALU_cap_BITS_48_TO_45_1_EQ_15___d82 = ARG_specialRWALU_cap.get_bits_in_word8(1u,
											    13u,
											    4u) == (tUInt8)15u;
  DEF_specialRWALU_oldCap_BITS_48_TO_45_7_EQ_15___d38 = ARG_specialRWALU_oldCap.get_bits_in_word8(1u,
												  13u,
												  4u) == (tUInt8)15u;
  DEF_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180 = DEF_x_BITS_13_TO_11___h2251 < DEF_repBound__h3370;
  DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169 = DEF_x_BITS_13_TO_11___h2015 < DEF_repBound__h3370;
  DEF_NOT_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_ETC___d182 = !DEF_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180;
  DEF_NOT_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_ETC___d171 = !DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169;
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)2u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_THE_ETC___d193 = (tUInt8)31u & (((DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169 << 4u) | ((DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 == DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169 ? (tUInt8)0u : (DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 && DEF_NOT_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_ETC___d171 ? (tUInt8)1u : (tUInt8)3u)) << 2u)) | (DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 == DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169 ? (tUInt8)0u : (DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 && DEF_NOT_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_ETC___d171 ? (tUInt8)1u : (tUInt8)3u)));
    break;
  case (tUInt8)3u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_THE_ETC___d193 = (tUInt8)31u & (((DEF_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180 << 4u) | ((DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 == DEF_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180 ? (tUInt8)0u : (DEF_specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 && DEF_NOT_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_ETC___d182 ? (tUInt8)1u : (tUInt8)3u)) << 2u)) | (DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 == DEF_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180 ? (tUInt8)0u : (DEF_specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 && DEF_NOT_specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_ETC___d182 ? (tUInt8)1u : (tUInt8)3u)));
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_THE_ETC___d193 = ARG_specialRWALU_cap.get_bits_in_word8(0u,
													   0u,
													   5u);
  }
  DEF_repBound__h3348 = (tUInt8)7u & (DEF_bb__h3346 - (tUInt8)1u);
  DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 = DEF_bb__h3346 < DEF_repBound__h3348;
  DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 = DEF_tb__h3345 < DEF_repBound__h3348;
  DEF_y__h1568 = ~DEF_val__h1330;
  DEF_specialRWALU_oldCap_BITS_159_TO_96_AND_INV_spe_ETC___d12 = DEF_oldAddr__h23 & DEF_y__h1568;
  switch (DEF_specialRWALU_scrType_BITS_1_TO_0___d3) {
  case (tUInt8)0u:
    DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d49 = DEF_val__h1330;
    break;
  case (tUInt8)1u:
    DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d49 = DEF_specialRWALU_oldCap_BITS_159_TO_96_OR_specialR_ETC___d9;
    break;
  default:
    DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d49 = DEF_specialRWALU_oldCap_BITS_159_TO_96_AND_INV_spe_ETC___d12;
  }
  switch (DEF_specialRWALU_scrType_BITS_1_TO_0___d3) {
  case (tUInt8)0u:
    DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 = DEF_val__h1330;
    break;
  case (tUInt8)1u:
    DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 = DEF_specialRWALU_oldCap_BITS_159_TO_96_OR_specialR_ETC___d9;
    break;
  default:
    DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 = DEF_specialRWALU_oldCap_BITS_159_TO_96_AND_INV_spe_ETC___d12;
  }
  DEF_x__h1652 = (tUInt64)(DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d49 >> 14u);
  DEF_x__h1183 = (tUInt64)(DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 >> 14u);
  DEF_new_csr__h1275 = (((tUInt64)(DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d49 >> 1u)) << 1u) | (tUInt64)((tUInt8)0u);
  DEF_x__h1316 = primShiftR64(64u, 64u, (tUInt64)(DEF_new_csr__h1275), 6u, (tUInt8)(DEF_x__h1680));
  DEF_x_BITS_13_TO_0___h2869 = (tUInt32)(16383u & DEF_x__h1316);
  DEF_x_BITS_13_TO_11___h1607 = (tUInt8)((tUInt8)7u & (DEF_x__h1316 >> 11u));
  DEF_new_csr__h77 = ((((tUInt64)(DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 >> 2u)) << 2u) | (((tUInt64)((tUInt8)0u)) << 1u)) | (tUInt64)((tUInt8)((tUInt8)1u & DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15));
  DEF_x__h170 = primShiftR64(64u, 64u, (tUInt64)(DEF_new_csr__h77), 6u, (tUInt8)(DEF_x__h1680));
  DEF_x_BITS_13_TO_0___h2868 = (tUInt32)(16383u & DEF_x__h170);
  DEF_x_BITS_13_TO_11___h1117 = (tUInt8)((tUInt8)7u & (DEF_x__h170 >> 11u));
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)0u:
    DEF_res_capFat_address__h2808 = DEF_new_csr__h77;
    break;
  case (tUInt8)1u:
    DEF_res_capFat_address__h2808 = DEF_new_csr__h1275;
    break;
  case (tUInt8)2u:
    DEF_res_capFat_address__h2808 = DEF_specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d68;
    break;
  case (tUInt8)3u:
    DEF_res_capFat_address__h2808 = DEF_new_csr__h2167;
    break;
  default:
    DEF_res_capFat_address__h2808 = DEF_val__h1330;
  }
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)0u:
    DEF_res_capFat_addrBits__h2809 = DEF_x_BITS_13_TO_0___h2868;
    break;
  case (tUInt8)1u:
    DEF_res_capFat_addrBits__h2809 = DEF_x_BITS_13_TO_0___h2869;
    break;
  case (tUInt8)2u:
    DEF_res_capFat_addrBits__h2809 = DEF_x_BITS_13_TO_0___h2870;
    break;
  case (tUInt8)3u:
    DEF_res_capFat_addrBits__h2809 = DEF_x_BITS_13_TO_0___h2871;
    break;
  default:
    DEF_res_capFat_addrBits__h2809 = DEF_cap_capFat_addrBits__h410;
  }
  DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144 = DEF_x_BITS_13_TO_11___h1607 < DEF_repBound__h3348;
  DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131 = DEF_x_BITS_13_TO_11___h1117 < DEF_repBound__h3348;
  DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d146 = !DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144;
  DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d133 = !DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131;
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)0u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 = 1023u & ((((((((tUInt32)(DEF_repBound__h3348)) << 7u) | (((tUInt32)(DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129)) << 6u)) | (((tUInt32)(DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130)) << 5u)) | (((tUInt32)(DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131)) << 4u)) | (((tUInt32)(DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 == DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131 ? (tUInt8)0u : (DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 && DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d133 ? (tUInt8)1u : (tUInt8)3u))) << 2u)) | (tUInt32)(DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 == DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131 ? (tUInt8)0u : (DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 && DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d133 ? (tUInt8)1u : (tUInt8)3u)));
    break;
  case (tUInt8)1u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 = 1023u & ((((((((tUInt32)(DEF_repBound__h3348)) << 7u) | (((tUInt32)(DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129)) << 6u)) | (((tUInt32)(DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130)) << 5u)) | (((tUInt32)(DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144)) << 4u)) | (((tUInt32)(DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 == DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144 ? (tUInt8)0u : (DEF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 && DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d146 ? (tUInt8)1u : (tUInt8)3u))) << 2u)) | (tUInt32)(DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 == DEF_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144 ? (tUInt8)0u : (DEF_specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 && DEF_NOT_IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ__ETC___d146 ? (tUInt8)1u : (tUInt8)3u)));
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 = 1023u & ((((((tUInt32)(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d161)) << 7u) | (((tUInt32)(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d165)) << 6u)) | (((tUInt32)(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d168)) << 5u)) | (tUInt32)(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_THE_ETC___d193));
  }
  DEF_mask__h1289 = primShiftL64(50u, 50u, 1125899906842623llu, 6u, (tUInt8)(DEF_x__h1680));
  DEF_specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34 = DEF_x__h1682 & DEF_mask__h1289;
  DEF_deltaAddrUpper__h1290 = 1125899906842623llu & ((DEF_x__h1652 & DEF_mask__h1289) - DEF_specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34);
  DEF_deltaAddrUpper__h144 = 1125899906842623llu & ((DEF_x__h1183 & DEF_mask__h1289) - DEF_specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34);
  DEF__0b0_CONCAT_specialRWALU_cap_BIT_4_5___d76 = (tUInt8)3u & ARG_specialRWALU_cap.get_bits_in_word8(0u,
												       4u,
												       1u);
  DEF_x__h2188 = (tUInt8)3u & (((tUInt8)3u & (DEF_x_BITS_13_TO_11___h2251 < DEF_cap_tempFields_repBoundTopBits__h2022)) - DEF__0b0_CONCAT_specialRWALU_cap_BIT_4_5___d76);
  DEF_deltaAddrHi__h2180 = primShiftL64(50u,
					50u,
					(tUInt64)(primSignExt64(50u, 2u, (tUInt8)(DEF_x__h2188))),
					6u,
					(tUInt8)(DEF_x__h2324));
  DEF_x__h1759 = (tUInt8)3u & (((tUInt8)3u & (DEF_x_BITS_13_TO_11___h2015 < DEF_cap_tempFields_repBoundTopBits__h2022)) - DEF__0b0_CONCAT_specialRWALU_cap_BIT_4_5___d76);
  DEF_deltaAddrHi__h1751 = primShiftL64(50u,
					50u,
					(tUInt64)(primSignExt64(50u, 2u, (tUInt8)(DEF_x__h1759))),
					6u,
					(tUInt8)(DEF_x__h2324));
  DEF__0b0_CONCAT_specialRWALU_oldCap_BIT_4_5___d26 = (tUInt8)3u & ARG_specialRWALU_oldCap.get_bits_in_word8(0u,
													     4u,
													     1u);
  DEF_x__h1296 = (tUInt8)3u & (((tUInt8)3u & (DEF_x_BITS_13_TO_11___h1607 < DEF_oldCap_tempFields_repBoundTopBits__h1124)) - DEF__0b0_CONCAT_specialRWALU_oldCap_BIT_4_5___d26);
  DEF_deltaAddrHi__h1288 = primShiftL64(50u,
					50u,
					(tUInt64)(primSignExt64(50u, 2u, (tUInt8)(DEF_x__h1296))),
					6u,
					(tUInt8)(DEF_x__h1680));
  DEF_x__h150 = (tUInt8)3u & (((tUInt8)3u & (DEF_x_BITS_13_TO_11___h1117 < DEF_oldCap_tempFields_repBoundTopBits__h1124)) - DEF__0b0_CONCAT_specialRWALU_oldCap_BIT_4_5___d26);
  DEF_deltaAddrHi__h142 = primShiftL64(50u,
				       50u,
				       (tUInt64)(primSignExt64(50u, 2u, (tUInt8)(DEF_x__h150))),
				       6u,
				       (tUInt8)(DEF_x__h1680));
  switch (DEF_specialRWALU_scrType_BITS_4_TO_2___d1) {
  case (tUInt8)0u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 = (DEF_deltaAddrHi__h142 == DEF_deltaAddrUpper__h144 && DEF_specialRWALU_oldCap_BITS_48_TO_45_7_EQ_15___d38) && DEF_specialRWALU_oldCap_BIT_160___d40;
    break;
  case (tUInt8)1u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 = (DEF_deltaAddrHi__h1288 == DEF_deltaAddrUpper__h1290 && DEF_specialRWALU_oldCap_BITS_48_TO_45_7_EQ_15___d38) && DEF_specialRWALU_oldCap_BIT_160___d40;
    break;
  case (tUInt8)2u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 = (DEF_deltaAddrHi__h1751 == 0llu && DEF_specialRWALU_cap_BITS_48_TO_45_1_EQ_15___d82) && DEF_specialRWALU_cap_BIT_160___d84;
    break;
  case (tUInt8)3u:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 = (DEF_deltaAddrHi__h2180 == 0llu && (DEF_specialRWALU_cap_BITS_48_TO_45_1_EQ_15___d82 || !DEF_specialRWALU_cap_BIT_96___d67)) && DEF_specialRWALU_cap_BIT_160___d84;
    break;
  default:
    DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 = DEF_specialRWALU_cap_BIT_160___d84;
  }
  DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125.set_bits_in_word((tUInt32)(DEF_res_capFat_address__h2808 >> 42u),
										 4u,
										 0u,
										 22u).set_whole_word((tUInt32)(DEF_res_capFat_address__h2808 >> 10u),
												     3u).set_whole_word(((((tUInt32)(1023u & DEF_res_capFat_address__h2808)) << 22u) | (DEF_res_capFat_addrBits__h2809 << 8u)) | (tUInt32)(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124.get_bits_in_word8(2u,
																																							   0u,
																																							   8u)),
															2u).set_whole_word(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124.get_whole_word(1u),
																	   1u).set_whole_word(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124.get_whole_word(0u),
																			      0u);
  PORT_specialRWALU.build_concat(8589934591llu & ((((tUInt64)(DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104)) << 32u) | (tUInt64)(primExtract32(32u,
																				150u,
																				DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125,
																				32u,
																				149u,
																				32u,
																				118u))),
				 128u,
				 33u).set_whole_word(primExtract32(32u,
								   150u,
								   DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125,
								   32u,
								   117u,
								   32u,
								   86u),
						     3u).set_whole_word(primExtract32(32u,
										      150u,
										      DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125,
										      32u,
										      85u,
										      32u,
										      54u),
									2u).set_whole_word(primExtract32(32u,
													 150u,
													 DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125,
													 32u,
													 53u,
													 32u,
													 22u),
											   1u).set_whole_word((DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125.get_bits_in_word32(0u,
																								0u,
																								22u) << 10u) | DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197,
													      0u);
  return PORT_specialRWALU;
}

tUInt8 MOD_module_specialRWALU::METH_RDY_specialRWALU()
{
  tUInt8 PORT_RDY_specialRWALU;
  tUInt8 DEF_CAN_FIRE_specialRWALU;
  DEF_CAN_FIRE_specialRWALU = (tUInt8)1u;
  PORT_RDY_specialRWALU = DEF_CAN_FIRE_specialRWALU;
  return PORT_RDY_specialRWALU;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_specialRWALU::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_specialRWALU::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 7u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124", 72u);
  vcd_write_def(sim_hdl, num++, "IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125", 150u);
  vcd_write_def(sim_hdl, num++, "specialRWALU_cap_BITS_81_TO_10___d123", 72u);
  vcd_write_def(sim_hdl, num++, "specialRWALU_oldCap_BITS_81_TO_10___d122", 72u);
  vcd_write_def(sim_hdl, num++, "specialRWALU", 161u);
  vcd_write_def(sim_hdl, num++, "specialRWALU_cap", 161u);
  vcd_write_def(sim_hdl, num++, "specialRWALU_oldCap", 161u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_specialRWALU::dump_VCD(tVCDDumpType dt,
				       unsigned int levels,
				       MOD_module_specialRWALU &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_specialRWALU::vcd_defs(tVCDDumpType dt, MOD_module_specialRWALU &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 150u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124) != DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124, 72u);
	backing.DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124 = DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124;
      }
      ++num;
      if ((backing.DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125) != DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125, 150u);
	backing.DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125 = DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125;
      }
      ++num;
      if ((backing.DEF_specialRWALU_cap_BITS_81_TO_10___d123) != DEF_specialRWALU_cap_BITS_81_TO_10___d123)
      {
	vcd_write_val(sim_hdl, num, DEF_specialRWALU_cap_BITS_81_TO_10___d123, 72u);
	backing.DEF_specialRWALU_cap_BITS_81_TO_10___d123 = DEF_specialRWALU_cap_BITS_81_TO_10___d123;
      }
      ++num;
      if ((backing.DEF_specialRWALU_oldCap_BITS_81_TO_10___d122) != DEF_specialRWALU_oldCap_BITS_81_TO_10___d122)
      {
	vcd_write_val(sim_hdl, num, DEF_specialRWALU_oldCap_BITS_81_TO_10___d122, 72u);
	backing.DEF_specialRWALU_oldCap_BITS_81_TO_10___d122 = DEF_specialRWALU_oldCap_BITS_81_TO_10___d122;
      }
      ++num;
      if ((backing.PORT_specialRWALU) != PORT_specialRWALU)
      {
	vcd_write_val(sim_hdl, num, PORT_specialRWALU, 161u);
	backing.PORT_specialRWALU = PORT_specialRWALU;
      }
      ++num;
      if ((backing.PORT_specialRWALU_cap) != PORT_specialRWALU_cap)
      {
	vcd_write_val(sim_hdl, num, PORT_specialRWALU_cap, 161u);
	backing.PORT_specialRWALU_cap = PORT_specialRWALU_cap;
      }
      ++num;
      if ((backing.PORT_specialRWALU_oldCap) != PORT_specialRWALU_oldCap)
      {
	vcd_write_val(sim_hdl, num, PORT_specialRWALU_oldCap, 161u);
	backing.PORT_specialRWALU_oldCap = PORT_specialRWALU_oldCap;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124, 72u);
      backing.DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124 = DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_OR_sp_ETC___d124;
      vcd_write_val(sim_hdl, num++, DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125, 150u);
      backing.DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125 = DEF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125;
      vcd_write_val(sim_hdl, num++, DEF_specialRWALU_cap_BITS_81_TO_10___d123, 72u);
      backing.DEF_specialRWALU_cap_BITS_81_TO_10___d123 = DEF_specialRWALU_cap_BITS_81_TO_10___d123;
      vcd_write_val(sim_hdl, num++, DEF_specialRWALU_oldCap_BITS_81_TO_10___d122, 72u);
      backing.DEF_specialRWALU_oldCap_BITS_81_TO_10___d122 = DEF_specialRWALU_oldCap_BITS_81_TO_10___d122;
      vcd_write_val(sim_hdl, num++, PORT_specialRWALU, 161u);
      backing.PORT_specialRWALU = PORT_specialRWALU;
      vcd_write_val(sim_hdl, num++, PORT_specialRWALU_cap, 161u);
      backing.PORT_specialRWALU_cap = PORT_specialRWALU_cap;
      vcd_write_val(sim_hdl, num++, PORT_specialRWALU_oldCap, 161u);
      backing.PORT_specialRWALU_oldCap = PORT_specialRWALU_oldCap;
    }
}
