/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Thu Jun  4 21:58:12 BST 2026
 * 
 */
#include "bluesim_primitives.h"
#include "module_brAddrCalc.h"


/* Constructor */
MOD_module_brAddrCalc::MOD_module_brAddrCalc(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230(161u),
    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208(150u),
    DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166(161u),
    DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142(150u),
    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207(72u),
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141(72u)
{
  PORT_brAddrCalc_pc.setSize(161u);
  PORT_brAddrCalc_pc.clear();
  PORT_brAddrCalc_val.setSize(161u);
  PORT_brAddrCalc_val.clear();
  PORT_brAddrCalc.setSize(161u);
  PORT_brAddrCalc.clear();
  symbol_count = 3u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_module_brAddrCalc::init_symbols_0()
{
  init_symbol(&symbols[0u], "brAddrCalc", SYM_PORT, &PORT_brAddrCalc, 161u);
  init_symbol(&symbols[1u], "brAddrCalc_pc", SYM_PORT, &PORT_brAddrCalc_pc, 161u);
  init_symbol(&symbols[2u], "brAddrCalc_val", SYM_PORT, &PORT_brAddrCalc_val, 161u);
}


/* Rule actions */


/* Methods */

tUWide MOD_module_brAddrCalc::METH_brAddrCalc(tUWide ARG_brAddrCalc_pc,
					      tUWide ARG_brAddrCalc_val,
					      tUInt8 ARG_brAddrCalc_iType,
					      tUInt64 ARG_brAddrCalc_imm,
					      tUInt8 ARG_brAddrCalc_taken,
					      tUInt32 ARG_brAddrCalc_orig_inst,
					      tUInt8 ARG_brAddrCalc_cap)
{
  tUInt64 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92;
  tUInt64 DEF_x__h351;
  tUInt64 DEF_highBitsfilter__h323;
  tUInt64 DEF_addBase__h2102;
  tUInt8 DEF_repBound__h2665;
  tUInt8 DEF_repBound__h2675;
  tUInt64 DEF_signBits__h321;
  tUInt8 DEF_x__h1611;
  tUInt8 DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155;
  tUInt8 DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d217;
  tUInt8 DEF_brAddrCalc_iType_EQ_9___d4;
  tUInt8 DEF_brAddrCalc_iType_EQ_11___d6;
  tUInt8 DEF_brAddrCalc_iType_EQ_13___d8;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150;
  tUInt8 DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151;
  tUInt8 DEF_brAddrCalc_pc_BITS_37_TO_35_11_ULT_brAddrCalc__ETC___d212;
  tUInt8 DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d215;
  tUInt8 DEF_brAddrCalc_pc_BITS_23_TO_21_09_ULT_brAddrCalc__ETC___d213;
  tUInt32 DEF_repBoundBits__h330;
  tUInt64 DEF_highOffsetBits__h324;
  tUInt64 DEF_deltaAddrUpper__h1605;
  tUInt64 DEF_deltaAddrHi__h1603;
  tUInt8 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82;
  tUInt8 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74;
  tUInt8 DEF__theResult___fst_capFat_flags__h892;
  tUInt8 DEF_thin_flags__h1899;
  tUInt8 DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96;
  tUInt8 DEF__theResult___fst_capFat_tmode__h896;
  tUInt8 DEF_thin_tmode__h1902;
  tUInt8 DEF__theResult___fst_tempFields_repBoundTopBits__h1516;
  tUInt8 DEF__theResult___fst_tempFields_repBoundTopBits__h1522;
  tUInt8 DEF__theResult___fst_capFat_perms_soft__h1911;
  tUInt8 DEF__theResult___fst_capFat_perms_soft__h1913;
  tUInt8 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28;
  tUInt8 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29;
  tUInt8 DEF__theResult___fst_capFat_tloc__h895;
  tUInt8 DEF_thin_tloc__h1901;
  tUInt8 DEF__theResult___fst_capFat_mte__h894;
  tUInt8 DEF_thin_mte__h1900;
  tUInt32 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165;
  tUInt32 DEF_brAddrCalc_pc_BITS_23_TO_21_09_MINUS_0b1_10_CO_ETC___d227;
  tUInt32 DEF_inc__h126;
  tUInt32 DEF__theResult___fst_capFat_addrBits__h890;
  tUInt32 DEF__theResult___fst_capFat_addrBits__h902;
  tUInt32 DEF__theResult___fst_capFat_bounds_baseBits__h920;
  tUInt32 DEF__theResult___fst_capFat_bounds_topBits__h919;
  tUInt32 DEF_toBounds_B__h331;
  tUInt32 DEF_toBounds_A__h328;
  tUInt32 DEF_toBounds__h333;
  tUInt32 DEF_toBoundsM1_B__h332;
  tUInt32 DEF_toBoundsM1_A__h329;
  tUInt32 DEF_toBoundsM1__h334;
  tUInt32 DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101;
  tUInt32 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102;
  tUInt32 DEF_x__h2153;
  tUInt32 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117;
  tUInt32 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118;
  tUInt64 DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d137;
  tUInt64 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138;
  tUInt64 DEF_targetAddr_capFat_address__h190;
  tUInt64 DEF_offset___1__h297;
  tUInt64 DEF__theResult___snd_fst__h288;
  tUInt64 DEF__theResult___fst_capFat_address__h889;
  tUInt64 DEF_pointer__h317;
  tUInt64 DEF_ret___1_address__h1796;
  tUInt8 DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36;
  tUInt64 DEF_result_d_address__h1585;
  tUInt8 DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15;
  tUInt64 DEF_address__h127;
  tUInt8 DEF_brAddrCalc_iType_EQ_10___d167;
  tUInt8 DEF_brAddrCalc_pc_BIT_4___d80;
  tUInt8 DEF_thin_flags__h2317;
  tUInt8 DEF_brAddrCalc_pc_BIT_160___d72;
  tUInt8 DEF_val_capFat_flags__h492;
  tUInt8 DEF_x__h816;
  tUInt8 DEF_thin_tmode__h2320;
  tUInt8 DEF_val_capFat_tmode__h496;
  tUInt8 DEF_pc_tempFields_repBoundTopBits__h1510;
  tUInt8 DEF_bb__h2673;
  tUInt8 DEF_tb__h2672;
  tUInt8 DEF_val_tempFields_repBoundTopBits__h1498;
  tUInt8 DEF_bb__h2663;
  tUInt32 DEF__theResult___fst_capFat_bounds_topBits__h922;
  tUInt8 DEF_tb__h2662;
  tUInt8 DEF_x_BITS_13_TO_11___h1671;
  tUInt8 DEF_ab__h2664;
  tUInt8 DEF_ab__h2674;
  tUInt8 DEF_thin_otype__h2321;
  tUInt8 DEF_pc_capFat_perms_soft__h1909;
  tUInt8 DEF_val_capFat_perms_soft__h511;
  tUInt8 DEF_x__h2540;
  tUInt8 DEF_thin_tloc__h2319;
  tUInt8 DEF_val_capFat_tloc__h495;
  tUInt8 DEF_thin_mte__h2318;
  tUInt8 DEF_val_capFat_mte__h494;
  tUInt32 DEF__theResult___fst_capFat_bounds_baseBits__h923;
  tUInt32 DEF_x_BITS_10_TO_0___h1490;
  tUInt32 DEF_pc_capFat_bounds_baseBits__h917;
  tUInt32 DEF_pc_capFat_bounds_topBits__h916;
  tUInt32 DEF_pc_capFat_addrBits__h878;
  tUInt32 DEF_val_capFat_bounds_baseBits__h631;
  tUInt32 DEF_val_capFat_bounds_topBits__h630;
  tUInt32 DEF_val_capFat_addrBits__h490;
  tUInt64 DEF_x__h1457;
  tUInt32 DEF_offsetBits__h327;
  tUInt64 DEF_x__h2481;
  tUInt32 DEF_targetAddr_capFat_addrBits__h191;
  tUInt64 DEF_x__h2512;
  tUInt32 DEF_cap_capFat_addrBits__h207;
  tUInt32 DEF_brAddrCalc_pc_BITS_81_TO_66___d116;
  tUInt64 DEF_brAddrCalc_pc_BITS_44_TO_10___d136;
  tUInt64 DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  tUInt64 DEF_highOffsetBits__h322;
  tUInt64 DEF__theResult___fst_capFat_address__h901;
  tUInt64 DEF_x__h1762;
  tUInt64 DEF_thin_address__h1905;
  tUInt64 DEF_cap_address__h2281;
  tUInt64 DEF_cap_address__h427;
  PORT_brAddrCalc_pc = ARG_brAddrCalc_pc;
  PORT_brAddrCalc_val = ARG_brAddrCalc_val;
  DEF_cap_address__h427 = primExtract64(64u, 161u, ARG_brAddrCalc_val, 32u, 159u, 32u, 96u);
  DEF_cap_address__h2281 = primExtract64(64u, 161u, ARG_brAddrCalc_pc, 32u, 159u, 32u, 96u);
  DEF_brAddrCalc_pc_BITS_44_TO_10___d136 = primExtract64(35u,
							 161u,
							 ARG_brAddrCalc_pc,
							 32u,
							 44u,
							 32u,
							 10u);
  DEF_brAddrCalc_pc_BITS_81_TO_66___d116 = ARG_brAddrCalc_pc.get_bits_in_word32(2u, 2u, 16u);
  DEF_val_capFat_addrBits__h490 = ARG_brAddrCalc_val.get_bits_in_word32(2u, 18u, 14u);
  DEF_val_capFat_bounds_topBits__h630 = primExtract32(14u,
						      161u,
						      ARG_brAddrCalc_val,
						      32u,
						      37u,
						      32u,
						      24u);
  DEF_val_capFat_bounds_baseBits__h631 = ARG_brAddrCalc_val.get_bits_in_word32(0u, 10u, 14u);
  DEF_pc_capFat_addrBits__h878 = ARG_brAddrCalc_pc.get_bits_in_word32(2u, 18u, 14u);
  DEF_pc_capFat_bounds_topBits__h916 = primExtract32(14u,
						     161u,
						     ARG_brAddrCalc_pc,
						     32u,
						     37u,
						     32u,
						     24u);
  DEF_pc_capFat_bounds_baseBits__h917 = ARG_brAddrCalc_pc.get_bits_in_word32(0u, 10u, 14u);
  DEF_val_capFat_mte__h494 = primExtract8(8u, 161u, ARG_brAddrCalc_val, 32u, 64u, 32u, 57u);
  DEF_thin_mte__h2318 = primExtract8(8u, 161u, ARG_brAddrCalc_pc, 32u, 64u, 32u, 57u);
  DEF_val_capFat_tloc__h495 = ARG_brAddrCalc_val.get_bits_in_word8(1u, 19u, 6u);
  DEF_thin_tloc__h2319 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 19u, 6u);
  DEF_x__h2540 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 6u, 6u);
  DEF_pc_capFat_perms_soft__h1909 = ARG_brAddrCalc_pc.get_bits_in_word8(2u, 14u, 4u);
  DEF_val_capFat_perms_soft__h511 = ARG_brAddrCalc_val.get_bits_in_word8(2u, 14u, 4u);
  DEF_thin_otype__h2321 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 13u, 4u);
  DEF_val_tempFields_repBoundTopBits__h1498 = ARG_brAddrCalc_val.get_bits_in_word8(0u, 7u, 3u);
  DEF_tb__h2672 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 3u, 3u);
  DEF_brAddrCalc_pc_BIT_4___d80 = ARG_brAddrCalc_pc.get_bits_in_word8(0u, 4u, 1u);
  DEF_bb__h2673 = ARG_brAddrCalc_pc.get_bits_in_word8(0u, 21u, 3u);
  DEF_pc_tempFields_repBoundTopBits__h1510 = ARG_brAddrCalc_pc.get_bits_in_word8(0u, 7u, 3u);
  DEF_val_capFat_tmode__h496 = ARG_brAddrCalc_val.get_bits_in_word8(1u, 17u, 2u);
  DEF_thin_tmode__h2320 = ARG_brAddrCalc_pc.get_bits_in_word8(1u, 17u, 2u);
  DEF_val_capFat_flags__h492 = ARG_brAddrCalc_val.get_bits_in_word8(2u, 1u, 1u);
  DEF_brAddrCalc_pc_BIT_160___d72 = ARG_brAddrCalc_pc.get_bits_in_word8(5u, 0u, 1u);
  DEF_thin_flags__h2317 = ARG_brAddrCalc_pc.get_bits_in_word8(2u, 1u, 1u);
  DEF_brAddrCalc_iType_EQ_10___d167 = ARG_brAddrCalc_iType == (tUInt8)10u;
  DEF__theResult___fst_capFat_address__h889 = ARG_brAddrCalc_cap ? DEF_cap_address__h427 : DEF_cap_address__h2281;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_address__h901 = DEF__theResult___fst_capFat_address__h889;
    break;
  default:
    DEF__theResult___fst_capFat_address__h901 = DEF_cap_address__h2281;
  }
  DEF_x__h1762 = (tUInt64)(DEF__theResult___fst_capFat_address__h901 >> 14u);
  DEF_offset___1__h297 = DEF_cap_address__h427 + ARG_brAddrCalc_imm;
  DEF__theResult___snd_fst__h288 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_imm : DEF_offset___1__h297;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 = DEF__theResult___snd_fst__h288;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 = ARG_brAddrCalc_imm;
  }
  DEF_highOffsetBits__h322 = (tUInt64)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 >> 14u);
  DEF_x__h816 = (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 >> 63u);
  DEF_pointer__h317 = DEF__theResult___fst_capFat_address__h901 + DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d137 = ARG_brAddrCalc_cap ? primExtract64(35u,
												     161u,
												     ARG_brAddrCalc_val,
												     32u,
												     44u,
												     32u,
												     10u) : DEF_brAddrCalc_pc_BITS_44_TO_10___d136;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d137;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138 = DEF_brAddrCalc_pc_BITS_44_TO_10___d136;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word32(2u,
															     2u,
															     16u) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118 = DEF_brAddrCalc_pc_BITS_81_TO_66___d116;
  }
  DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101 = 65535u & ((((tUInt32)(ARG_brAddrCalc_pc.get_bits_in_word8(0u,
															    0u,
															    2u))) << 14u) | DEF_pc_capFat_bounds_baseBits__h917);
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102 = ARG_brAddrCalc_cap ? 65535u & ((((tUInt32)(ARG_brAddrCalc_val.get_bits_in_word8(0u,
																		  0u,
																		  2u))) << 14u) | DEF_val_capFat_bounds_baseBits__h631) : DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_x__h2153 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102;
    break;
  default:
    DEF_x__h2153 = DEF_brAddrCalc_pc_BITS_1_TO_0_00_CONCAT_brAddrCalc_ETC___d101;
  }
  DEF__theResult___fst_capFat_bounds_topBits__h919 = ARG_brAddrCalc_cap ? DEF_val_capFat_bounds_topBits__h630 : DEF_pc_capFat_bounds_topBits__h916;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_bounds_topBits__h922 = DEF__theResult___fst_capFat_bounds_topBits__h919;
    break;
  default:
    DEF__theResult___fst_capFat_bounds_topBits__h922 = DEF_pc_capFat_bounds_topBits__h916;
  }
  DEF_tb__h2662 = (tUInt8)(DEF__theResult___fst_capFat_bounds_topBits__h922 >> 11u);
  DEF__theResult___fst_capFat_bounds_baseBits__h920 = ARG_brAddrCalc_cap ? DEF_val_capFat_bounds_baseBits__h631 : DEF_pc_capFat_bounds_baseBits__h917;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_bounds_baseBits__h923 = DEF__theResult___fst_capFat_bounds_baseBits__h920;
    break;
  default:
    DEF__theResult___fst_capFat_bounds_baseBits__h923 = DEF_pc_capFat_bounds_baseBits__h917;
  }
  DEF_x_BITS_10_TO_0___h1490 = (tUInt32)(2047u & DEF__theResult___fst_capFat_bounds_baseBits__h923);
  DEF_bb__h2663 = (tUInt8)(DEF__theResult___fst_capFat_bounds_baseBits__h923 >> 11u);
  DEF_toBoundsM1_A__h329 = 16383u & ((((tUInt32)((tUInt8)6u)) << 11u) | (2047u & ~DEF_x_BITS_10_TO_0___h1490));
  DEF_toBounds_A__h328 = 16383u & (14336u - (16383u & ((((tUInt32)((tUInt8)0u)) << 11u) | DEF_x_BITS_10_TO_0___h1490)));
  DEF__theResult___fst_capFat_addrBits__h890 = ARG_brAddrCalc_cap ? DEF_val_capFat_addrBits__h490 : DEF_pc_capFat_addrBits__h878;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_addrBits__h902 = DEF__theResult___fst_capFat_addrBits__h890;
    break;
  default:
    DEF__theResult___fst_capFat_addrBits__h902 = DEF_pc_capFat_addrBits__h878;
  }
  DEF_inc__h126 = ((tUInt8)((tUInt8)3u & ARG_brAddrCalc_orig_inst)) == (tUInt8)3u ? 4u : 2u;
  DEF_address__h127 = DEF_cap_address__h2281 + primSignExt64(64u, 12u, (tUInt32)(DEF_inc__h126));
  DEF_x__h2512 = primShiftR64(64u, 64u, (tUInt64)(DEF_address__h127), 6u, (tUInt8)(DEF_x__h2540));
  DEF_cap_capFat_addrBits__h207 = (tUInt32)(16383u & DEF_x__h2512);
  DEF_ab__h2674 = (tUInt8)((tUInt8)7u & (DEF_x__h2512 >> 11u));
  DEF__theResult___fst_capFat_mte__h894 = ARG_brAddrCalc_cap ? DEF_val_capFat_mte__h494 : DEF_thin_mte__h2318;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_thin_mte__h1900 = DEF__theResult___fst_capFat_mte__h894;
    break;
  default:
    DEF_thin_mte__h1900 = DEF_thin_mte__h2318;
  }
  DEF__theResult___fst_capFat_tloc__h895 = ARG_brAddrCalc_cap ? DEF_val_capFat_tloc__h495 : DEF_thin_tloc__h2319;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_thin_tloc__h1901 = DEF__theResult___fst_capFat_tloc__h895;
    break;
  default:
    DEF_thin_tloc__h1901 = DEF_thin_tloc__h2319;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word8(1u,
															   6u,
															   6u) : DEF_x__h2540;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 = DEF_x__h2540;
  }
  DEF_x__h1457 = primShiftR64(64u,
			      64u,
			      (tUInt64)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21),
			      6u,
			      (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_offsetBits__h327 = (tUInt32)(16383u & DEF_x__h1457);
  DEF_x_BITS_13_TO_11___h1671 = (tUInt8)((tUInt8)7u & (DEF_x__h1457 >> 11u));
  DEF__theResult___fst_capFat_perms_soft__h1911 = ARG_brAddrCalc_cap ? DEF_val_capFat_perms_soft__h511 : DEF_pc_capFat_perms_soft__h1909;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_capFat_perms_soft__h1913 = DEF__theResult___fst_capFat_perms_soft__h1911;
    break;
  default:
    DEF__theResult___fst_capFat_perms_soft__h1913 = DEF_pc_capFat_perms_soft__h1909;
  }
  DEF__theResult___fst_tempFields_repBoundTopBits__h1516 = ARG_brAddrCalc_cap ? DEF_val_tempFields_repBoundTopBits__h1498 : DEF_pc_tempFields_repBoundTopBits__h1510;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF__theResult___fst_tempFields_repBoundTopBits__h1522 = DEF__theResult___fst_tempFields_repBoundTopBits__h1516;
    break;
  default:
    DEF__theResult___fst_tempFields_repBoundTopBits__h1522 = DEF_pc_tempFields_repBoundTopBits__h1510;
  }
  DEF__theResult___fst_capFat_tmode__h896 = ARG_brAddrCalc_cap ? DEF_val_capFat_tmode__h496 : DEF_thin_tmode__h2320;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_thin_tmode__h1902 = DEF__theResult___fst_capFat_tmode__h896;
    break;
  default:
    DEF_thin_tmode__h1902 = DEF_thin_tmode__h2320;
  }
  DEF__theResult___fst_capFat_flags__h892 = ARG_brAddrCalc_cap ? DEF_val_capFat_flags__h492 : DEF_thin_flags__h2317;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_thin_flags__h1899 = DEF__theResult___fst_capFat_flags__h892;
    break;
  default:
    DEF_thin_flags__h1899 = DEF_thin_flags__h2317;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word8(5u,
															   0u,
															   1u) : DEF_brAddrCalc_pc_BIT_160___d72;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 = DEF_brAddrCalc_pc_BIT_160___d72;
  }
  DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81 = ARG_brAddrCalc_cap ? ARG_brAddrCalc_val.get_bits_in_word8(0u,
															   4u,
															   1u) : DEF_brAddrCalc_pc_BIT_4___d80;
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)13u:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82 = DEF_IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81;
    break;
  default:
    DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82 = DEF_brAddrCalc_pc_BIT_4___d80;
  }
  DEF_repBoundBits__h330 = 16383u & (((tUInt32)(DEF__theResult___fst_tempFields_repBoundTopBits__h1522)) << 11u);
  DEF_toBoundsM1_B__h332 = 16383u & (DEF_repBoundBits__h330 + (16383u & ~DEF__theResult___fst_capFat_addrBits__h902));
  DEF_toBounds_B__h331 = 16383u & (DEF_repBoundBits__h330 - DEF__theResult___fst_capFat_addrBits__h902);
  DEF_brAddrCalc_iType_EQ_13___d8 = ARG_brAddrCalc_iType == (tUInt8)13u;
  DEF_brAddrCalc_iType_EQ_11___d6 = ARG_brAddrCalc_iType == (tUInt8)11u;
  DEF_brAddrCalc_iType_EQ_9___d4 = ARG_brAddrCalc_iType == (tUInt8)9u;
  DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15 = ((!DEF_brAddrCalc_iType_EQ_9___d4 && !DEF_brAddrCalc_iType_EQ_11___d6) && !DEF_brAddrCalc_iType_EQ_13___d8) || ARG_brAddrCalc_cap;
  DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 = ((DEF_brAddrCalc_iType_EQ_9___d4 || DEF_brAddrCalc_iType_EQ_11___d6) || DEF_brAddrCalc_iType_EQ_13___d8) && !ARG_brAddrCalc_cap;
  DEF_toBoundsM1__h334 = DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 ? DEF_toBoundsM1_A__h329 : DEF_toBoundsM1_B__h332;
  DEF_toBounds__h333 = DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 ? DEF_toBounds_A__h328 : DEF_toBounds_B__h331;
  DEF_highBitsfilter__h323 = primShiftL64(50u,
					  50u,
					  1125899906842623llu,
					  6u,
					  (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_x__h1611 = (tUInt8)3u & (((tUInt8)3u & (DEF_x_BITS_13_TO_11___h1671 < DEF__theResult___fst_tempFields_repBoundTopBits__h1522)) - ((tUInt8)3u & DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d82));
  DEF_deltaAddrHi__h1603 = primShiftL64(50u,
					50u,
					(tUInt64)(primSignExt64(50u, 2u, (tUInt8)(DEF_x__h1611))),
					6u,
					(tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_signBits__h321 = primSignExt64(50u, 1u, (tUInt8)(DEF_x__h816));
  DEF_repBound__h2675 = (tUInt8)7u & (DEF_bb__h2673 - (tUInt8)1u);
  DEF_brAddrCalc_pc_BITS_23_TO_21_09_ULT_brAddrCalc__ETC___d213 = DEF_bb__h2673 < DEF_repBound__h2675;
  DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d215 = DEF_ab__h2674 < DEF_repBound__h2675;
  DEF_brAddrCalc_pc_BITS_37_TO_35_11_ULT_brAddrCalc__ETC___d212 = DEF_tb__h2672 < DEF_repBound__h2675;
  DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d217 = !DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d215;
  DEF_brAddrCalc_pc_BITS_23_TO_21_09_MINUS_0b1_10_CO_ETC___d227 = 1023u & ((((((((tUInt32)(DEF_repBound__h2675)) << 7u) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_37_TO_35_11_ULT_brAddrCalc__ETC___d212)) << 6u)) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_23_TO_21_09_ULT_brAddrCalc__ETC___d213)) << 5u)) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d215)) << 4u)) | (((tUInt32)(DEF_brAddrCalc_pc_BITS_37_TO_35_11_ULT_brAddrCalc__ETC___d212 == DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d215 ? (tUInt8)0u : (DEF_brAddrCalc_pc_BITS_37_TO_35_11_ULT_brAddrCalc__ETC___d212 && DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d217 ? (tUInt8)1u : (tUInt8)3u))) << 2u)) | (tUInt32)(DEF_brAddrCalc_pc_BITS_23_TO_21_09_ULT_brAddrCalc__ETC___d213 == DEF_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d215 ? (tUInt8)0u : (DEF_brAddrCalc_pc_BITS_23_TO_21_09_ULT_brAddrCalc__ETC___d213 && DEF_NOT_brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_I_ETC___d217 ? (tUInt8)1u : (tUInt8)3u)));
  DEF_addBase__h2102 = primShiftL64(64u,
				    64u,
				    (tUInt64)(primSignExt64(64u, 16u, (tUInt32)(DEF_x__h2153))),
				    6u,
				    (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_repBound__h2665 = (tUInt8)7u & (DEF_bb__h2663 - (tUInt8)1u);
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151 = DEF_bb__h2663 < DEF_repBound__h2665;
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150 = DEF_tb__h2662 < DEF_repBound__h2665;
  DEF_x__h351 = DEF_highOffsetBits__h322 ^ DEF_signBits__h321;
  DEF_highOffsetBits__h324 = DEF_x__h351 & DEF_highBitsfilter__h323;
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92 = DEF_x__h1762 & DEF_highBitsfilter__h323;
  DEF_ret___1_address__h1796 = (((DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92 << 14u) | (tUInt64)(0u)) + DEF_addBase__h2102) + DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  DEF_result_d_address__h1585 = DEF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_EQ_1_ETC___d36 ? DEF_ret___1_address__h1796 : DEF_pointer__h317;
  DEF_thin_address__h1905 = DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15 ? DEF_result_d_address__h1585 : DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21;
  DEF_targetAddr_capFat_address__h190 = (((tUInt64)(DEF_thin_address__h1905 >> 1u)) << 1u) | (tUInt64)((tUInt8)0u);
  DEF_x__h2481 = primShiftR64(64u,
			      64u,
			      (tUInt64)(DEF_targetAddr_capFat_address__h190),
			      6u,
			      (tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29));
  DEF_targetAddr_capFat_addrBits__h191 = (tUInt32)(16383u & DEF_x__h2481);
  DEF_ab__h2664 = (tUInt8)((tUInt8)7u & (DEF_x__h2481 >> 11u));
  DEF_deltaAddrUpper__h1605 = 1125899906842623llu & ((DEF_highOffsetBits__h322 & DEF_highBitsfilter__h323) - DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92);
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 = DEF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrCalc_ETC___d15 ? ((DEF_highOffsetBits__h324 == 0llu && (DEF_x__h816 ? !(DEF_offsetBits__h327 < DEF_toBounds__h333) && !(DEF_repBoundBits__h330 == DEF__theResult___fst_capFat_addrBits__h902) : DEF_offsetBits__h327 < DEF_toBoundsM1__h334)) || !(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 < (tUInt8)50u)) && DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 : DEF_deltaAddrHi__h1603 == DEF_deltaAddrUpper__h1605 && DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74;
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153 = DEF_ab__h2664 < DEF_repBound__h2665;
  DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155 = !DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153;
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165 = 1023u & ((((((((tUInt32)(DEF_repBound__h2665)) << 7u) | (((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150)) << 6u)) | (((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151)) << 5u)) | (((tUInt32)(DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153)) << 4u)) | (((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150 == DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153 ? (tUInt8)0u : (DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d150 && DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155 ? (tUInt8)1u : (tUInt8)3u))) << 2u)) | (tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151 == DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d153 ? (tUInt8)0u : (DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d151 && DEF_NOT_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brA_ETC___d155 ? (tUInt8)1u : (tUInt8)3u)));
  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207.set_bits_in_word((tUInt8)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? 65535u & ((((tUInt32)(DEF__theResult___fst_capFat_perms_soft__h1913)) << 12u) | ARG_brAddrCalc_pc.get_bits_in_word32(2u,
																																	    2u,
																																	    12u)) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116) >> 8u),
										 2u,
										 0u,
										 8u).set_whole_word((((((((((tUInt32)((tUInt8)((tUInt8)255u & (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? 65535u & ((((tUInt32)(DEF__theResult___fst_capFat_perms_soft__h1913)) << 12u) | ARG_brAddrCalc_pc.get_bits_in_word32(2u,
																																								2u,
																																								12u)) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116) : DEF_brAddrCalc_pc_BITS_81_TO_66___d116)))) << 24u) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_thin_flags__h1899 : DEF_thin_flags__h2317) : DEF_thin_flags__h2317)) << 23u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_thin_mte__h1900 : DEF_thin_mte__h2318) : DEF_thin_mte__h2318)) << 15u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_thin_tloc__h1901 : DEF_thin_tloc__h2319) : DEF_thin_tloc__h2319)) << 9u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_thin_tmode__h1902 : DEF_thin_tmode__h2320) : DEF_thin_tmode__h2320)) << 7u)) | (((tUInt32)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? (tUInt8)15u : DEF_thin_otype__h2321) : DEF_thin_otype__h2321)) << 3u)) | (((tUInt32)(ARG_brAddrCalc_pc.get_bits_in_word8(1u,
																																																																																																																																																									     12u,
																																																																																																																																																									     1u))) << 2u)) | (tUInt32)((tUInt8)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 : DEF_x__h2540) : DEF_x__h2540) >> 4u)),
												    1u).set_whole_word((((tUInt32)((tUInt8)((tUInt8)15u & (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 : DEF_x__h2540) : DEF_x__h2540)))) << 28u) | primExtract32(28u,
																																									       161u,
																																									       ARG_brAddrCalc_pc,
																																									       32u,
																																									       37u,
																																									       32u,
																																									       10u),
														       0u);
  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208.set_bits_in_word((tUInt32)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_address__h190 : DEF_address__h127) : DEF_address__h127) >> 42u),
										 4u,
										 0u,
										 22u).set_whole_word((tUInt32)((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_address__h190 : DEF_address__h127) : DEF_address__h127) >> 10u),
												     3u).set_whole_word(((((tUInt32)(1023u & (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_address__h190 : DEF_address__h127) : DEF_address__h127))) << 22u) | ((DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_targetAddr_capFat_addrBits__h191 : DEF_cap_capFat_addrBits__h207) : DEF_cap_capFat_addrBits__h207) << 8u)) | (tUInt32)(DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207.get_bits_in_word8(2u,
																																																																					     0u,
																																																																					     8u)),
															2u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207.get_whole_word(1u),
																	   1u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207.get_whole_word(0u),
																			      0u);
  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230.build_concat(8589934591llu & ((((tUInt64)(DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 : DEF_brAddrCalc_pc_BIT_160___d72) : DEF_brAddrCalc_pc_BIT_160___d72)) << 32u) | (tUInt64)(primExtract32(32u,
																																									    150u,
																																									    DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208,
																																									    32u,
																																									    149u,
																																									    32u,
																																									    118u))),
									     128u,
									     33u).set_whole_word(primExtract32(32u,
													       150u,
													       DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208,
													       32u,
													       117u,
													       32u,
													       86u),
												 3u).set_whole_word(primExtract32(32u,
																  150u,
																  DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208,
																  32u,
																  85u,
																  32u,
																  54u),
														    2u).set_whole_word(primExtract32(32u,
																		     150u,
																		     DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208,
																		     32u,
																		     53u,
																		     32u,
																		     22u),
																       1u).set_whole_word((DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208.get_bits_in_word32(0u,
																													    0u,
																													    22u) << 10u) | (DEF_brAddrCalc_iType_EQ_10___d167 ? (ARG_brAddrCalc_taken ? DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165 : DEF_brAddrCalc_pc_BITS_23_TO_21_09_MINUS_0b1_10_CO_ETC___d227) : DEF_brAddrCalc_pc_BITS_23_TO_21_09_MINUS_0b1_10_CO_ETC___d227),
																			  0u);
  DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.set_bits_in_word((tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118 >> 8u),
										 2u,
										 0u,
										 8u).set_whole_word(((((((((tUInt32)((tUInt8)((tUInt8)255u & DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d118))) << 24u) | (((tUInt32)(DEF_thin_flags__h1899)) << 23u)) | (((tUInt32)(DEF_thin_mte__h1900)) << 15u)) | (((tUInt32)(DEF_thin_tloc__h1901)) << 9u)) | (((tUInt32)(DEF_thin_tmode__h1902)) << 7u)) | (((tUInt32)((tUInt8)15u)) << 3u)) | (tUInt32)((tUInt8)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138 >> 32u)),
												    1u).set_whole_word((tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d138),
														       0u);
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142.set_bits_in_word((tUInt32)(DEF_targetAddr_capFat_address__h190 >> 42u),
										 4u,
										 0u,
										 22u).set_whole_word((tUInt32)(DEF_targetAddr_capFat_address__h190 >> 10u),
												     3u).set_whole_word(((((tUInt32)(1023u & DEF_targetAddr_capFat_address__h190)) << 22u) | (DEF_targetAddr_capFat_addrBits__h191 << 8u)) | (tUInt32)(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.get_bits_in_word8(2u,
																																								       0u,
																																								       8u)),
															2u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.get_whole_word(1u),
																	   1u).set_whole_word(DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141.get_whole_word(0u),
																			      0u);
  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166.build_concat(8589934591llu & ((((tUInt64)(DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96)) << 32u) | (tUInt64)(primExtract32(32u,
																									   150u,
																									   DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
																									   32u,
																									   149u,
																									   32u,
																									   118u))),
									     128u,
									     33u).set_whole_word(primExtract32(32u,
													       150u,
													       DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
													       32u,
													       117u,
													       32u,
													       86u),
												 3u).set_whole_word(primExtract32(32u,
																  150u,
																  DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
																  32u,
																  85u,
																  32u,
																  54u),
														    2u).set_whole_word(primExtract32(32u,
																		     150u,
																		     DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142,
																		     32u,
																		     53u,
																		     32u,
																		     22u),
																       1u).set_whole_word((DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142.get_bits_in_word32(0u,
																													    0u,
																													    22u) << 10u) | DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d165,
																			  0u);
  switch (ARG_brAddrCalc_iType) {
  case (tUInt8)8u:
  case (tUInt8)9u:
  case (tUInt8)11u:
  case (tUInt8)12u:
  case (tUInt8)13u:
    PORT_brAddrCalc = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166;
    break;
  default:
    PORT_brAddrCalc = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230;
  }
  return PORT_brAddrCalc;
}

tUInt8 MOD_module_brAddrCalc::METH_RDY_brAddrCalc()
{
  tUInt8 PORT_RDY_brAddrCalc;
  tUInt8 DEF_CAN_FIRE_brAddrCalc;
  DEF_CAN_FIRE_brAddrCalc = (tUInt8)1u;
  PORT_RDY_brAddrCalc = DEF_CAN_FIRE_brAddrCalc;
  return PORT_RDY_brAddrCalc;
}


/* Reset routines */


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */


/* State dumping routine */
void MOD_module_brAddrCalc::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_module_brAddrCalc::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 9u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, num++, "IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142", 150u);
  vcd_write_def(sim_hdl, num++, "IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166", 161u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207", 72u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208", 150u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230", 161u);
  vcd_write_def(sim_hdl, num++, "IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141", 72u);
  vcd_write_def(sim_hdl, num++, "brAddrCalc", 161u);
  vcd_write_def(sim_hdl, num++, "brAddrCalc_pc", 161u);
  vcd_write_def(sim_hdl, num++, "brAddrCalc_val", 161u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_module_brAddrCalc::dump_VCD(tVCDDumpType dt,
				     unsigned int levels,
				     MOD_module_brAddrCalc &backing)
{
  vcd_defs(dt, backing);
}

void MOD_module_brAddrCalc::vcd_defs(tVCDDumpType dt, MOD_module_brAddrCalc &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 150u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 150u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 72u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
    vcd_write_x(sim_hdl, num++, 161u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142) != DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142, 150u);
	backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142;
      }
      ++num;
      if ((backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166) != DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166, 161u);
	backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207) != DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207, 72u);
	backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208) != DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208, 150u);
	backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230) != DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230, 161u);
	backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230;
      }
      ++num;
      if ((backing.DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141) != DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141)
      {
	vcd_write_val(sim_hdl, num, DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141, 72u);
	backing.DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141 = DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141;
      }
      ++num;
      if ((backing.PORT_brAddrCalc) != PORT_brAddrCalc)
      {
	vcd_write_val(sim_hdl, num, PORT_brAddrCalc, 161u);
	backing.PORT_brAddrCalc = PORT_brAddrCalc;
      }
      ++num;
      if ((backing.PORT_brAddrCalc_pc) != PORT_brAddrCalc_pc)
      {
	vcd_write_val(sim_hdl, num, PORT_brAddrCalc_pc, 161u);
	backing.PORT_brAddrCalc_pc = PORT_brAddrCalc_pc;
      }
      ++num;
      if ((backing.PORT_brAddrCalc_val) != PORT_brAddrCalc_val)
      {
	vcd_write_val(sim_hdl, num, PORT_brAddrCalc_val, 161u);
	backing.PORT_brAddrCalc_val = PORT_brAddrCalc_val;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142, 150u);
      backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d142;
      vcd_write_val(sim_hdl, num++, DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166, 161u);
      backing.DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166 = DEF_IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d166;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207, 72u);
      backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d207;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208, 150u);
      backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d208;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230, 161u);
      backing.DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230 = DEF_IF_brAddrCalc_iType_EQ_10_67_THEN_IF_brAddrCal_ETC___d230;
      vcd_write_val(sim_hdl, num++, DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141, 72u);
      backing.DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141 = DEF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d141;
      vcd_write_val(sim_hdl, num++, PORT_brAddrCalc, 161u);
      backing.PORT_brAddrCalc = PORT_brAddrCalc;
      vcd_write_val(sim_hdl, num++, PORT_brAddrCalc_pc, 161u);
      backing.PORT_brAddrCalc_pc = PORT_brAddrCalc_pc;
      vcd_write_val(sim_hdl, num++, PORT_brAddrCalc_val, 161u);
      backing.PORT_brAddrCalc_val = PORT_brAddrCalc_val;
    }
}
