//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:17:09 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// dmactive_cleared               O     1 reg
// RDY_dmactive_cleared           O     1 const
// RDY_reset                      O     1 const
// av_read                        O    32
// RDY_av_read                    O     1 const
// RDY_write                      O     1
// harts_reset_client_0_request_get  O     1 reg
// RDY_harts_reset_client_0_request_get  O     1 reg
// RDY_harts_reset_client_0_response_put  O     1 reg
// harts_reset_client_1_request_get  O     1 reg
// RDY_harts_reset_client_1_request_get  O     1 reg
// RDY_harts_reset_client_1_response_put  O     1 reg
// harts_client_run_halt_0_request_get  O     1 reg
// RDY_harts_client_run_halt_0_request_get  O     1 reg
// RDY_harts_client_run_halt_0_response_put  O     1 reg
// harts_client_run_halt_1_request_get  O     1 reg
// RDY_harts_client_run_halt_1_request_get  O     1 reg
// RDY_harts_client_run_halt_1_response_put  O     1 reg
// harts_get_other_req_0_get      O     4 reg
// RDY_harts_get_other_req_0_get  O     1 reg
// harts_get_other_req_1_get      O     4 reg
// RDY_harts_get_other_req_1_get  O     1 reg
// RDY_harts_is_running_0_put     O     1 const
// RDY_harts_is_running_1_put     O     1 const
// ndm_reset_client_request_get   O     1 reg
// RDY_ndm_reset_client_request_get  O     1 reg
// RDY_ndm_reset_client_response_put  O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// av_read_dm_addr                I     7
// write_dm_addr                  I     7
// write_dm_word                  I    32
// harts_reset_client_0_response_put  I     1 reg
// harts_reset_client_1_response_put  I     1 reg
// harts_client_run_halt_0_response_put  I     1 reg
// harts_client_run_halt_1_response_put  I     1 reg
// harts_is_running_0_put         I     1 reg
// harts_is_running_1_put         I     1 reg
// ndm_reset_client_response_put  I     1 reg
// EN_reset                       I     1
// EN_write                       I     1
// EN_harts_reset_client_0_response_put  I     1
// EN_harts_reset_client_1_response_put  I     1
// EN_harts_client_run_halt_0_response_put  I     1
// EN_harts_client_run_halt_1_response_put  I     1
// EN_harts_is_running_0_put      I     1
// EN_harts_is_running_1_put      I     1
// EN_ndm_reset_client_response_put  I     1
// EN_av_read                     I     1 unused
// EN_harts_reset_client_0_request_get  I     1
// EN_harts_reset_client_1_request_get  I     1
// EN_harts_client_run_halt_0_request_get  I     1
// EN_harts_client_run_halt_1_request_get  I     1
// EN_harts_get_other_req_0_get   I     1
// EN_harts_get_other_req_1_get   I     1
// EN_ndm_reset_client_request_get  I     1
//
// Combinational paths from inputs to outputs:
//   av_read_dm_addr -> av_read
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDM_Run_Control(CLK,
			RST_N,

			dmactive_cleared,
			RDY_dmactive_cleared,

			EN_reset,
			RDY_reset,

			av_read_dm_addr,
			EN_av_read,
			av_read,
			RDY_av_read,

			write_dm_addr,
			write_dm_word,
			EN_write,
			RDY_write,

			EN_harts_reset_client_0_request_get,
			harts_reset_client_0_request_get,
			RDY_harts_reset_client_0_request_get,

			harts_reset_client_0_response_put,
			EN_harts_reset_client_0_response_put,
			RDY_harts_reset_client_0_response_put,

			EN_harts_reset_client_1_request_get,
			harts_reset_client_1_request_get,
			RDY_harts_reset_client_1_request_get,

			harts_reset_client_1_response_put,
			EN_harts_reset_client_1_response_put,
			RDY_harts_reset_client_1_response_put,

			EN_harts_client_run_halt_0_request_get,
			harts_client_run_halt_0_request_get,
			RDY_harts_client_run_halt_0_request_get,

			harts_client_run_halt_0_response_put,
			EN_harts_client_run_halt_0_response_put,
			RDY_harts_client_run_halt_0_response_put,

			EN_harts_client_run_halt_1_request_get,
			harts_client_run_halt_1_request_get,
			RDY_harts_client_run_halt_1_request_get,

			harts_client_run_halt_1_response_put,
			EN_harts_client_run_halt_1_response_put,
			RDY_harts_client_run_halt_1_response_put,

			EN_harts_get_other_req_0_get,
			harts_get_other_req_0_get,
			RDY_harts_get_other_req_0_get,

			EN_harts_get_other_req_1_get,
			harts_get_other_req_1_get,
			RDY_harts_get_other_req_1_get,

			harts_is_running_0_put,
			EN_harts_is_running_0_put,
			RDY_harts_is_running_0_put,

			harts_is_running_1_put,
			EN_harts_is_running_1_put,
			RDY_harts_is_running_1_put,

			EN_ndm_reset_client_request_get,
			ndm_reset_client_request_get,
			RDY_ndm_reset_client_request_get,

			ndm_reset_client_response_put,
			EN_ndm_reset_client_response_put,
			RDY_ndm_reset_client_response_put);
  input  CLK;
  input  RST_N;

  // value method dmactive_cleared
  output dmactive_cleared;
  output RDY_dmactive_cleared;

  // action method reset
  input  EN_reset;
  output RDY_reset;

  // actionvalue method av_read
  input  [6 : 0] av_read_dm_addr;
  input  EN_av_read;
  output [31 : 0] av_read;
  output RDY_av_read;

  // action method write
  input  [6 : 0] write_dm_addr;
  input  [31 : 0] write_dm_word;
  input  EN_write;
  output RDY_write;

  // actionvalue method harts_reset_client_0_request_get
  input  EN_harts_reset_client_0_request_get;
  output harts_reset_client_0_request_get;
  output RDY_harts_reset_client_0_request_get;

  // action method harts_reset_client_0_response_put
  input  harts_reset_client_0_response_put;
  input  EN_harts_reset_client_0_response_put;
  output RDY_harts_reset_client_0_response_put;

  // actionvalue method harts_reset_client_1_request_get
  input  EN_harts_reset_client_1_request_get;
  output harts_reset_client_1_request_get;
  output RDY_harts_reset_client_1_request_get;

  // action method harts_reset_client_1_response_put
  input  harts_reset_client_1_response_put;
  input  EN_harts_reset_client_1_response_put;
  output RDY_harts_reset_client_1_response_put;

  // actionvalue method harts_client_run_halt_0_request_get
  input  EN_harts_client_run_halt_0_request_get;
  output harts_client_run_halt_0_request_get;
  output RDY_harts_client_run_halt_0_request_get;

  // action method harts_client_run_halt_0_response_put
  input  harts_client_run_halt_0_response_put;
  input  EN_harts_client_run_halt_0_response_put;
  output RDY_harts_client_run_halt_0_response_put;

  // actionvalue method harts_client_run_halt_1_request_get
  input  EN_harts_client_run_halt_1_request_get;
  output harts_client_run_halt_1_request_get;
  output RDY_harts_client_run_halt_1_request_get;

  // action method harts_client_run_halt_1_response_put
  input  harts_client_run_halt_1_response_put;
  input  EN_harts_client_run_halt_1_response_put;
  output RDY_harts_client_run_halt_1_response_put;

  // actionvalue method harts_get_other_req_0_get
  input  EN_harts_get_other_req_0_get;
  output [3 : 0] harts_get_other_req_0_get;
  output RDY_harts_get_other_req_0_get;

  // actionvalue method harts_get_other_req_1_get
  input  EN_harts_get_other_req_1_get;
  output [3 : 0] harts_get_other_req_1_get;
  output RDY_harts_get_other_req_1_get;

  // action method harts_is_running_0_put
  input  harts_is_running_0_put;
  input  EN_harts_is_running_0_put;
  output RDY_harts_is_running_0_put;

  // action method harts_is_running_1_put
  input  harts_is_running_1_put;
  input  EN_harts_is_running_1_put;
  output RDY_harts_is_running_1_put;

  // actionvalue method ndm_reset_client_request_get
  input  EN_ndm_reset_client_request_get;
  output ndm_reset_client_request_get;
  output RDY_ndm_reset_client_request_get;

  // action method ndm_reset_client_response_put
  input  ndm_reset_client_response_put;
  input  EN_ndm_reset_client_response_put;
  output RDY_ndm_reset_client_response_put;

  // signals for module outputs
  reg [31 : 0] av_read;
  wire [3 : 0] harts_get_other_req_0_get, harts_get_other_req_1_get;
  wire RDY_av_read,
       RDY_dmactive_cleared,
       RDY_harts_client_run_halt_0_request_get,
       RDY_harts_client_run_halt_0_response_put,
       RDY_harts_client_run_halt_1_request_get,
       RDY_harts_client_run_halt_1_response_put,
       RDY_harts_get_other_req_0_get,
       RDY_harts_get_other_req_1_get,
       RDY_harts_is_running_0_put,
       RDY_harts_is_running_1_put,
       RDY_harts_reset_client_0_request_get,
       RDY_harts_reset_client_0_response_put,
       RDY_harts_reset_client_1_request_get,
       RDY_harts_reset_client_1_response_put,
       RDY_ndm_reset_client_request_get,
       RDY_ndm_reset_client_response_put,
       RDY_reset,
       RDY_write,
       dmactive_cleared,
       harts_client_run_halt_0_request_get,
       harts_client_run_halt_1_request_get,
       harts_reset_client_0_request_get,
       harts_reset_client_1_request_get,
       ndm_reset_client_request_get;

  // register rg_dmactive_cleared
  reg rg_dmactive_cleared;
  wire rg_dmactive_cleared$D_IN, rg_dmactive_cleared$EN;

  // register rg_dmcontrol_dmactive
  reg rg_dmcontrol_dmactive;
  wire rg_dmcontrol_dmactive$D_IN, rg_dmcontrol_dmactive$EN;

  // register rg_dmcontrol_haltreq
  reg rg_dmcontrol_haltreq;
  wire rg_dmcontrol_haltreq$D_IN, rg_dmcontrol_haltreq$EN;

  // register rg_dmcontrol_hartreset
  reg rg_dmcontrol_hartreset;
  wire rg_dmcontrol_hartreset$D_IN, rg_dmcontrol_hartreset$EN;

  // register rg_dmcontrol_hartsel
  reg [19 : 0] rg_dmcontrol_hartsel;
  wire [19 : 0] rg_dmcontrol_hartsel$D_IN;
  wire rg_dmcontrol_hartsel$EN;

  // register rg_dmcontrol_ndmreset
  reg rg_dmcontrol_ndmreset;
  wire rg_dmcontrol_ndmreset$D_IN, rg_dmcontrol_ndmreset$EN;

  // register rg_harts_hasreset_0
  reg rg_harts_hasreset_0;
  wire rg_harts_hasreset_0$D_IN, rg_harts_hasreset_0$EN;

  // register rg_harts_hasreset_1
  reg rg_harts_hasreset_1;
  wire rg_harts_hasreset_1$D_IN, rg_harts_hasreset_1$EN;

  // register rg_harts_resumeack_0
  reg rg_harts_resumeack_0;
  reg rg_harts_resumeack_0$D_IN;
  wire rg_harts_resumeack_0$EN;

  // register rg_harts_resumeack_1
  reg rg_harts_resumeack_1;
  reg rg_harts_resumeack_1$D_IN;
  wire rg_harts_resumeack_1$EN;

  // register rg_harts_running_0
  reg rg_harts_running_0;
  wire rg_harts_running_0$D_IN, rg_harts_running_0$EN;

  // register rg_harts_running_1
  reg rg_harts_running_1;
  wire rg_harts_running_1$D_IN, rg_harts_running_1$EN;

  // register rg_ndm_reset_pending
  reg rg_ndm_reset_pending;
  wire rg_ndm_reset_pending$D_IN, rg_ndm_reset_pending$EN;

  // register rg_verbosity
  reg [3 : 0] rg_verbosity;
  wire [3 : 0] rg_verbosity$D_IN;
  wire rg_verbosity$EN;

  // ports of submodule f_harts_other_reqs_0
  wire [3 : 0] f_harts_other_reqs_0$D_IN, f_harts_other_reqs_0$D_OUT;
  wire f_harts_other_reqs_0$CLR,
       f_harts_other_reqs_0$DEQ,
       f_harts_other_reqs_0$EMPTY_N,
       f_harts_other_reqs_0$ENQ,
       f_harts_other_reqs_0$FULL_N;

  // ports of submodule f_harts_other_reqs_1
  wire [3 : 0] f_harts_other_reqs_1$D_IN, f_harts_other_reqs_1$D_OUT;
  wire f_harts_other_reqs_1$CLR,
       f_harts_other_reqs_1$DEQ,
       f_harts_other_reqs_1$EMPTY_N,
       f_harts_other_reqs_1$ENQ,
       f_harts_other_reqs_1$FULL_N;

  // ports of submodule f_harts_reset_reqs_0
  wire f_harts_reset_reqs_0$CLR,
       f_harts_reset_reqs_0$DEQ,
       f_harts_reset_reqs_0$D_IN,
       f_harts_reset_reqs_0$D_OUT,
       f_harts_reset_reqs_0$EMPTY_N,
       f_harts_reset_reqs_0$ENQ,
       f_harts_reset_reqs_0$FULL_N;

  // ports of submodule f_harts_reset_reqs_1
  wire f_harts_reset_reqs_1$CLR,
       f_harts_reset_reqs_1$DEQ,
       f_harts_reset_reqs_1$D_IN,
       f_harts_reset_reqs_1$D_OUT,
       f_harts_reset_reqs_1$EMPTY_N,
       f_harts_reset_reqs_1$ENQ,
       f_harts_reset_reqs_1$FULL_N;

  // ports of submodule f_harts_reset_rsps_0
  wire f_harts_reset_rsps_0$CLR,
       f_harts_reset_rsps_0$DEQ,
       f_harts_reset_rsps_0$D_IN,
       f_harts_reset_rsps_0$EMPTY_N,
       f_harts_reset_rsps_0$ENQ,
       f_harts_reset_rsps_0$FULL_N;

  // ports of submodule f_harts_reset_rsps_1
  wire f_harts_reset_rsps_1$CLR,
       f_harts_reset_rsps_1$DEQ,
       f_harts_reset_rsps_1$D_IN,
       f_harts_reset_rsps_1$EMPTY_N,
       f_harts_reset_rsps_1$ENQ,
       f_harts_reset_rsps_1$FULL_N;

  // ports of submodule f_harts_run_halt_reqs_0
  wire f_harts_run_halt_reqs_0$CLR,
       f_harts_run_halt_reqs_0$DEQ,
       f_harts_run_halt_reqs_0$D_IN,
       f_harts_run_halt_reqs_0$D_OUT,
       f_harts_run_halt_reqs_0$EMPTY_N,
       f_harts_run_halt_reqs_0$ENQ,
       f_harts_run_halt_reqs_0$FULL_N;

  // ports of submodule f_harts_run_halt_reqs_1
  wire f_harts_run_halt_reqs_1$CLR,
       f_harts_run_halt_reqs_1$DEQ,
       f_harts_run_halt_reqs_1$D_IN,
       f_harts_run_halt_reqs_1$D_OUT,
       f_harts_run_halt_reqs_1$EMPTY_N,
       f_harts_run_halt_reqs_1$ENQ,
       f_harts_run_halt_reqs_1$FULL_N;

  // ports of submodule f_harts_run_halt_rsps_0
  wire f_harts_run_halt_rsps_0$CLR,
       f_harts_run_halt_rsps_0$DEQ,
       f_harts_run_halt_rsps_0$D_IN,
       f_harts_run_halt_rsps_0$D_OUT,
       f_harts_run_halt_rsps_0$EMPTY_N,
       f_harts_run_halt_rsps_0$ENQ,
       f_harts_run_halt_rsps_0$FULL_N;

  // ports of submodule f_harts_run_halt_rsps_1
  wire f_harts_run_halt_rsps_1$CLR,
       f_harts_run_halt_rsps_1$DEQ,
       f_harts_run_halt_rsps_1$D_IN,
       f_harts_run_halt_rsps_1$D_OUT,
       f_harts_run_halt_rsps_1$EMPTY_N,
       f_harts_run_halt_rsps_1$ENQ,
       f_harts_run_halt_rsps_1$FULL_N;

  // ports of submodule f_ndm_reset_reqs
  wire f_ndm_reset_reqs$CLR,
       f_ndm_reset_reqs$DEQ,
       f_ndm_reset_reqs$D_IN,
       f_ndm_reset_reqs$D_OUT,
       f_ndm_reset_reqs$EMPTY_N,
       f_ndm_reset_reqs$ENQ,
       f_ndm_reset_reqs$FULL_N;

  // ports of submodule f_ndm_reset_rsps
  wire f_ndm_reset_rsps$CLR,
       f_ndm_reset_rsps$DEQ,
       f_ndm_reset_rsps$D_IN,
       f_ndm_reset_rsps$EMPTY_N,
       f_ndm_reset_rsps$ENQ,
       f_ndm_reset_rsps$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_harts_reset_rsp,
       CAN_FIRE_RL_rl_harts_reset_rsp_1,
       CAN_FIRE_RL_rl_harts_run_rsp,
       CAN_FIRE_RL_rl_harts_run_rsp_1,
       CAN_FIRE_RL_rl_ndm_reset_rsp,
       CAN_FIRE_av_read,
       CAN_FIRE_harts_client_run_halt_0_request_get,
       CAN_FIRE_harts_client_run_halt_0_response_put,
       CAN_FIRE_harts_client_run_halt_1_request_get,
       CAN_FIRE_harts_client_run_halt_1_response_put,
       CAN_FIRE_harts_get_other_req_0_get,
       CAN_FIRE_harts_get_other_req_1_get,
       CAN_FIRE_harts_is_running_0_put,
       CAN_FIRE_harts_is_running_1_put,
       CAN_FIRE_harts_reset_client_0_request_get,
       CAN_FIRE_harts_reset_client_0_response_put,
       CAN_FIRE_harts_reset_client_1_request_get,
       CAN_FIRE_harts_reset_client_1_response_put,
       CAN_FIRE_ndm_reset_client_request_get,
       CAN_FIRE_ndm_reset_client_response_put,
       CAN_FIRE_reset,
       CAN_FIRE_write,
       WILL_FIRE_RL_rl_harts_reset_rsp,
       WILL_FIRE_RL_rl_harts_reset_rsp_1,
       WILL_FIRE_RL_rl_harts_run_rsp,
       WILL_FIRE_RL_rl_harts_run_rsp_1,
       WILL_FIRE_RL_rl_ndm_reset_rsp,
       WILL_FIRE_av_read,
       WILL_FIRE_harts_client_run_halt_0_request_get,
       WILL_FIRE_harts_client_run_halt_0_response_put,
       WILL_FIRE_harts_client_run_halt_1_request_get,
       WILL_FIRE_harts_client_run_halt_1_response_put,
       WILL_FIRE_harts_get_other_req_0_get,
       WILL_FIRE_harts_get_other_req_1_get,
       WILL_FIRE_harts_is_running_0_put,
       WILL_FIRE_harts_is_running_1_put,
       WILL_FIRE_harts_reset_client_0_request_get,
       WILL_FIRE_harts_reset_client_0_response_put,
       WILL_FIRE_harts_reset_client_1_request_get,
       WILL_FIRE_harts_reset_client_1_response_put,
       WILL_FIRE_ndm_reset_client_request_get,
       WILL_FIRE_ndm_reset_client_response_put,
       WILL_FIRE_reset,
       WILL_FIRE_write;

  // inputs to muxes for submodule ports
  wire MUX_rg_dmcontrol_haltreq$write_1__SEL_2,
       MUX_rg_harts_hasreset_0$write_1__SEL_3,
       MUX_rg_harts_hasreset_1$write_1__SEL_3,
       MUX_rg_harts_resumeack_0$write_1__SEL_2,
       MUX_rg_harts_resumeack_0$write_1__SEL_3,
       MUX_rg_harts_resumeack_1$write_1__SEL_2,
       MUX_rg_harts_resumeack_1$write_1__SEL_3,
       MUX_rg_ndm_reset_pending$write_1__SEL_3;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h6102;
  reg [31 : 0] v__h6455;
  reg [31 : 0] v__h6538;
  reg [31 : 0] v__h6670;
  reg [31 : 0] v__h6865;
  reg [31 : 0] v__h6914;
  reg [31 : 0] v__h5719;
  reg [31 : 0] v__h5713;
  reg [31 : 0] v__h6096;
  reg [31 : 0] v__h6449;
  reg [31 : 0] v__h6532;
  reg [31 : 0] v__h6664;
  reg [31 : 0] v__h6859;
  reg [31 : 0] v__h6908;
  // synopsys translate_on

  // remaining internal signals
  reg CASE_hartsel442_0_rg_harts_running_0_1_rg_hart_ETC__q5,
      CASE_rg_dmcontrol_hartsel_0_NOT_rg_harts_runni_ETC__q4,
      CASE_rg_dmcontrol_hartsel_0_f_harts_other_reqs_ETC__q6,
      CASE_rg_dmcontrol_hartsel_0_rg_harts_hasreset__ETC__q1,
      CASE_rg_dmcontrol_hartsel_0_rg_harts_resumeack_ETC__q2,
      CASE_rg_dmcontrol_hartsel_0_rg_harts_running_0_ETC__q3,
      SEL_ARR_NOT_rg_harts_running_0_8_3_NOT_rg_hart_ETC___d132;
  wire [31 : 0] haltsum0__h2266,
		virt_rg_dmcontrol__h2275,
		virt_rg_dmstatus__h2274;
  wire [19 : 0] hartsel__h5442;
  wire [1 : 0] x__h5106;
  wire NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d107,
       NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d127,
       NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d138,
       NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d96,
       NOT_write_dm_word_BIT_30_22_45_OR_NOT_SEL_ARR__ETC___d150,
       f_ndm_reset_reqs_i_notFull__76_AND_f_harts_res_ETC___d184,
       rg_dmcontrol_hartsel_4_ULT_2___d24,
       write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d119,
       write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d157,
       write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d84,
       write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d101,
       write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d141,
       write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d142,
       write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d99,
       write_dm_word_BIT_0_3_AND_NOT_rg_ndm_reset_pen_ETC___d88;

  // value method dmactive_cleared
  assign dmactive_cleared = rg_dmactive_cleared ;
  assign RDY_dmactive_cleared = 1'd1 ;

  // action method reset
  assign RDY_reset = 1'd1 ;
  assign CAN_FIRE_reset = 1'd1 ;
  assign WILL_FIRE_reset = EN_reset ;

  // actionvalue method av_read
  always@(av_read_dm_addr or
	  rg_verbosity or
	  virt_rg_dmcontrol__h2275 or
	  virt_rg_dmstatus__h2274 or haltsum0__h2266)
  begin
    case (av_read_dm_addr)
      7'h10: av_read = virt_rg_dmcontrol__h2275;
      7'h11: av_read = virt_rg_dmstatus__h2274;
      7'h40: av_read = haltsum0__h2266;
      default: av_read = { 28'd0, rg_verbosity };
    endcase
  end
  assign RDY_av_read = 1'd1 ;
  assign CAN_FIRE_av_read = 1'd1 ;
  assign WILL_FIRE_av_read = EN_av_read ;

  // action method write
  assign RDY_write =
	     (rg_ndm_reset_pending ||
	      f_ndm_reset_reqs_i_notFull__76_AND_f_harts_res_ETC___d184) &&
	     CASE_rg_dmcontrol_hartsel_0_f_harts_other_reqs_ETC__q6 ;
  assign CAN_FIRE_write = RDY_write ;
  assign WILL_FIRE_write = EN_write ;

  // actionvalue method harts_reset_client_0_request_get
  assign harts_reset_client_0_request_get = f_harts_reset_reqs_0$D_OUT ;
  assign RDY_harts_reset_client_0_request_get = f_harts_reset_reqs_0$EMPTY_N ;
  assign CAN_FIRE_harts_reset_client_0_request_get =
	     f_harts_reset_reqs_0$EMPTY_N ;
  assign WILL_FIRE_harts_reset_client_0_request_get =
	     EN_harts_reset_client_0_request_get ;

  // action method harts_reset_client_0_response_put
  assign RDY_harts_reset_client_0_response_put = f_harts_reset_rsps_0$FULL_N ;
  assign CAN_FIRE_harts_reset_client_0_response_put =
	     f_harts_reset_rsps_0$FULL_N ;
  assign WILL_FIRE_harts_reset_client_0_response_put =
	     EN_harts_reset_client_0_response_put ;

  // actionvalue method harts_reset_client_1_request_get
  assign harts_reset_client_1_request_get = f_harts_reset_reqs_1$D_OUT ;
  assign RDY_harts_reset_client_1_request_get = f_harts_reset_reqs_1$EMPTY_N ;
  assign CAN_FIRE_harts_reset_client_1_request_get =
	     f_harts_reset_reqs_1$EMPTY_N ;
  assign WILL_FIRE_harts_reset_client_1_request_get =
	     EN_harts_reset_client_1_request_get ;

  // action method harts_reset_client_1_response_put
  assign RDY_harts_reset_client_1_response_put = f_harts_reset_rsps_1$FULL_N ;
  assign CAN_FIRE_harts_reset_client_1_response_put =
	     f_harts_reset_rsps_1$FULL_N ;
  assign WILL_FIRE_harts_reset_client_1_response_put =
	     EN_harts_reset_client_1_response_put ;

  // actionvalue method harts_client_run_halt_0_request_get
  assign harts_client_run_halt_0_request_get = f_harts_run_halt_reqs_0$D_OUT ;
  assign RDY_harts_client_run_halt_0_request_get =
	     f_harts_run_halt_reqs_0$EMPTY_N ;
  assign CAN_FIRE_harts_client_run_halt_0_request_get =
	     f_harts_run_halt_reqs_0$EMPTY_N ;
  assign WILL_FIRE_harts_client_run_halt_0_request_get =
	     EN_harts_client_run_halt_0_request_get ;

  // action method harts_client_run_halt_0_response_put
  assign RDY_harts_client_run_halt_0_response_put =
	     f_harts_run_halt_rsps_0$FULL_N ;
  assign CAN_FIRE_harts_client_run_halt_0_response_put =
	     f_harts_run_halt_rsps_0$FULL_N ;
  assign WILL_FIRE_harts_client_run_halt_0_response_put =
	     EN_harts_client_run_halt_0_response_put ;

  // actionvalue method harts_client_run_halt_1_request_get
  assign harts_client_run_halt_1_request_get = f_harts_run_halt_reqs_1$D_OUT ;
  assign RDY_harts_client_run_halt_1_request_get =
	     f_harts_run_halt_reqs_1$EMPTY_N ;
  assign CAN_FIRE_harts_client_run_halt_1_request_get =
	     f_harts_run_halt_reqs_1$EMPTY_N ;
  assign WILL_FIRE_harts_client_run_halt_1_request_get =
	     EN_harts_client_run_halt_1_request_get ;

  // action method harts_client_run_halt_1_response_put
  assign RDY_harts_client_run_halt_1_response_put =
	     f_harts_run_halt_rsps_1$FULL_N ;
  assign CAN_FIRE_harts_client_run_halt_1_response_put =
	     f_harts_run_halt_rsps_1$FULL_N ;
  assign WILL_FIRE_harts_client_run_halt_1_response_put =
	     EN_harts_client_run_halt_1_response_put ;

  // actionvalue method harts_get_other_req_0_get
  assign harts_get_other_req_0_get = f_harts_other_reqs_0$D_OUT ;
  assign RDY_harts_get_other_req_0_get = f_harts_other_reqs_0$EMPTY_N ;
  assign CAN_FIRE_harts_get_other_req_0_get = f_harts_other_reqs_0$EMPTY_N ;
  assign WILL_FIRE_harts_get_other_req_0_get = EN_harts_get_other_req_0_get ;

  // actionvalue method harts_get_other_req_1_get
  assign harts_get_other_req_1_get = f_harts_other_reqs_1$D_OUT ;
  assign RDY_harts_get_other_req_1_get = f_harts_other_reqs_1$EMPTY_N ;
  assign CAN_FIRE_harts_get_other_req_1_get = f_harts_other_reqs_1$EMPTY_N ;
  assign WILL_FIRE_harts_get_other_req_1_get = EN_harts_get_other_req_1_get ;

  // action method harts_is_running_0_put
  assign RDY_harts_is_running_0_put = 1'd1 ;
  assign CAN_FIRE_harts_is_running_0_put = 1'd1 ;
  assign WILL_FIRE_harts_is_running_0_put = EN_harts_is_running_0_put ;

  // action method harts_is_running_1_put
  assign RDY_harts_is_running_1_put = 1'd1 ;
  assign CAN_FIRE_harts_is_running_1_put = 1'd1 ;
  assign WILL_FIRE_harts_is_running_1_put = EN_harts_is_running_1_put ;

  // actionvalue method ndm_reset_client_request_get
  assign ndm_reset_client_request_get = f_ndm_reset_reqs$D_OUT ;
  assign RDY_ndm_reset_client_request_get = f_ndm_reset_reqs$EMPTY_N ;
  assign CAN_FIRE_ndm_reset_client_request_get = f_ndm_reset_reqs$EMPTY_N ;
  assign WILL_FIRE_ndm_reset_client_request_get =
	     EN_ndm_reset_client_request_get ;

  // action method ndm_reset_client_response_put
  assign RDY_ndm_reset_client_response_put = f_ndm_reset_rsps$FULL_N ;
  assign CAN_FIRE_ndm_reset_client_response_put = f_ndm_reset_rsps$FULL_N ;
  assign WILL_FIRE_ndm_reset_client_response_put =
	     EN_ndm_reset_client_response_put ;

  // submodule f_harts_other_reqs_0
  FIFO2 #(.width(32'd4), .guarded(1'd1)) f_harts_other_reqs_0(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(f_harts_other_reqs_0$D_IN),
							      .ENQ(f_harts_other_reqs_0$ENQ),
							      .DEQ(f_harts_other_reqs_0$DEQ),
							      .CLR(f_harts_other_reqs_0$CLR),
							      .D_OUT(f_harts_other_reqs_0$D_OUT),
							      .FULL_N(f_harts_other_reqs_0$FULL_N),
							      .EMPTY_N(f_harts_other_reqs_0$EMPTY_N));

  // submodule f_harts_other_reqs_1
  FIFO2 #(.width(32'd4), .guarded(1'd1)) f_harts_other_reqs_1(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(f_harts_other_reqs_1$D_IN),
							      .ENQ(f_harts_other_reqs_1$ENQ),
							      .DEQ(f_harts_other_reqs_1$DEQ),
							      .CLR(f_harts_other_reqs_1$CLR),
							      .D_OUT(f_harts_other_reqs_1$D_OUT),
							      .FULL_N(f_harts_other_reqs_1$FULL_N),
							      .EMPTY_N(f_harts_other_reqs_1$EMPTY_N));

  // submodule f_harts_reset_reqs_0
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_reset_reqs_0(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(f_harts_reset_reqs_0$D_IN),
							      .ENQ(f_harts_reset_reqs_0$ENQ),
							      .DEQ(f_harts_reset_reqs_0$DEQ),
							      .CLR(f_harts_reset_reqs_0$CLR),
							      .D_OUT(f_harts_reset_reqs_0$D_OUT),
							      .FULL_N(f_harts_reset_reqs_0$FULL_N),
							      .EMPTY_N(f_harts_reset_reqs_0$EMPTY_N));

  // submodule f_harts_reset_reqs_1
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_reset_reqs_1(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(f_harts_reset_reqs_1$D_IN),
							      .ENQ(f_harts_reset_reqs_1$ENQ),
							      .DEQ(f_harts_reset_reqs_1$DEQ),
							      .CLR(f_harts_reset_reqs_1$CLR),
							      .D_OUT(f_harts_reset_reqs_1$D_OUT),
							      .FULL_N(f_harts_reset_reqs_1$FULL_N),
							      .EMPTY_N(f_harts_reset_reqs_1$EMPTY_N));

  // submodule f_harts_reset_rsps_0
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_reset_rsps_0(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(f_harts_reset_rsps_0$D_IN),
							      .ENQ(f_harts_reset_rsps_0$ENQ),
							      .DEQ(f_harts_reset_rsps_0$DEQ),
							      .CLR(f_harts_reset_rsps_0$CLR),
							      .D_OUT(),
							      .FULL_N(f_harts_reset_rsps_0$FULL_N),
							      .EMPTY_N(f_harts_reset_rsps_0$EMPTY_N));

  // submodule f_harts_reset_rsps_1
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_reset_rsps_1(.RST(RST_N),
							      .CLK(CLK),
							      .D_IN(f_harts_reset_rsps_1$D_IN),
							      .ENQ(f_harts_reset_rsps_1$ENQ),
							      .DEQ(f_harts_reset_rsps_1$DEQ),
							      .CLR(f_harts_reset_rsps_1$CLR),
							      .D_OUT(),
							      .FULL_N(f_harts_reset_rsps_1$FULL_N),
							      .EMPTY_N(f_harts_reset_rsps_1$EMPTY_N));

  // submodule f_harts_run_halt_reqs_0
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_run_halt_reqs_0(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(f_harts_run_halt_reqs_0$D_IN),
								 .ENQ(f_harts_run_halt_reqs_0$ENQ),
								 .DEQ(f_harts_run_halt_reqs_0$DEQ),
								 .CLR(f_harts_run_halt_reqs_0$CLR),
								 .D_OUT(f_harts_run_halt_reqs_0$D_OUT),
								 .FULL_N(f_harts_run_halt_reqs_0$FULL_N),
								 .EMPTY_N(f_harts_run_halt_reqs_0$EMPTY_N));

  // submodule f_harts_run_halt_reqs_1
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_run_halt_reqs_1(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(f_harts_run_halt_reqs_1$D_IN),
								 .ENQ(f_harts_run_halt_reqs_1$ENQ),
								 .DEQ(f_harts_run_halt_reqs_1$DEQ),
								 .CLR(f_harts_run_halt_reqs_1$CLR),
								 .D_OUT(f_harts_run_halt_reqs_1$D_OUT),
								 .FULL_N(f_harts_run_halt_reqs_1$FULL_N),
								 .EMPTY_N(f_harts_run_halt_reqs_1$EMPTY_N));

  // submodule f_harts_run_halt_rsps_0
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_run_halt_rsps_0(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(f_harts_run_halt_rsps_0$D_IN),
								 .ENQ(f_harts_run_halt_rsps_0$ENQ),
								 .DEQ(f_harts_run_halt_rsps_0$DEQ),
								 .CLR(f_harts_run_halt_rsps_0$CLR),
								 .D_OUT(f_harts_run_halt_rsps_0$D_OUT),
								 .FULL_N(f_harts_run_halt_rsps_0$FULL_N),
								 .EMPTY_N(f_harts_run_halt_rsps_0$EMPTY_N));

  // submodule f_harts_run_halt_rsps_1
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_harts_run_halt_rsps_1(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(f_harts_run_halt_rsps_1$D_IN),
								 .ENQ(f_harts_run_halt_rsps_1$ENQ),
								 .DEQ(f_harts_run_halt_rsps_1$DEQ),
								 .CLR(f_harts_run_halt_rsps_1$CLR),
								 .D_OUT(f_harts_run_halt_rsps_1$D_OUT),
								 .FULL_N(f_harts_run_halt_rsps_1$FULL_N),
								 .EMPTY_N(f_harts_run_halt_rsps_1$EMPTY_N));

  // submodule f_ndm_reset_reqs
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_ndm_reset_reqs(.RST(RST_N),
							  .CLK(CLK),
							  .D_IN(f_ndm_reset_reqs$D_IN),
							  .ENQ(f_ndm_reset_reqs$ENQ),
							  .DEQ(f_ndm_reset_reqs$DEQ),
							  .CLR(f_ndm_reset_reqs$CLR),
							  .D_OUT(f_ndm_reset_reqs$D_OUT),
							  .FULL_N(f_ndm_reset_reqs$FULL_N),
							  .EMPTY_N(f_ndm_reset_reqs$EMPTY_N));

  // submodule f_ndm_reset_rsps
  FIFO2 #(.width(32'd1), .guarded(1'd1)) f_ndm_reset_rsps(.RST(RST_N),
							  .CLK(CLK),
							  .D_IN(f_ndm_reset_rsps$D_IN),
							  .ENQ(f_ndm_reset_rsps$ENQ),
							  .DEQ(f_ndm_reset_rsps$DEQ),
							  .CLR(f_ndm_reset_rsps$CLR),
							  .D_OUT(),
							  .FULL_N(f_ndm_reset_rsps$FULL_N),
							  .EMPTY_N(f_ndm_reset_rsps$EMPTY_N));

  // rule RL_rl_harts_reset_rsp
  assign CAN_FIRE_RL_rl_harts_reset_rsp = f_harts_reset_rsps_0$EMPTY_N ;
  assign WILL_FIRE_RL_rl_harts_reset_rsp = f_harts_reset_rsps_0$EMPTY_N ;

  // rule RL_rl_harts_reset_rsp_1
  assign CAN_FIRE_RL_rl_harts_reset_rsp_1 = f_harts_reset_rsps_1$EMPTY_N ;
  assign WILL_FIRE_RL_rl_harts_reset_rsp_1 = f_harts_reset_rsps_1$EMPTY_N ;

  // rule RL_rl_ndm_reset_rsp
  assign CAN_FIRE_RL_rl_ndm_reset_rsp = f_ndm_reset_rsps$EMPTY_N ;
  assign WILL_FIRE_RL_rl_ndm_reset_rsp = f_ndm_reset_rsps$EMPTY_N ;

  // rule RL_rl_harts_run_rsp
  assign CAN_FIRE_RL_rl_harts_run_rsp =
	     f_harts_run_halt_rsps_0$EMPTY_N && !f_ndm_reset_rsps$EMPTY_N ;
  assign WILL_FIRE_RL_rl_harts_run_rsp = CAN_FIRE_RL_rl_harts_run_rsp ;

  // rule RL_rl_harts_run_rsp_1
  assign CAN_FIRE_RL_rl_harts_run_rsp_1 =
	     f_harts_run_halt_rsps_1$EMPTY_N && !f_ndm_reset_rsps$EMPTY_N ;
  assign WILL_FIRE_RL_rl_harts_run_rsp_1 = CAN_FIRE_RL_rl_harts_run_rsp_1 ;

  // inputs to muxes for submodule ports
  assign MUX_rg_dmcontrol_haltreq$write_1__SEL_2 =
	     EN_write && write_dm_addr == 7'h10 ;
  assign MUX_rg_harts_hasreset_0$write_1__SEL_3 =
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d99 ;
  assign MUX_rg_harts_hasreset_1$write_1__SEL_3 =
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d101 ;
  assign MUX_rg_harts_resumeack_0$write_1__SEL_2 =
	     WILL_FIRE_RL_rl_harts_run_rsp && f_harts_run_halt_rsps_0$D_OUT ;
  assign MUX_rg_harts_resumeack_0$write_1__SEL_3 =
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d141 ;
  assign MUX_rg_harts_resumeack_1$write_1__SEL_2 =
	     WILL_FIRE_RL_rl_harts_run_rsp_1 &&
	     f_harts_run_halt_rsps_1$D_OUT ;
  assign MUX_rg_harts_resumeack_1$write_1__SEL_3 =
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d142 ;
  assign MUX_rg_ndm_reset_pending$write_1__SEL_3 =
	     EN_write &&
	     write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d84 ;

  // register rg_dmactive_cleared
  assign rg_dmactive_cleared$D_IN = !EN_reset ;
  assign rg_dmactive_cleared$EN =
	     EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] ||
	     EN_reset ;

  // register rg_dmcontrol_dmactive
  assign rg_dmcontrol_dmactive$D_IN = !EN_reset ;
  assign rg_dmcontrol_dmactive$EN =
	     EN_write && write_dm_addr == 7'h10 && write_dm_word[0] ||
	     EN_reset ;

  // register rg_dmcontrol_haltreq
  assign rg_dmcontrol_haltreq$D_IN = !EN_reset && write_dm_word[31] ;
  assign rg_dmcontrol_haltreq$EN =
	     EN_write && write_dm_addr == 7'h10 || EN_reset ;

  // register rg_dmcontrol_hartreset
  assign rg_dmcontrol_hartreset$D_IN = !EN_reset && write_dm_word[29] ;
  assign rg_dmcontrol_hartreset$EN =
	     EN_write && write_dm_addr == 7'h10 || EN_reset ;

  // register rg_dmcontrol_hartsel
  assign rg_dmcontrol_hartsel$D_IN = hartsel__h5442 ;
  assign rg_dmcontrol_hartsel$EN = MUX_rg_dmcontrol_haltreq$write_1__SEL_2 ;

  // register rg_dmcontrol_ndmreset
  assign rg_dmcontrol_ndmreset$D_IN = !EN_reset && write_dm_word[1] ;
  assign rg_dmcontrol_ndmreset$EN =
	     EN_write && write_dm_addr == 7'h10 || EN_reset ;

  // register rg_harts_hasreset_0
  assign rg_harts_hasreset_0$D_IN =
	     !EN_reset && !f_harts_reset_rsps_0$EMPTY_N ;
  assign rg_harts_hasreset_0$EN =
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d99 ||
	     f_harts_reset_rsps_0$EMPTY_N ||
	     EN_reset ;

  // register rg_harts_hasreset_1
  assign rg_harts_hasreset_1$D_IN =
	     !EN_reset && !f_harts_reset_rsps_1$EMPTY_N ;
  assign rg_harts_hasreset_1$EN =
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d101 ||
	     f_harts_reset_rsps_1$EMPTY_N ||
	     EN_reset ;

  // register rg_harts_resumeack_0
  always@(EN_reset or
	  MUX_rg_harts_resumeack_0$write_1__SEL_2 or
	  MUX_rg_harts_resumeack_0$write_1__SEL_3)
  case (1'b1)
    EN_reset: rg_harts_resumeack_0$D_IN = 1'd0;
    MUX_rg_harts_resumeack_0$write_1__SEL_2: rg_harts_resumeack_0$D_IN = 1'd1;
    MUX_rg_harts_resumeack_0$write_1__SEL_3: rg_harts_resumeack_0$D_IN = 1'd0;
    default: rg_harts_resumeack_0$D_IN = 1'bx /* unspecified value */ ;
  endcase
  assign rg_harts_resumeack_0$EN =
	     WILL_FIRE_RL_rl_harts_run_rsp && f_harts_run_halt_rsps_0$D_OUT ||
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d141 ||
	     EN_reset ;

  // register rg_harts_resumeack_1
  always@(EN_reset or
	  MUX_rg_harts_resumeack_1$write_1__SEL_2 or
	  MUX_rg_harts_resumeack_1$write_1__SEL_3)
  case (1'b1)
    EN_reset: rg_harts_resumeack_1$D_IN = 1'd0;
    MUX_rg_harts_resumeack_1$write_1__SEL_2: rg_harts_resumeack_1$D_IN = 1'd1;
    MUX_rg_harts_resumeack_1$write_1__SEL_3: rg_harts_resumeack_1$D_IN = 1'd0;
    default: rg_harts_resumeack_1$D_IN = 1'bx /* unspecified value */ ;
  endcase
  assign rg_harts_resumeack_1$EN =
	     WILL_FIRE_RL_rl_harts_run_rsp_1 &&
	     f_harts_run_halt_rsps_1$D_OUT ||
	     EN_write &&
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d142 ||
	     EN_reset ;

  // register rg_harts_running_0
  assign rg_harts_running_0$D_IN = harts_is_running_0_put ;
  assign rg_harts_running_0$EN = EN_harts_is_running_0_put ;

  // register rg_harts_running_1
  assign rg_harts_running_1$D_IN = harts_is_running_1_put ;
  assign rg_harts_running_1$EN = EN_harts_is_running_1_put ;

  // register rg_ndm_reset_pending
  assign rg_ndm_reset_pending$D_IN = !EN_reset && !f_ndm_reset_rsps$EMPTY_N ;
  assign rg_ndm_reset_pending$EN =
	     EN_write &&
	     write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d84 ||
	     f_ndm_reset_rsps$EMPTY_N ||
	     EN_reset ;

  // register rg_verbosity
  assign rg_verbosity$D_IN = EN_reset ? 4'd0 : write_dm_word[3:0] ;
  assign rg_verbosity$EN = EN_write && write_dm_addr == 7'h60 || EN_reset ;

  // submodule f_harts_other_reqs_0
  assign f_harts_other_reqs_0$D_IN = write_dm_word[3:0] ;
  assign f_harts_other_reqs_0$ENQ =
	     EN_write && rg_dmcontrol_hartsel == 20'd0 &&
	     write_dm_addr == 7'h60 ;
  assign f_harts_other_reqs_0$DEQ = EN_harts_get_other_req_0_get ;
  assign f_harts_other_reqs_0$CLR = 1'b0 ;

  // submodule f_harts_other_reqs_1
  assign f_harts_other_reqs_1$D_IN = write_dm_word[3:0] ;
  assign f_harts_other_reqs_1$ENQ =
	     EN_write && rg_dmcontrol_hartsel == 20'd1 &&
	     write_dm_addr == 7'h60 ;
  assign f_harts_other_reqs_1$DEQ = EN_harts_get_other_req_1_get ;
  assign f_harts_other_reqs_1$CLR = 1'b0 ;

  // submodule f_harts_reset_reqs_0
  assign f_harts_reset_reqs_0$D_IN = !write_dm_word[31] ;
  assign f_harts_reset_reqs_0$ENQ = MUX_rg_harts_hasreset_0$write_1__SEL_3 ;
  assign f_harts_reset_reqs_0$DEQ = EN_harts_reset_client_0_request_get ;
  assign f_harts_reset_reqs_0$CLR = EN_reset ;

  // submodule f_harts_reset_reqs_1
  assign f_harts_reset_reqs_1$D_IN = !write_dm_word[31] ;
  assign f_harts_reset_reqs_1$ENQ = MUX_rg_harts_hasreset_1$write_1__SEL_3 ;
  assign f_harts_reset_reqs_1$DEQ = EN_harts_reset_client_1_request_get ;
  assign f_harts_reset_reqs_1$CLR = EN_reset ;

  // submodule f_harts_reset_rsps_0
  assign f_harts_reset_rsps_0$D_IN = harts_reset_client_0_response_put ;
  assign f_harts_reset_rsps_0$ENQ = EN_harts_reset_client_0_response_put ;
  assign f_harts_reset_rsps_0$DEQ = f_harts_reset_rsps_0$EMPTY_N ;
  assign f_harts_reset_rsps_0$CLR = EN_reset ;

  // submodule f_harts_reset_rsps_1
  assign f_harts_reset_rsps_1$D_IN = harts_reset_client_1_response_put ;
  assign f_harts_reset_rsps_1$ENQ = EN_harts_reset_client_1_response_put ;
  assign f_harts_reset_rsps_1$DEQ = f_harts_reset_rsps_1$EMPTY_N ;
  assign f_harts_reset_rsps_1$CLR = EN_reset ;

  // submodule f_harts_run_halt_reqs_0
  assign f_harts_run_halt_reqs_0$D_IN =
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d141 ;
  assign f_harts_run_halt_reqs_0$ENQ =
	     EN_write &&
	     (write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d141 ||
	      hartsel__h5442 == 20'd0 &&
	      write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d157) ;
  assign f_harts_run_halt_reqs_0$DEQ =
	     EN_harts_client_run_halt_0_request_get ;
  assign f_harts_run_halt_reqs_0$CLR = EN_reset ;

  // submodule f_harts_run_halt_reqs_1
  assign f_harts_run_halt_reqs_1$D_IN =
	     write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d142 ;
  assign f_harts_run_halt_reqs_1$ENQ =
	     EN_write &&
	     (write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d142 ||
	      hartsel__h5442 == 20'd1 &&
	      write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d157) ;
  assign f_harts_run_halt_reqs_1$DEQ =
	     EN_harts_client_run_halt_1_request_get ;
  assign f_harts_run_halt_reqs_1$CLR = EN_reset ;

  // submodule f_harts_run_halt_rsps_0
  assign f_harts_run_halt_rsps_0$D_IN = harts_client_run_halt_0_response_put ;
  assign f_harts_run_halt_rsps_0$ENQ =
	     EN_harts_client_run_halt_0_response_put ;
  assign f_harts_run_halt_rsps_0$DEQ = CAN_FIRE_RL_rl_harts_run_rsp ;
  assign f_harts_run_halt_rsps_0$CLR = EN_reset ;

  // submodule f_harts_run_halt_rsps_1
  assign f_harts_run_halt_rsps_1$D_IN = harts_client_run_halt_1_response_put ;
  assign f_harts_run_halt_rsps_1$ENQ =
	     EN_harts_client_run_halt_1_response_put ;
  assign f_harts_run_halt_rsps_1$DEQ = CAN_FIRE_RL_rl_harts_run_rsp_1 ;
  assign f_harts_run_halt_rsps_1$CLR = EN_reset ;

  // submodule f_ndm_reset_reqs
  assign f_ndm_reset_reqs$D_IN = !write_dm_word[31] ;
  assign f_ndm_reset_reqs$ENQ = MUX_rg_ndm_reset_pending$write_1__SEL_3 ;
  assign f_ndm_reset_reqs$DEQ = EN_ndm_reset_client_request_get ;
  assign f_ndm_reset_reqs$CLR = EN_reset ;

  // submodule f_ndm_reset_rsps
  assign f_ndm_reset_rsps$D_IN = ndm_reset_client_response_put ;
  assign f_ndm_reset_rsps$ENQ = EN_ndm_reset_client_response_put ;
  assign f_ndm_reset_rsps$DEQ = f_ndm_reset_rsps$EMPTY_N ;
  assign f_ndm_reset_rsps$CLR = EN_reset ;

  // remaining internal signals
  assign NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d107 =
	     !rg_ndm_reset_pending &&
	     (rg_dmcontrol_ndmreset || !write_dm_word[1]) &&
	     (!rg_dmcontrol_ndmreset || write_dm_word[1]) &&
	     !write_dm_word[29] &&
	     write_dm_word[26] ;
  assign NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d127 =
	     !rg_ndm_reset_pending &&
	     (rg_dmcontrol_ndmreset || !write_dm_word[1]) &&
	     (!rg_dmcontrol_ndmreset || write_dm_word[1]) &&
	     !write_dm_word[29] &&
	     write_dm_word[31] &&
	     write_dm_word[30] ;
  assign NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d138 =
	     !rg_ndm_reset_pending &&
	     (rg_dmcontrol_ndmreset || !write_dm_word[1]) &&
	     (!rg_dmcontrol_ndmreset || write_dm_word[1]) &&
	     !write_dm_word[29] &&
	     !write_dm_word[31] &&
	     write_dm_word[30] &&
	     SEL_ARR_NOT_rg_harts_running_0_8_3_NOT_rg_hart_ETC___d132 ;
  assign NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d96 =
	     !rg_ndm_reset_pending &&
	     (rg_dmcontrol_ndmreset || !write_dm_word[1]) &&
	     (!rg_dmcontrol_ndmreset || write_dm_word[1]) &&
	     write_dm_word[29] ;
  assign NOT_write_dm_word_BIT_30_22_45_OR_NOT_SEL_ARR__ETC___d150 =
	     (!write_dm_word[30] ||
	      !SEL_ARR_NOT_rg_harts_running_0_8_3_NOT_rg_hart_ETC___d132) &&
	     write_dm_word[31] &&
	     CASE_hartsel442_0_rg_harts_running_0_1_rg_hart_ETC__q5 ;
  assign f_ndm_reset_reqs_i_notFull__76_AND_f_harts_res_ETC___d184 =
	     f_ndm_reset_reqs$FULL_N && f_harts_reset_reqs_0$FULL_N &&
	     f_harts_reset_reqs_1$FULL_N &&
	     f_harts_run_halt_reqs_1$FULL_N &&
	     f_harts_run_halt_reqs_0$FULL_N ;
  assign haltsum0__h2266 = { 30'd0, x__h5106 } ;
  assign hartsel__h5442 = { write_dm_word[15:6], write_dm_word[25:16] } ;
  assign rg_dmcontrol_hartsel_4_ULT_2___d24 = rg_dmcontrol_hartsel < 20'd2 ;
  assign virt_rg_dmcontrol__h2275 =
	     { 2'b0,
	       rg_dmcontrol_hartreset,
	       3'd0,
	       rg_dmcontrol_hartsel[9:0],
	       rg_dmcontrol_hartsel[19:10],
	       4'd0,
	       rg_dmcontrol_ndmreset,
	       rg_dmcontrol_dmactive } ;
  assign virt_rg_dmstatus__h2274 =
	     { 12'd0,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_rg_harts_hasreset__ETC__q1,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_rg_harts_hasreset__ETC__q1,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_rg_harts_resumeack_ETC__q2,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_rg_harts_resumeack_ETC__q2,
	       !rg_dmcontrol_hartsel_4_ULT_2___d24,
	       !rg_dmcontrol_hartsel_4_ULT_2___d24,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 && rg_ndm_reset_pending,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 && rg_ndm_reset_pending,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_rg_harts_running_0_ETC__q3,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_rg_harts_running_0_ETC__q3,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_NOT_rg_harts_runni_ETC__q4,
	       rg_dmcontrol_hartsel_4_ULT_2___d24 &&
	       CASE_rg_dmcontrol_hartsel_0_NOT_rg_harts_runni_ETC__q4,
	       8'd130 } ;
  assign write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d119 =
	     write_dm_addr == 7'h10 && write_dm_word[0] &&
	     !rg_ndm_reset_pending &&
	     (rg_dmcontrol_ndmreset || !write_dm_word[1]) &&
	     (!rg_dmcontrol_ndmreset || write_dm_word[1]) &&
	     !write_dm_word[29] &&
	     hartsel__h5442 >= 20'd2 ;
  assign write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d157 =
	     write_dm_addr == 7'h10 && write_dm_word[0] &&
	     !rg_ndm_reset_pending &&
	     (rg_dmcontrol_ndmreset || !write_dm_word[1]) &&
	     (!rg_dmcontrol_ndmreset || write_dm_word[1]) &&
	     !write_dm_word[29] &&
	     !write_dm_word[30] &&
	     NOT_write_dm_word_BIT_30_22_45_OR_NOT_SEL_ARR__ETC___d150 ;
  assign write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d84 =
	     write_dm_addr == 7'h10 && write_dm_word[0] &&
	     !rg_ndm_reset_pending &&
	     rg_dmcontrol_ndmreset &&
	     !write_dm_word[1] ;
  assign write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d101 =
	     hartsel__h5442 == 20'd1 && write_dm_addr == 7'h10 &&
	     write_dm_word[0] &&
	     NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d96 ;
  assign write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d141 =
	     hartsel__h5442 == 20'd0 && write_dm_addr == 7'h10 &&
	     write_dm_word[0] &&
	     NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d138 ;
  assign write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d142 =
	     hartsel__h5442 == 20'd1 && write_dm_addr == 7'h10 &&
	     write_dm_word[0] &&
	     NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d138 ;
  assign write_dm_word_BITS_15_TO_6_0_CONCAT_write_dm_w_ETC___d99 =
	     hartsel__h5442 == 20'd0 && write_dm_addr == 7'h10 &&
	     write_dm_word[0] &&
	     NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d96 ;
  assign write_dm_word_BIT_0_3_AND_NOT_rg_ndm_reset_pen_ETC___d88 =
	     write_dm_word[0] && !rg_ndm_reset_pending &&
	     rg_dmcontrol_ndmreset &&
	     !write_dm_word[1] &&
	     write_dm_word[29] ;
  assign x__h5106 = { ~rg_harts_running_1, ~rg_harts_running_0 } ;
  always@(rg_dmcontrol_hartsel or rg_harts_hasreset_0 or rg_harts_hasreset_1)
  begin
    case (rg_dmcontrol_hartsel)
      20'd0:
	  CASE_rg_dmcontrol_hartsel_0_rg_harts_hasreset__ETC__q1 =
	      rg_harts_hasreset_0;
      20'd1:
	  CASE_rg_dmcontrol_hartsel_0_rg_harts_hasreset__ETC__q1 =
	      rg_harts_hasreset_1;
      default: CASE_rg_dmcontrol_hartsel_0_rg_harts_hasreset__ETC__q1 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(rg_dmcontrol_hartsel or
	  rg_harts_resumeack_0 or rg_harts_resumeack_1)
  begin
    case (rg_dmcontrol_hartsel)
      20'd0:
	  CASE_rg_dmcontrol_hartsel_0_rg_harts_resumeack_ETC__q2 =
	      rg_harts_resumeack_0;
      20'd1:
	  CASE_rg_dmcontrol_hartsel_0_rg_harts_resumeack_ETC__q2 =
	      rg_harts_resumeack_1;
      default: CASE_rg_dmcontrol_hartsel_0_rg_harts_resumeack_ETC__q2 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(rg_dmcontrol_hartsel or rg_harts_running_0 or rg_harts_running_1)
  begin
    case (rg_dmcontrol_hartsel)
      20'd0:
	  CASE_rg_dmcontrol_hartsel_0_rg_harts_running_0_ETC__q3 =
	      rg_harts_running_0;
      20'd1:
	  CASE_rg_dmcontrol_hartsel_0_rg_harts_running_0_ETC__q3 =
	      rg_harts_running_1;
      default: CASE_rg_dmcontrol_hartsel_0_rg_harts_running_0_ETC__q3 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(rg_dmcontrol_hartsel or rg_harts_running_0 or rg_harts_running_1)
  begin
    case (rg_dmcontrol_hartsel)
      20'd0:
	  CASE_rg_dmcontrol_hartsel_0_NOT_rg_harts_runni_ETC__q4 =
	      !rg_harts_running_0;
      20'd1:
	  CASE_rg_dmcontrol_hartsel_0_NOT_rg_harts_runni_ETC__q4 =
	      !rg_harts_running_1;
      default: CASE_rg_dmcontrol_hartsel_0_NOT_rg_harts_runni_ETC__q4 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(hartsel__h5442 or rg_harts_running_0 or rg_harts_running_1)
  begin
    case (hartsel__h5442)
      20'd0:
	  SEL_ARR_NOT_rg_harts_running_0_8_3_NOT_rg_hart_ETC___d132 =
	      !rg_harts_running_0;
      20'd1:
	  SEL_ARR_NOT_rg_harts_running_0_8_3_NOT_rg_hart_ETC___d132 =
	      !rg_harts_running_1;
      default: SEL_ARR_NOT_rg_harts_running_0_8_3_NOT_rg_hart_ETC___d132 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(hartsel__h5442 or rg_harts_running_0 or rg_harts_running_1)
  begin
    case (hartsel__h5442)
      20'd0:
	  CASE_hartsel442_0_rg_harts_running_0_1_rg_hart_ETC__q5 =
	      rg_harts_running_0;
      20'd1:
	  CASE_hartsel442_0_rg_harts_running_0_1_rg_hart_ETC__q5 =
	      rg_harts_running_1;
      default: CASE_hartsel442_0_rg_harts_running_0_1_rg_hart_ETC__q5 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(rg_dmcontrol_hartsel or
	  f_harts_other_reqs_0$FULL_N or f_harts_other_reqs_1$FULL_N)
  begin
    case (rg_dmcontrol_hartsel)
      20'd0:
	  CASE_rg_dmcontrol_hartsel_0_f_harts_other_reqs_ETC__q6 =
	      f_harts_other_reqs_0$FULL_N;
      20'd1:
	  CASE_rg_dmcontrol_hartsel_0_f_harts_other_reqs_ETC__q6 =
	      f_harts_other_reqs_1$FULL_N;
      default: CASE_rg_dmcontrol_hartsel_0_f_harts_other_reqs_ETC__q6 = 1'd1;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_dmactive_cleared <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_dmcontrol_dmactive <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_dmcontrol_hartsel <= `BSV_ASSIGNMENT_DELAY 20'd0;
	rg_ndm_reset_pending <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (rg_dmactive_cleared$EN)
	  rg_dmactive_cleared <= `BSV_ASSIGNMENT_DELAY
	      rg_dmactive_cleared$D_IN;
	if (rg_dmcontrol_dmactive$EN)
	  rg_dmcontrol_dmactive <= `BSV_ASSIGNMENT_DELAY
	      rg_dmcontrol_dmactive$D_IN;
	if (rg_dmcontrol_hartsel$EN)
	  rg_dmcontrol_hartsel <= `BSV_ASSIGNMENT_DELAY
	      rg_dmcontrol_hartsel$D_IN;
	if (rg_ndm_reset_pending$EN)
	  rg_ndm_reset_pending <= `BSV_ASSIGNMENT_DELAY
	      rg_ndm_reset_pending$D_IN;
      end
    if (rg_dmcontrol_haltreq$EN)
      rg_dmcontrol_haltreq <= `BSV_ASSIGNMENT_DELAY rg_dmcontrol_haltreq$D_IN;
    if (rg_dmcontrol_hartreset$EN)
      rg_dmcontrol_hartreset <= `BSV_ASSIGNMENT_DELAY
	  rg_dmcontrol_hartreset$D_IN;
    if (rg_dmcontrol_ndmreset$EN)
      rg_dmcontrol_ndmreset <= `BSV_ASSIGNMENT_DELAY
	  rg_dmcontrol_ndmreset$D_IN;
    if (rg_harts_hasreset_0$EN)
      rg_harts_hasreset_0 <= `BSV_ASSIGNMENT_DELAY rg_harts_hasreset_0$D_IN;
    if (rg_harts_hasreset_1$EN)
      rg_harts_hasreset_1 <= `BSV_ASSIGNMENT_DELAY rg_harts_hasreset_1$D_IN;
    if (rg_harts_resumeack_0$EN)
      rg_harts_resumeack_0 <= `BSV_ASSIGNMENT_DELAY rg_harts_resumeack_0$D_IN;
    if (rg_harts_resumeack_1$EN)
      rg_harts_resumeack_1 <= `BSV_ASSIGNMENT_DELAY rg_harts_resumeack_1$D_IN;
    if (rg_harts_running_0$EN)
      rg_harts_running_0 <= `BSV_ASSIGNMENT_DELAY rg_harts_running_0$D_IN;
    if (rg_harts_running_1$EN)
      rg_harts_running_1 <= `BSV_ASSIGNMENT_DELAY rg_harts_running_1$D_IN;
    if (rg_verbosity$EN)
      rg_verbosity <= `BSV_ASSIGNMENT_DELAY rg_verbosity$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_dmactive_cleared = 1'h0;
    rg_dmcontrol_dmactive = 1'h0;
    rg_dmcontrol_haltreq = 1'h0;
    rg_dmcontrol_hartreset = 1'h0;
    rg_dmcontrol_hartsel = 20'hAAAAA;
    rg_dmcontrol_ndmreset = 1'h0;
    rg_harts_hasreset_0 = 1'h0;
    rg_harts_hasreset_1 = 1'h0;
    rg_harts_resumeack_0 = 1'h0;
    rg_harts_resumeack_1 = 1'h0;
    rg_harts_running_0 = 1'h0;
    rg_harts_running_1 = 1'h0;
    rg_ndm_reset_pending = 1'h0;
    rg_verbosity = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  rg_ndm_reset_pending)
	begin
	  v__h6102 = $stime;
	  #0;
	end
    v__h6096 = v__h6102 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  rg_ndm_reset_pending)
	$display("%0d: %m.dmcontrol_write 0x%0h: ndm reset in progress; ignoring this write",
		 v__h6096,
		 write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 &&
	  write_dm_word_BIT_0_3_AND_NOT_rg_ndm_reset_pen_ETC___d88)
	$display("    WARNING: %m.dmcontrol_write 0x%08h:", write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 &&
	  write_dm_word_BIT_0_3_AND_NOT_rg_ndm_reset_pen_ETC___d88)
	$display("    Both ndmreset [1] and hartreset [29] are asserted");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 &&
	  write_dm_word_BIT_0_3_AND_NOT_rg_ndm_reset_pen_ETC___d88)
	$display("    ndmreset has priority; ignoring hartreset");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d107)
	begin
	  v__h6455 = $stime;
	  #0;
	end
    v__h6449 = v__h6455 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d107)
	$display("%0d:ERROR: %m.dmcontrol_write 0x%08h: hasel is not supported",
		 v__h6449,
		 write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write &&
	  write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d119)
	begin
	  v__h6538 = $stime;
	  #0;
	end
    v__h6532 = v__h6538 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write &&
	  write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d119)
	$display("%0d:WARNING: %m.dmcontrol_write 0x%08h: hartsel 0x%0h refers to non-existent hart",
		 v__h6532,
		 write_dm_word,
		 hartsel__h5442);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d127)
	begin
	  v__h6670 = $stime;
	  #0;
	end
    v__h6664 = v__h6670 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d127)
	$display("%0d:ERROR: %m.dmcontrol_write 0x%08h: haltreq=1 and resumereq=1",
		 v__h6664,
		 write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d127)
	$display("    This behavior is 'undefined' in the spec; ignoring");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d138)
	begin
	  v__h6865 = $stime;
	  #0;
	end
    v__h6859 = v__h6865 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && write_dm_word[0] &&
	  NOT_rg_ndm_reset_pending_read__6_9_AND_rg_dmco_ETC___d138)
	$display("%0d: %m.dmcontrol_write: hart %0d resume request",
		 v__h6859,
		 hartsel__h5442);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write &&
	  write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d157)
	begin
	  v__h6914 = $stime;
	  #0;
	end
    v__h6908 = v__h6914 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write &&
	  write_dm_addr_EQ_0x10_6_AND_write_dm_word_BIT__ETC___d157)
	$display("%0d: %m.dmcontrol_write: hart %0d halt request",
		 v__h6908,
		 hartsel__h5442);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0])
	begin
	  v__h5719 = $stime;
	  #0;
	end
    v__h5713 = v__h5719 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0])
	$display("%0d: %m.dmcontrol_write 0x%08h (dmactive=0): resetting Debug Module",
		 v__h5713,
		 write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] &&
	  write_dm_word[1])
	$display("    WARNING: DM_Run_Control: dmcontrol_write 0x%08h:",
		 write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] &&
	  write_dm_word[1])
	$display("    [1] (ndmreset) and [0] (dmactive) both asserted");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] &&
	  write_dm_word[1])
	$display("    dmactive has priority; ignoring ndmreset");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] &&
	  write_dm_word[29])
	$display("    WARNING: DM_Run_Control: dmcontrol_write 0x%08h:",
		 write_dm_word);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] &&
	  write_dm_word[29])
	$display("    [29] (hartreset) and [0] (dmactive) both asserted");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_write && write_dm_addr == 7'h10 && !write_dm_word[0] &&
	  write_dm_word[29])
	$display("    dmactive has priority; ignoring hartreset");
  end
  // synopsys translate_on
endmodule  // mkDM_Run_Control

