//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:19:53 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_enq                        O     1
// notFull                        O     1
// RDY_notFull                    O     1 const
// RDY_deq                        O     1
// first                          O   190
// RDY_first                      O     1
// notEmpty                       O     1
// RDY_notEmpty                   O     1 const
// RDY_specUpdate_incorrectSpeculation  O     1 const
// RDY_specUpdate_correctSpeculation  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// enq_x                          I   190
// specUpdate_incorrectSpeculation_kill_all  I     1
// specUpdate_incorrectSpeculation_kill_tag  I     4
// specUpdate_correctSpeculation_mask  I    12
// EN_enq                         I     1
// EN_deq                         I     1
// EN_specUpdate_incorrectSpeculation  I     1
// EN_specUpdate_correctSpeculation  I     1
//
// Combinational paths from inputs to outputs:
//   EN_specUpdate_incorrectSpeculation -> RDY_enq
//   EN_specUpdate_incorrectSpeculation -> RDY_deq
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkLSQIssueLdQ(CLK,
		     RST_N,

		     enq_x,
		     EN_enq,
		     RDY_enq,

		     notFull,
		     RDY_notFull,

		     EN_deq,
		     RDY_deq,

		     first,
		     RDY_first,

		     notEmpty,
		     RDY_notEmpty,

		     specUpdate_incorrectSpeculation_kill_all,
		     specUpdate_incorrectSpeculation_kill_tag,
		     EN_specUpdate_incorrectSpeculation,
		     RDY_specUpdate_incorrectSpeculation,

		     specUpdate_correctSpeculation_mask,
		     EN_specUpdate_correctSpeculation,
		     RDY_specUpdate_correctSpeculation);
  input  CLK;
  input  RST_N;

  // action method enq
  input  [189 : 0] enq_x;
  input  EN_enq;
  output RDY_enq;

  // value method notFull
  output notFull;
  output RDY_notFull;

  // action method deq
  input  EN_deq;
  output RDY_deq;

  // value method first
  output [189 : 0] first;
  output RDY_first;

  // value method notEmpty
  output notEmpty;
  output RDY_notEmpty;

  // action method specUpdate_incorrectSpeculation
  input  specUpdate_incorrectSpeculation_kill_all;
  input  [3 : 0] specUpdate_incorrectSpeculation_kill_tag;
  input  EN_specUpdate_incorrectSpeculation;
  output RDY_specUpdate_incorrectSpeculation;

  // action method specUpdate_correctSpeculation
  input  [11 : 0] specUpdate_correctSpeculation_mask;
  input  EN_specUpdate_correctSpeculation;
  output RDY_specUpdate_correctSpeculation;

  // signals for module outputs
  reg notEmpty;
  wire [189 : 0] first;
  wire RDY_deq,
       RDY_enq,
       RDY_first,
       RDY_notEmpty,
       RDY_notFull,
       RDY_specUpdate_correctSpeculation,
       RDY_specUpdate_incorrectSpeculation,
       notFull;

  // inlined wires
  reg m_m_valid_for_enq_wire$wget;
  wire m_m_deqP_ehr_lat_0$whas,
       m_m_empty_for_enq_wire$wget,
       m_m_valid_0_lat_0$whas,
       m_m_valid_0_lat_1$whas,
       m_m_valid_1_lat_0$whas,
       m_m_valid_1_lat_1$whas;

  // register m_m_deqP_ehr_rl
  reg m_m_deqP_ehr_rl;
  wire m_m_deqP_ehr_rl$D_IN, m_m_deqP_ehr_rl$EN;

  // register m_m_enqP
  reg m_m_enqP;
  wire m_m_enqP$D_IN, m_m_enqP$EN;

  // register m_m_row_0
  reg [177 : 0] m_m_row_0;
  wire [177 : 0] m_m_row_0$D_IN;
  wire m_m_row_0$EN;

  // register m_m_row_1
  reg [177 : 0] m_m_row_1;
  wire [177 : 0] m_m_row_1$D_IN;
  wire m_m_row_1$EN;

  // register m_m_specBits_0_rl
  reg [11 : 0] m_m_specBits_0_rl;
  wire [11 : 0] m_m_specBits_0_rl$D_IN;
  wire m_m_specBits_0_rl$EN;

  // register m_m_specBits_1_rl
  reg [11 : 0] m_m_specBits_1_rl;
  wire [11 : 0] m_m_specBits_1_rl$D_IN;
  wire m_m_specBits_1_rl$EN;

  // register m_m_valid_0_rl
  reg m_m_valid_0_rl;
  wire m_m_valid_0_rl$D_IN, m_m_valid_0_rl$EN;

  // register m_m_valid_1_rl
  reg m_m_valid_1_rl;
  wire m_m_valid_1_rl$D_IN, m_m_valid_1_rl$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_m_m_canon_deqP,
       CAN_FIRE_RL_m_m_deqP_ehr_canon,
       CAN_FIRE_RL_m_m_setWireForEnq,
       CAN_FIRE_RL_m_m_specBits_0_canon,
       CAN_FIRE_RL_m_m_specBits_1_canon,
       CAN_FIRE_RL_m_m_valid_0_canon,
       CAN_FIRE_RL_m_m_valid_1_canon,
       CAN_FIRE_deq,
       CAN_FIRE_enq,
       CAN_FIRE_specUpdate_correctSpeculation,
       CAN_FIRE_specUpdate_incorrectSpeculation,
       WILL_FIRE_RL_m_m_canon_deqP,
       WILL_FIRE_RL_m_m_deqP_ehr_canon,
       WILL_FIRE_RL_m_m_setWireForEnq,
       WILL_FIRE_RL_m_m_specBits_0_canon,
       WILL_FIRE_RL_m_m_specBits_1_canon,
       WILL_FIRE_RL_m_m_valid_0_canon,
       WILL_FIRE_RL_m_m_valid_1_canon,
       WILL_FIRE_deq,
       WILL_FIRE_enq,
       WILL_FIRE_specUpdate_correctSpeculation,
       WILL_FIRE_specUpdate_incorrectSpeculation;

  // inputs to muxes for submodule ports
  wire MUX_m_m_valid_0_lat_0$wset_1__SEL_2,
       MUX_m_m_valid_1_lat_0$wset_1__SEL_2;

  // remaining internal signals
  reg [63 : 0] CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_172_TO_1_ETC__q24,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_90_TO_27_ETC__q20;
  reg [15 : 0] CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_26_TO_11_ETC__q21;
  reg [11 : 0] CASE_m_m_deqP_ehr_rl_0_m_m_specBits_0_rl_1_m_m_ETC__q26;
  reg [7 : 0] CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_10_TO_3__ETC__q22;
  reg [4 : 0] CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_177_TO_1_ETC__q25;
  reg [2 : 0] CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_2_TO_0_1_ETC__q23;
  reg CASE_m_m_deqP_ehr_rl_0_NOT_m_m_valid_0_rl_1_NO_ETC__q1,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_100_1_m_m_ETC__q9,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_101_1_m_m_ETC__q8,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_102_1_m_m_ETC__q7,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_103_1_m_m_ETC__q6,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_104_1_m_m_ETC__q5,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_105_1_m_m_ETC__q4,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_106_1_m_m_ETC__q3,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_107_1_m_m_ETC__q2,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_108_1_m_m_ETC__q17,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_91_1_m_m__ETC__q19,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_92_1_m_m__ETC__q18,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_93_1_m_m__ETC__q16,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_94_1_m_m__ETC__q15,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_95_1_m_m__ETC__q14,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_96_1_m_m__ETC__q13,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_97_1_m_m__ETC__q12,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_98_1_m_m__ETC__q11,
      CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_99_1_m_m__ETC__q10;
  wire [172 : 0] SEL_ARR_m_m_row_0_1_BITS_172_TO_109_7_m_m_row__ETC___d191;
  wire [91 : 0] SEL_ARR_m_m_row_0_1_BIT_91_67_m_m_row_1_3_BIT__ETC___d190;
  wire [16 : 0] SEL_ARR_m_m_row_0_1_BIT_108_1_m_m_row_1_3_BIT__ETC___d166;
  wire [14 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d161;
  wire [12 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d152;
  wire [11 : 0] IF_m_m_specBits_0_lat_0_whas__8_THEN_IF_m_m_sp_ETC___d22,
		IF_m_m_specBits_1_lat_0_whas__7_THEN_IF_m_m_sp_ETC___d31,
		upd__h1586,
		upd__h1924;
  wire [10 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d143;
  wire [8 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d134;
  wire [6 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d125;
  wire [4 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d116;
  wire [2 : 0] SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d107;
  wire SEL_ARR_NOT_m_m_valid_0_rl_2_NOT_m_m_valid_1_r_ETC___d51, upd__h2448;

  // action method enq
  assign RDY_enq =
	     (m_m_empty_for_enq_wire$wget || m_m_enqP != m_m_deqP_ehr_rl) &&
	     !EN_specUpdate_incorrectSpeculation ;
  assign CAN_FIRE_enq = RDY_enq ;
  assign WILL_FIRE_enq = EN_enq ;

  // value method notFull
  assign notFull =
	     m_m_empty_for_enq_wire$wget || m_m_enqP != m_m_deqP_ehr_rl ;
  assign RDY_notFull = 1'd1 ;

  // action method deq
  assign RDY_deq = notEmpty && !EN_specUpdate_incorrectSpeculation ;
  assign CAN_FIRE_deq = notEmpty && !EN_specUpdate_incorrectSpeculation ;
  assign WILL_FIRE_deq = EN_deq ;

  // value method first
  assign first =
	     { CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_177_TO_1_ETC__q25,
	       SEL_ARR_m_m_row_0_1_BITS_172_TO_109_7_m_m_row__ETC___d191,
	       CASE_m_m_deqP_ehr_rl_0_m_m_specBits_0_rl_1_m_m_ETC__q26 } ;
  assign RDY_first = notEmpty ;

  // value method notEmpty
  always@(m_m_deqP_ehr_rl or m_m_valid_0_rl or m_m_valid_1_rl)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0: notEmpty = m_m_valid_0_rl;
      1'd1: notEmpty = m_m_valid_1_rl;
    endcase
  end
  assign RDY_notEmpty = 1'd1 ;

  // action method specUpdate_incorrectSpeculation
  assign RDY_specUpdate_incorrectSpeculation = 1'd1 ;
  assign CAN_FIRE_specUpdate_incorrectSpeculation = 1'd1 ;
  assign WILL_FIRE_specUpdate_incorrectSpeculation =
	     EN_specUpdate_incorrectSpeculation ;

  // action method specUpdate_correctSpeculation
  assign RDY_specUpdate_correctSpeculation = 1'd1 ;
  assign CAN_FIRE_specUpdate_correctSpeculation = 1'd1 ;
  assign WILL_FIRE_specUpdate_correctSpeculation =
	     EN_specUpdate_correctSpeculation ;

  // rule RL_m_m_canon_deqP
  assign CAN_FIRE_RL_m_m_canon_deqP =
	     SEL_ARR_NOT_m_m_valid_0_rl_2_NOT_m_m_valid_1_r_ETC___d51 &&
	     !EN_specUpdate_incorrectSpeculation ;
  assign WILL_FIRE_RL_m_m_canon_deqP = CAN_FIRE_RL_m_m_canon_deqP ;

  // rule RL_m_m_setWireForEnq
  assign CAN_FIRE_RL_m_m_setWireForEnq = 1'd1 ;
  assign WILL_FIRE_RL_m_m_setWireForEnq = 1'd1 ;

  // rule RL_m_m_valid_0_canon
  assign CAN_FIRE_RL_m_m_valid_0_canon = 1'd1 ;
  assign WILL_FIRE_RL_m_m_valid_0_canon = 1'd1 ;

  // rule RL_m_m_valid_1_canon
  assign CAN_FIRE_RL_m_m_valid_1_canon = 1'd1 ;
  assign WILL_FIRE_RL_m_m_valid_1_canon = 1'd1 ;

  // rule RL_m_m_specBits_0_canon
  assign CAN_FIRE_RL_m_m_specBits_0_canon = 1'd1 ;
  assign WILL_FIRE_RL_m_m_specBits_0_canon = 1'd1 ;

  // rule RL_m_m_specBits_1_canon
  assign CAN_FIRE_RL_m_m_specBits_1_canon = 1'd1 ;
  assign WILL_FIRE_RL_m_m_specBits_1_canon = 1'd1 ;

  // rule RL_m_m_deqP_ehr_canon
  assign CAN_FIRE_RL_m_m_deqP_ehr_canon = 1'd1 ;
  assign WILL_FIRE_RL_m_m_deqP_ehr_canon = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_m_m_valid_0_lat_0$wset_1__SEL_2 =
	     EN_specUpdate_incorrectSpeculation &&
	     (specUpdate_incorrectSpeculation_kill_all ||
	      m_m_specBits_0_rl[specUpdate_incorrectSpeculation_kill_tag]) ;
  assign MUX_m_m_valid_1_lat_0$wset_1__SEL_2 =
	     EN_specUpdate_incorrectSpeculation &&
	     (specUpdate_incorrectSpeculation_kill_all ||
	      m_m_specBits_1_rl[specUpdate_incorrectSpeculation_kill_tag]) ;

  // inlined wires
  assign m_m_valid_0_lat_0$whas =
	     EN_deq && m_m_deqP_ehr_rl == 1'd0 ||
	     MUX_m_m_valid_0_lat_0$wset_1__SEL_2 ;
  assign m_m_valid_0_lat_1$whas = EN_enq && m_m_enqP == 1'd0 ;
  assign m_m_valid_1_lat_0$whas =
	     EN_deq && m_m_deqP_ehr_rl == 1'd1 ||
	     MUX_m_m_valid_1_lat_0$wset_1__SEL_2 ;
  assign m_m_valid_1_lat_1$whas = EN_enq && m_m_enqP == 1'd1 ;
  assign m_m_deqP_ehr_lat_0$whas = WILL_FIRE_RL_m_m_canon_deqP || EN_deq ;
  assign m_m_empty_for_enq_wire$wget = !m_m_valid_0_rl && !m_m_valid_1_rl ;
  always@(m_m_enqP or m_m_valid_0_rl or m_m_valid_1_rl)
  begin
    case (m_m_enqP)
      1'd0: m_m_valid_for_enq_wire$wget = m_m_valid_0_rl;
      1'd1: m_m_valid_for_enq_wire$wget = m_m_valid_1_rl;
    endcase
  end

  // register m_m_deqP_ehr_rl
  assign m_m_deqP_ehr_rl$D_IN =
	     m_m_deqP_ehr_lat_0$whas ? upd__h2448 : m_m_deqP_ehr_rl ;
  assign m_m_deqP_ehr_rl$EN = 1'd1 ;

  // register m_m_enqP
  assign m_m_enqP$D_IN = m_m_enqP + 1'd1 ;
  assign m_m_enqP$EN = EN_enq ;

  // register m_m_row_0
  assign m_m_row_0$D_IN = enq_x[189:12] ;
  assign m_m_row_0$EN = m_m_valid_0_lat_1$whas ;

  // register m_m_row_1
  assign m_m_row_1$D_IN = enq_x[189:12] ;
  assign m_m_row_1$EN = m_m_valid_1_lat_1$whas ;

  // register m_m_specBits_0_rl
  assign m_m_specBits_0_rl$D_IN =
	     EN_specUpdate_correctSpeculation ?
	       upd__h1586 :
	       IF_m_m_specBits_0_lat_0_whas__8_THEN_IF_m_m_sp_ETC___d22 ;
  assign m_m_specBits_0_rl$EN = 1'd1 ;

  // register m_m_specBits_1_rl
  assign m_m_specBits_1_rl$D_IN =
	     EN_specUpdate_correctSpeculation ?
	       upd__h1924 :
	       IF_m_m_specBits_1_lat_0_whas__7_THEN_IF_m_m_sp_ETC___d31 ;
  assign m_m_specBits_1_rl$EN = 1'd1 ;

  // register m_m_valid_0_rl
  assign m_m_valid_0_rl$D_IN =
	     m_m_valid_0_lat_1$whas ||
	     (m_m_valid_0_lat_0$whas ? 1'd0 : m_m_valid_0_rl) ;
  assign m_m_valid_0_rl$EN = 1'd1 ;

  // register m_m_valid_1_rl
  assign m_m_valid_1_rl$D_IN =
	     m_m_valid_1_lat_1$whas ||
	     (m_m_valid_1_lat_0$whas ? 1'd0 : m_m_valid_1_rl) ;
  assign m_m_valid_1_rl$EN = 1'd1 ;

  // remaining internal signals
  assign IF_m_m_specBits_0_lat_0_whas__8_THEN_IF_m_m_sp_ETC___d22 =
	     m_m_valid_0_lat_1$whas ? enq_x[11:0] : m_m_specBits_0_rl ;
  assign IF_m_m_specBits_1_lat_0_whas__7_THEN_IF_m_m_sp_ETC___d31 =
	     m_m_valid_1_lat_1$whas ? enq_x[11:0] : m_m_specBits_1_rl ;
  assign SEL_ARR_NOT_m_m_valid_0_rl_2_NOT_m_m_valid_1_r_ETC___d51 =
	     CASE_m_m_deqP_ehr_rl_0_NOT_m_m_valid_0_rl_1_NO_ETC__q1 &&
	     (m_m_enqP != m_m_deqP_ehr_rl || m_m_valid_0_rl ||
	      m_m_valid_1_rl) ;
  assign SEL_ARR_m_m_row_0_1_BITS_172_TO_109_7_m_m_row__ETC___d191 =
	     { CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_172_TO_1_ETC__q24,
	       SEL_ARR_m_m_row_0_1_BIT_108_1_m_m_row_1_3_BIT__ETC___d166,
	       SEL_ARR_m_m_row_0_1_BIT_91_67_m_m_row_1_3_BIT__ETC___d190 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d107 =
	     { CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_107_1_m_m_ETC__q2,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_106_1_m_m_ETC__q3,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_105_1_m_m_ETC__q4 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d116 =
	     { SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d107,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_104_1_m_m_ETC__q5,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_103_1_m_m_ETC__q6 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d125 =
	     { SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d116,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_102_1_m_m_ETC__q7,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_101_1_m_m_ETC__q8 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d134 =
	     { SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d125,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_100_1_m_m_ETC__q9,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_99_1_m_m__ETC__q10 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d143 =
	     { SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d134,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_98_1_m_m__ETC__q11,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_97_1_m_m__ETC__q12 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d152 =
	     { SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d143,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_96_1_m_m__ETC__q13,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_95_1_m_m__ETC__q14 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d161 =
	     { SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d152,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_94_1_m_m__ETC__q15,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_93_1_m_m__ETC__q16 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_108_1_m_m_row_1_3_BIT__ETC___d166 =
	     { CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_108_1_m_m_ETC__q17,
	       SEL_ARR_m_m_row_0_1_BIT_107_5_m_m_row_1_3_BIT__ETC___d161,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_92_1_m_m__ETC__q18 } ;
  assign SEL_ARR_m_m_row_0_1_BIT_91_67_m_m_row_1_3_BIT__ETC___d190 =
	     { CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_91_1_m_m__ETC__q19,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_90_TO_27_ETC__q20,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_26_TO_11_ETC__q21,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_10_TO_3__ETC__q22,
	       CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_2_TO_0_1_ETC__q23 } ;
  assign upd__h1586 =
	     IF_m_m_specBits_0_lat_0_whas__8_THEN_IF_m_m_sp_ETC___d22 &
	     specUpdate_correctSpeculation_mask ;
  assign upd__h1924 =
	     IF_m_m_specBits_1_lat_0_whas__7_THEN_IF_m_m_sp_ETC___d31 &
	     specUpdate_correctSpeculation_mask ;
  assign upd__h2448 = m_m_deqP_ehr_rl + 1'd1 ;
  always@(m_m_deqP_ehr_rl or m_m_valid_0_rl or m_m_valid_1_rl)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_NOT_m_m_valid_0_rl_1_NO_ETC__q1 =
	      !m_m_valid_0_rl;
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_NOT_m_m_valid_0_rl_1_NO_ETC__q1 =
	      !m_m_valid_1_rl;
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_107_1_m_m_ETC__q2 =
	      m_m_row_0[107];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_107_1_m_m_ETC__q2 =
	      m_m_row_1[107];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_106_1_m_m_ETC__q3 =
	      m_m_row_0[106];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_106_1_m_m_ETC__q3 =
	      m_m_row_1[106];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_105_1_m_m_ETC__q4 =
	      m_m_row_0[105];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_105_1_m_m_ETC__q4 =
	      m_m_row_1[105];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_104_1_m_m_ETC__q5 =
	      m_m_row_0[104];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_104_1_m_m_ETC__q5 =
	      m_m_row_1[104];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_103_1_m_m_ETC__q6 =
	      m_m_row_0[103];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_103_1_m_m_ETC__q6 =
	      m_m_row_1[103];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_102_1_m_m_ETC__q7 =
	      m_m_row_0[102];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_102_1_m_m_ETC__q7 =
	      m_m_row_1[102];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_101_1_m_m_ETC__q8 =
	      m_m_row_0[101];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_101_1_m_m_ETC__q8 =
	      m_m_row_1[101];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_100_1_m_m_ETC__q9 =
	      m_m_row_0[100];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_100_1_m_m_ETC__q9 =
	      m_m_row_1[100];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_99_1_m_m__ETC__q10 =
	      m_m_row_0[99];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_99_1_m_m__ETC__q10 =
	      m_m_row_1[99];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_98_1_m_m__ETC__q11 =
	      m_m_row_0[98];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_98_1_m_m__ETC__q11 =
	      m_m_row_1[98];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_97_1_m_m__ETC__q12 =
	      m_m_row_0[97];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_97_1_m_m__ETC__q12 =
	      m_m_row_1[97];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_96_1_m_m__ETC__q13 =
	      m_m_row_0[96];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_96_1_m_m__ETC__q13 =
	      m_m_row_1[96];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_95_1_m_m__ETC__q14 =
	      m_m_row_0[95];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_95_1_m_m__ETC__q14 =
	      m_m_row_1[95];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_94_1_m_m__ETC__q15 =
	      m_m_row_0[94];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_94_1_m_m__ETC__q15 =
	      m_m_row_1[94];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_93_1_m_m__ETC__q16 =
	      m_m_row_0[93];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_93_1_m_m__ETC__q16 =
	      m_m_row_1[93];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_108_1_m_m_ETC__q17 =
	      m_m_row_0[108];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_108_1_m_m_ETC__q17 =
	      m_m_row_1[108];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_92_1_m_m__ETC__q18 =
	      m_m_row_0[92];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_92_1_m_m__ETC__q18 =
	      m_m_row_1[92];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_91_1_m_m__ETC__q19 =
	      m_m_row_0[91];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BIT_91_1_m_m__ETC__q19 =
	      m_m_row_1[91];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_90_TO_27_ETC__q20 =
	      m_m_row_0[90:27];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_90_TO_27_ETC__q20 =
	      m_m_row_1[90:27];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_26_TO_11_ETC__q21 =
	      m_m_row_0[26:11];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_26_TO_11_ETC__q21 =
	      m_m_row_1[26:11];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_10_TO_3__ETC__q22 =
	      m_m_row_0[10:3];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_10_TO_3__ETC__q22 =
	      m_m_row_1[10:3];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_2_TO_0_1_ETC__q23 =
	      m_m_row_0[2:0];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_2_TO_0_1_ETC__q23 =
	      m_m_row_1[2:0];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_172_TO_1_ETC__q24 =
	      m_m_row_0[172:109];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_172_TO_1_ETC__q24 =
	      m_m_row_1[172:109];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_row_0 or m_m_row_1)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_177_TO_1_ETC__q25 =
	      m_m_row_0[177:173];
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_row_0_BITS_177_TO_1_ETC__q25 =
	      m_m_row_1[177:173];
    endcase
  end
  always@(m_m_deqP_ehr_rl or m_m_specBits_0_rl or m_m_specBits_1_rl)
  begin
    case (m_m_deqP_ehr_rl)
      1'd0:
	  CASE_m_m_deqP_ehr_rl_0_m_m_specBits_0_rl_1_m_m_ETC__q26 =
	      m_m_specBits_0_rl;
      1'd1:
	  CASE_m_m_deqP_ehr_rl_0_m_m_specBits_0_rl_1_m_m_ETC__q26 =
	      m_m_specBits_1_rl;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        m_m_deqP_ehr_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_m_enqP <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_m_specBits_0_rl <= `BSV_ASSIGNMENT_DELAY
	    12'bxxxxxxxxxxxx /* unspecified value */ ;
	m_m_specBits_1_rl <= `BSV_ASSIGNMENT_DELAY
	    12'bxxxxxxxxxxxx /* unspecified value */ ;
	m_m_valid_0_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m_m_valid_1_rl <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (m_m_deqP_ehr_rl$EN)
	  m_m_deqP_ehr_rl <= `BSV_ASSIGNMENT_DELAY m_m_deqP_ehr_rl$D_IN;
	if (m_m_enqP$EN) m_m_enqP <= `BSV_ASSIGNMENT_DELAY m_m_enqP$D_IN;
	if (m_m_specBits_0_rl$EN)
	  m_m_specBits_0_rl <= `BSV_ASSIGNMENT_DELAY m_m_specBits_0_rl$D_IN;
	if (m_m_specBits_1_rl$EN)
	  m_m_specBits_1_rl <= `BSV_ASSIGNMENT_DELAY m_m_specBits_1_rl$D_IN;
	if (m_m_valid_0_rl$EN)
	  m_m_valid_0_rl <= `BSV_ASSIGNMENT_DELAY m_m_valid_0_rl$D_IN;
	if (m_m_valid_1_rl$EN)
	  m_m_valid_1_rl <= `BSV_ASSIGNMENT_DELAY m_m_valid_1_rl$D_IN;
      end
    if (m_m_row_0$EN) m_m_row_0 <= `BSV_ASSIGNMENT_DELAY m_m_row_0$D_IN;
    if (m_m_row_1$EN) m_m_row_1 <= `BSV_ASSIGNMENT_DELAY m_m_row_1$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    m_m_deqP_ehr_rl = 1'h0;
    m_m_enqP = 1'h0;
    m_m_row_0 = 178'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    m_m_row_1 = 178'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    m_m_specBits_0_rl = 12'hAAA;
    m_m_specBits_1_rl = 12'hAAA;
    m_m_valid_0_rl = 1'h0;
    m_m_valid_1_rl = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_enq && m_m_valid_for_enq_wire$wget)
	$fdisplay(32'h80000002, "\n%m: ASSERT FAIL!!");
  end
  // synopsys translate_on
endmodule  // mkLSQIssueLdQ

