//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:17:25 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// setBoundsALU                   O   161
// setBoundsALU_cap               I   161
// setBoundsALU_len               I    64
// setBoundsALU_boundsOp          I     2
//
// Combinational paths from inputs to outputs:
//   (setBoundsALU_cap, setBoundsALU_len, setBoundsALU_boundsOp) -> setBoundsALU
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_setBoundsALU(setBoundsALU_cap,
			   setBoundsALU_len,
			   setBoundsALU_boundsOp,
			   setBoundsALU);
  // value method setBoundsALU
  input  [160 : 0] setBoundsALU_cap;
  input  [63 : 0] setBoundsALU_len;
  input  [1 : 0] setBoundsALU_boundsOp;
  output [160 : 0] setBoundsALU;

  // signals for module outputs
  wire [160 : 0] setBoundsALU;

  // remaining internal signals
  reg [63 : 0] CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q4;
  reg [33 : 0] CASE_setBoundsALU_boundsOp_0_IF_setBoundsALU_l_ETC__q3;
  reg [13 : 0] CASE_setBoundsALU_boundsOp_0_result_cap_addrBi_ETC__q5;
  reg [7 : 0] x__h10131, x__h10142;
  reg [3 : 0] CASE_setBoundsALU_boundsOp_0_IF_IF_NOT_setBoun_ETC__q6,
	      CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q2,
	      res_capFat_perms_soft__h9788;
  reg [2 : 0] res_tempFields_repBoundTopBits__h10389;
  wire [149 : 0] IF_setBoundsALU_boundsOp_EQ_1_44_OR_setBoundsA_ETC___d492;
  wire [65 : 0] _theResult_____2_fst__h9561,
		baseMask___1__h9560,
		base__h95,
		carries__h134,
		carryMask__h133,
		lmaskLo__h103,
		lmaskLor__h102,
		lowMask__h132,
		mwLsbMask__h111,
		newLengthRounded__h9557,
		newLengthRounded__h9559,
		newLength___2__h9558,
		newLength__h122,
		oneInLsb__h9556,
		top__h98,
		x__h10257,
		x__h8783,
		x__h8809,
		x__h9385,
		x__h9550,
		x__h9616,
		x__h9658,
		y__h8797,
		y__h9386,
		y__h9578;
  wire [63 : 0] lengthShifted__h126,
		setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d316,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d12,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d15,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d18,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d6,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d9,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC__q1;
  wire [38 : 0] IF_setBoundsALU_boundsOp_EQ_1_44_OR_setBoundsA_ETC___d489;
  wire [27 : 0] IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d485;
  wire [15 : 0] setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d211;
  wire [14 : 0] reqTopBits__h130, x__h10296;
  wire [13 : 0] _theResult_____3_bounds_baseBits__h10184,
		_theResult_____3_bounds_topBits__h10183,
		_theResult_____4_snd_bounds_topBits__h9647,
		res_addrBits__h9246,
		res_addrBits__h9258,
		result_cap_addrBits__h9233,
		ret_bounds_baseBits__h10208,
		ret_bounds_topBits__h10288,
		ret_bounds_topBits__h9643;
  wire [6 : 0] NOT_setBoundsALU_boundsOp_EQ_1_44_60_AND_NOT_s_ETC___d519;
  wire [5 : 0] IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d464,
	       _51_MINUS_IF_setBoundsALU_len_BIT_63_6_THEN_0_E_ETC___d404;
  wire [3 : 0] IF_IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT__ETC___d516;
  wire [2 : 0] repBound__h10345;
  wire IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d500,
       IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d502,
       IF_setBoundsALU_cap_BIT_5_91_EQ_setBoundsALU_c_ETC___d243,
       IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505,
       NOT_0_CONCAT_setBoundsALU_len_OR_0_CONCAT_setB_ETC___d346,
       NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d325,
       NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d475,
       NOT_setBoundsALU_boundsOp_EQ_0_OR_setBoundsALU_ETC___d249,
       _0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_82__ETC___d188,
       setBoundsALU_cap_BITS_159_TO_96_AND_0_CONCAT_s_ETC___d181,
       setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d228,
       setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d232,
       setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d323,
       setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d347,
       setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d350,
       setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d351,
       setBoundsALU_len_SRL_setBoundsALU_cap_BITS_43__ETC___d234;

  // value method setBoundsALU
  assign setBoundsALU =
	     { NOT_setBoundsALU_boundsOp_EQ_0_OR_setBoundsALU_ETC___d249,
	       IF_setBoundsALU_boundsOp_EQ_1_44_OR_setBoundsA_ETC___d492,
	       res_tempFields_repBoundTopBits__h10389,
	       NOT_setBoundsALU_boundsOp_EQ_1_44_60_AND_NOT_s_ETC___d519 } ;

  // remaining internal signals
  assign IF_IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT__ETC___d516 =
	     { (IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d500 ==
		IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505) ?
		 2'd0 :
		 ((IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d500 &&
		   !IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505) ?
		    2'd1 :
		    2'd3),
	       (IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d502 ==
		IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505) ?
		 2'd0 :
		 ((IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d502 &&
		   !IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d485 =
	     (!setBoundsALU_len[63] && !setBoundsALU_len[62] &&
	      !setBoundsALU_len[61] &&
	      !setBoundsALU_len[60] &&
	      !setBoundsALU_len[59] &&
	      !setBoundsALU_len[58] &&
	      !setBoundsALU_len[57] &&
	      !setBoundsALU_len[56] &&
	      !setBoundsALU_len[55] &&
	      !setBoundsALU_len[54] &&
	      !setBoundsALU_len[53] &&
	      !setBoundsALU_len[52] &&
	      !setBoundsALU_len[51] &&
	      !setBoundsALU_len[50] &&
	      !setBoundsALU_len[49] &&
	      !setBoundsALU_len[48] &&
	      !setBoundsALU_len[47] &&
	      !setBoundsALU_len[46] &&
	      !setBoundsALU_len[45] &&
	      !setBoundsALU_len[44] &&
	      !setBoundsALU_len[43] &&
	      !setBoundsALU_len[42] &&
	      !setBoundsALU_len[41] &&
	      !setBoundsALU_len[40] &&
	      !setBoundsALU_len[39] &&
	      !setBoundsALU_len[38] &&
	      !setBoundsALU_len[37] &&
	      !setBoundsALU_len[36] &&
	      !setBoundsALU_len[35] &&
	      !setBoundsALU_len[34] &&
	      !setBoundsALU_len[33] &&
	      !setBoundsALU_len[32] &&
	      !setBoundsALU_len[31] &&
	      !setBoundsALU_len[30] &&
	      !setBoundsALU_len[29] &&
	      !setBoundsALU_len[28] &&
	      !setBoundsALU_len[27] &&
	      !setBoundsALU_len[26] &&
	      !setBoundsALU_len[25] &&
	      !setBoundsALU_len[24] &&
	      !setBoundsALU_len[23] &&
	      !setBoundsALU_len[22] &&
	      !setBoundsALU_len[21] &&
	      !setBoundsALU_len[20] &&
	      !setBoundsALU_len[19] &&
	      !setBoundsALU_len[18] &&
	      !setBoundsALU_len[17] &&
	      !setBoundsALU_len[16] &&
	      !setBoundsALU_len[15] &&
	      !setBoundsALU_len[14] &&
	      !setBoundsALU_len[13] &&
	      !setBoundsALU_len[12]) ?
	       { ret_bounds_topBits__h10288, x__h9658[13:0] } :
	       { ret_bounds_topBits__h9643[13:3],
		 3'd0,
		 ret_bounds_baseBits__h10208 } ;
  assign IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d500 =
	     _theResult_____3_bounds_topBits__h10183[13:11] <
	     repBound__h10345 ;
  assign IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d502 =
	     _theResult_____3_bounds_baseBits__h10184[13:11] <
	     repBound__h10345 ;
  assign IF_setBoundsALU_boundsOp_EQ_1_44_OR_setBoundsA_ETC___d489 =
	     { CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q2,
	       setBoundsALU_boundsOp != 2'd1 &&
	       setBoundsALU_boundsOp != 2'd0 ||
	       setBoundsALU_len[63] ||
	       setBoundsALU_len[62] ||
	       setBoundsALU_len[61] ||
	       setBoundsALU_len[60] ||
	       setBoundsALU_len[59] ||
	       setBoundsALU_len[58] ||
	       setBoundsALU_len[57] ||
	       setBoundsALU_len[56] ||
	       setBoundsALU_len[55] ||
	       setBoundsALU_len[54] ||
	       setBoundsALU_len[53] ||
	       setBoundsALU_len[52] ||
	       setBoundsALU_len[51] ||
	       setBoundsALU_len[50] ||
	       setBoundsALU_len[49] ||
	       setBoundsALU_len[48] ||
	       setBoundsALU_len[47] ||
	       setBoundsALU_len[46] ||
	       setBoundsALU_len[45] ||
	       setBoundsALU_len[44] ||
	       setBoundsALU_len[43] ||
	       setBoundsALU_len[42] ||
	       setBoundsALU_len[41] ||
	       setBoundsALU_len[40] ||
	       setBoundsALU_len[39] ||
	       setBoundsALU_len[38] ||
	       setBoundsALU_len[37] ||
	       setBoundsALU_len[36] ||
	       setBoundsALU_len[35] ||
	       setBoundsALU_len[34] ||
	       setBoundsALU_len[33] ||
	       setBoundsALU_len[32] ||
	       setBoundsALU_len[31] ||
	       setBoundsALU_len[30] ||
	       setBoundsALU_len[29] ||
	       setBoundsALU_len[28] ||
	       setBoundsALU_len[27] ||
	       setBoundsALU_len[26] ||
	       setBoundsALU_len[25] ||
	       setBoundsALU_len[24] ||
	       setBoundsALU_len[23] ||
	       setBoundsALU_len[22] ||
	       setBoundsALU_len[21] ||
	       setBoundsALU_len[20] ||
	       setBoundsALU_len[19] ||
	       setBoundsALU_len[18] ||
	       setBoundsALU_len[17] ||
	       setBoundsALU_len[16] ||
	       setBoundsALU_len[15] ||
	       setBoundsALU_len[14] ||
	       setBoundsALU_len[13] ||
	       setBoundsALU_len[12],
	       CASE_setBoundsALU_boundsOp_0_IF_setBoundsALU_l_ETC__q3 } ;
  assign IF_setBoundsALU_boundsOp_EQ_1_44_OR_setBoundsA_ETC___d492 =
	     { CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q4,
	       CASE_setBoundsALU_boundsOp_0_result_cap_addrBi_ETC__q5,
	       res_capFat_perms_soft__h9788,
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[77],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[76],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[75],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[74],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[73],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[72],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[71],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[70],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[69],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[68],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[67],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[66],
	       (setBoundsALU_boundsOp == 2'd1 ||
		setBoundsALU_boundsOp == 2'd0) &&
	       setBoundsALU_cap[65],
	       x__h10131,
	       x__h10142,
	       IF_setBoundsALU_boundsOp_EQ_1_44_OR_setBoundsA_ETC___d489 } ;
  assign IF_setBoundsALU_cap_BIT_5_91_EQ_setBoundsALU_c_ETC___d243 =
	     ((setBoundsALU_cap[5] == setBoundsALU_cap[4]) ?
		setBoundsALU_cap[95:82] >= setBoundsALU_cap[23:10] :
		setBoundsALU_cap[4]) &&
	     setBoundsALU_len_SRL_setBoundsALU_cap_BITS_43__ETC___d234 &&
	     (setBoundsALU_len != 64'd0 ||
	      setBoundsALU_cap[159:96] != 64'd0 ||
	      setBoundsALU_cap[23:10] == 14'd0) ;
  assign IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d464 =
	     (setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d351 &&
	      (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	       setBoundsALU_len[61] ||
	       setBoundsALU_len[60] ||
	       setBoundsALU_len[59] ||
	       setBoundsALU_len[58] ||
	       setBoundsALU_len[57] ||
	       setBoundsALU_len[56] ||
	       setBoundsALU_len[55] ||
	       setBoundsALU_len[54] ||
	       setBoundsALU_len[53] ||
	       setBoundsALU_len[52] ||
	       setBoundsALU_len[51] ||
	       setBoundsALU_len[50] ||
	       setBoundsALU_len[49] ||
	       setBoundsALU_len[48] ||
	       setBoundsALU_len[47] ||
	       setBoundsALU_len[46] ||
	       setBoundsALU_len[45] ||
	       setBoundsALU_len[44] ||
	       setBoundsALU_len[43] ||
	       setBoundsALU_len[42] ||
	       setBoundsALU_len[41] ||
	       setBoundsALU_len[40] ||
	       setBoundsALU_len[39] ||
	       setBoundsALU_len[38] ||
	       setBoundsALU_len[37] ||
	       setBoundsALU_len[36] ||
	       setBoundsALU_len[35] ||
	       setBoundsALU_len[34] ||
	       setBoundsALU_len[33] ||
	       setBoundsALU_len[32] ||
	       setBoundsALU_len[31] ||
	       setBoundsALU_len[30] ||
	       setBoundsALU_len[29] ||
	       setBoundsALU_len[28] ||
	       setBoundsALU_len[27] ||
	       setBoundsALU_len[26] ||
	       setBoundsALU_len[25] ||
	       setBoundsALU_len[24] ||
	       setBoundsALU_len[23] ||
	       setBoundsALU_len[22] ||
	       setBoundsALU_len[21] ||
	       setBoundsALU_len[20] ||
	       setBoundsALU_len[19] ||
	       setBoundsALU_len[18] ||
	       setBoundsALU_len[17] ||
	       setBoundsALU_len[16] ||
	       setBoundsALU_len[15] ||
	       setBoundsALU_len[14] ||
	       setBoundsALU_len[13] ||
	       setBoundsALU_len[12])) ?
	       _51_MINUS_IF_setBoundsALU_len_BIT_63_6_THEN_0_E_ETC___d404 +
	       6'd1 :
	       _51_MINUS_IF_setBoundsALU_len_BIT_63_6_THEN_0_E_ETC___d404 ;
  assign IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505 =
	     result_cap_addrBits__h9233[13:11] < repBound__h10345 ;
  assign NOT_0_CONCAT_setBoundsALU_len_OR_0_CONCAT_setB_ETC___d346 =
	     (mwLsbMask__h111 & top__h98) != (x__h9385 ^ y__h9386) ;
  assign NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d325 =
	     (top__h98 & lmaskLor__h102) != 66'd0 &&
	     (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	      setBoundsALU_len[61] ||
	      setBoundsALU_len[60] ||
	      setBoundsALU_len[59] ||
	      setBoundsALU_len[58] ||
	      setBoundsALU_len[57] ||
	      setBoundsALU_len[56] ||
	      setBoundsALU_len[55] ||
	      setBoundsALU_len[54] ||
	      setBoundsALU_len[53] ||
	      setBoundsALU_len[52] ||
	      setBoundsALU_len[51] ||
	      setBoundsALU_len[50] ||
	      setBoundsALU_len[49] ||
	      setBoundsALU_len[48] ||
	      setBoundsALU_len[47] ||
	      setBoundsALU_len[46] ||
	      setBoundsALU_len[45] ||
	      setBoundsALU_len[44] ||
	      setBoundsALU_len[43] ||
	      setBoundsALU_len[42] ||
	      setBoundsALU_len[41] ||
	      setBoundsALU_len[40] ||
	      setBoundsALU_len[39] ||
	      setBoundsALU_len[38] ||
	      setBoundsALU_len[37] ||
	      setBoundsALU_len[36] ||
	      setBoundsALU_len[35] ||
	      setBoundsALU_len[34] ||
	      setBoundsALU_len[33] ||
	      setBoundsALU_len[32] ||
	      setBoundsALU_len[31] ||
	      setBoundsALU_len[30] ||
	      setBoundsALU_len[29] ||
	      setBoundsALU_len[28] ||
	      setBoundsALU_len[27] ||
	      setBoundsALU_len[26] ||
	      setBoundsALU_len[25] ||
	      setBoundsALU_len[24] ||
	      setBoundsALU_len[23] ||
	      setBoundsALU_len[22] ||
	      setBoundsALU_len[21] ||
	      setBoundsALU_len[20] ||
	      setBoundsALU_len[19] ||
	      setBoundsALU_len[18] ||
	      setBoundsALU_len[17] ||
	      setBoundsALU_len[16] ||
	      setBoundsALU_len[15] ||
	      setBoundsALU_len[14] ||
	      setBoundsALU_len[13] ||
	      setBoundsALU_len[12]) ;
  assign NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d475 =
	     (top__h98 & lmaskLo__h103) != 66'd0 &&
	     (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	      setBoundsALU_len[61] ||
	      setBoundsALU_len[60] ||
	      setBoundsALU_len[59] ||
	      setBoundsALU_len[58] ||
	      setBoundsALU_len[57] ||
	      setBoundsALU_len[56] ||
	      setBoundsALU_len[55] ||
	      setBoundsALU_len[54] ||
	      setBoundsALU_len[53] ||
	      setBoundsALU_len[52] ||
	      setBoundsALU_len[51] ||
	      setBoundsALU_len[50] ||
	      setBoundsALU_len[49] ||
	      setBoundsALU_len[48] ||
	      setBoundsALU_len[47] ||
	      setBoundsALU_len[46] ||
	      setBoundsALU_len[45] ||
	      setBoundsALU_len[44] ||
	      setBoundsALU_len[43] ||
	      setBoundsALU_len[42] ||
	      setBoundsALU_len[41] ||
	      setBoundsALU_len[40] ||
	      setBoundsALU_len[39] ||
	      setBoundsALU_len[38] ||
	      setBoundsALU_len[37] ||
	      setBoundsALU_len[36] ||
	      setBoundsALU_len[35] ||
	      setBoundsALU_len[34] ||
	      setBoundsALU_len[33] ||
	      setBoundsALU_len[32] ||
	      setBoundsALU_len[31] ||
	      setBoundsALU_len[30] ||
	      setBoundsALU_len[29] ||
	      setBoundsALU_len[28] ||
	      setBoundsALU_len[27] ||
	      setBoundsALU_len[26] ||
	      setBoundsALU_len[25] ||
	      setBoundsALU_len[24] ||
	      setBoundsALU_len[23] ||
	      setBoundsALU_len[22] ||
	      setBoundsALU_len[21] ||
	      setBoundsALU_len[20] ||
	      setBoundsALU_len[19] ||
	      setBoundsALU_len[18] ||
	      setBoundsALU_len[17] ||
	      setBoundsALU_len[16] ||
	      setBoundsALU_len[15] ||
	      setBoundsALU_len[14] ||
	      setBoundsALU_len[13] ||
	      setBoundsALU_len[12]) ;
  assign NOT_setBoundsALU_boundsOp_EQ_0_OR_setBoundsALU_ETC___d249 =
	     (setBoundsALU_boundsOp != 2'd0 ||
	      setBoundsALU_cap_BITS_159_TO_96_AND_0_CONCAT_s_ETC___d181 &&
	      _0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_82__ETC___d188) &&
	     IF_setBoundsALU_cap_BIT_5_91_EQ_setBoundsALU_c_ETC___d243 &&
	     (setBoundsALU_boundsOp == 2'd1 ||
	      setBoundsALU_boundsOp == 2'd0) &&
	     setBoundsALU_cap[160] ;
  assign NOT_setBoundsALU_boundsOp_EQ_1_44_60_AND_NOT_s_ETC___d519 =
	     { setBoundsALU_boundsOp != 2'd1 &&
	       setBoundsALU_boundsOp != 2'd0 ||
	       IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d500,
	       setBoundsALU_boundsOp != 2'd1 &&
	       setBoundsALU_boundsOp != 2'd0 ||
	       IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d502,
	       setBoundsALU_boundsOp != 2'd1 &&
	       setBoundsALU_boundsOp != 2'd0 ||
	       IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d505,
	       CASE_setBoundsALU_boundsOp_0_IF_IF_NOT_setBoun_ETC__q6 } ;
  assign _0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_82__ETC___d188 =
	     (top__h98 & lmaskLor__h102) == 66'd0 ||
	     !setBoundsALU_len[63] && !setBoundsALU_len[62] &&
	     !setBoundsALU_len[61] &&
	     !setBoundsALU_len[60] &&
	     !setBoundsALU_len[59] &&
	     !setBoundsALU_len[58] &&
	     !setBoundsALU_len[57] &&
	     !setBoundsALU_len[56] &&
	     !setBoundsALU_len[55] &&
	     !setBoundsALU_len[54] &&
	     !setBoundsALU_len[53] &&
	     !setBoundsALU_len[52] &&
	     !setBoundsALU_len[51] &&
	     !setBoundsALU_len[50] &&
	     !setBoundsALU_len[49] &&
	     !setBoundsALU_len[48] &&
	     !setBoundsALU_len[47] &&
	     !setBoundsALU_len[46] &&
	     !setBoundsALU_len[45] &&
	     !setBoundsALU_len[44] &&
	     !setBoundsALU_len[43] &&
	     !setBoundsALU_len[42] &&
	     !setBoundsALU_len[41] &&
	     !setBoundsALU_len[40] &&
	     !setBoundsALU_len[39] &&
	     !setBoundsALU_len[38] &&
	     !setBoundsALU_len[37] &&
	     !setBoundsALU_len[36] &&
	     !setBoundsALU_len[35] &&
	     !setBoundsALU_len[34] &&
	     !setBoundsALU_len[33] &&
	     !setBoundsALU_len[32] &&
	     !setBoundsALU_len[31] &&
	     !setBoundsALU_len[30] &&
	     !setBoundsALU_len[29] &&
	     !setBoundsALU_len[28] &&
	     !setBoundsALU_len[27] &&
	     !setBoundsALU_len[26] &&
	     !setBoundsALU_len[25] &&
	     !setBoundsALU_len[24] &&
	     !setBoundsALU_len[23] &&
	     !setBoundsALU_len[22] &&
	     !setBoundsALU_len[21] &&
	     !setBoundsALU_len[20] &&
	     !setBoundsALU_len[19] &&
	     !setBoundsALU_len[18] &&
	     !setBoundsALU_len[17] &&
	     !setBoundsALU_len[16] &&
	     !setBoundsALU_len[15] &&
	     !setBoundsALU_len[14] &&
	     !setBoundsALU_len[13] &&
	     !setBoundsALU_len[12] ;
  assign _51_MINUS_IF_setBoundsALU_len_BIT_63_6_THEN_0_E_ETC___d404 =
	     6'd51 -
	     (setBoundsALU_len[63] ?
		6'd0 :
		(setBoundsALU_len[62] ?
		   6'd1 :
		   (setBoundsALU_len[61] ?
		      6'd2 :
		      (setBoundsALU_len[60] ?
			 6'd3 :
			 (setBoundsALU_len[59] ?
			    6'd4 :
			    (setBoundsALU_len[58] ?
			       6'd5 :
			       (setBoundsALU_len[57] ?
				  6'd6 :
				  (setBoundsALU_len[56] ?
				     6'd7 :
				     (setBoundsALU_len[55] ?
					6'd8 :
					(setBoundsALU_len[54] ?
					   6'd9 :
					   (setBoundsALU_len[53] ?
					      6'd10 :
					      (setBoundsALU_len[52] ?
						 6'd11 :
						 (setBoundsALU_len[51] ?
						    6'd12 :
						    (setBoundsALU_len[50] ?
						       6'd13 :
						       (setBoundsALU_len[49] ?
							  6'd14 :
							  (setBoundsALU_len[48] ?
							     6'd15 :
							     (setBoundsALU_len[47] ?
								6'd16 :
								(setBoundsALU_len[46] ?
								   6'd17 :
								   (setBoundsALU_len[45] ?
								      6'd18 :
								      (setBoundsALU_len[44] ?
									 6'd19 :
									 (setBoundsALU_len[43] ?
									    6'd20 :
									    (setBoundsALU_len[42] ?
									       6'd21 :
									       (setBoundsALU_len[41] ?
										  6'd22 :
										  (setBoundsALU_len[40] ?
										     6'd23 :
										     (setBoundsALU_len[39] ?
											6'd24 :
											(setBoundsALU_len[38] ?
											   6'd25 :
											   (setBoundsALU_len[37] ?
											      6'd26 :
											      (setBoundsALU_len[36] ?
												 6'd27 :
												 (setBoundsALU_len[35] ?
												    6'd28 :
												    (setBoundsALU_len[34] ?
												       6'd29 :
												       (setBoundsALU_len[33] ?
													  6'd30 :
													  (setBoundsALU_len[32] ?
													     6'd31 :
													     (setBoundsALU_len[31] ?
														6'd32 :
														(setBoundsALU_len[30] ?
														   6'd33 :
														   (setBoundsALU_len[29] ?
														      6'd34 :
														      (setBoundsALU_len[28] ?
															 6'd35 :
															 (setBoundsALU_len[27] ?
															    6'd36 :
															    (setBoundsALU_len[26] ?
															       6'd37 :
															       (setBoundsALU_len[25] ?
																  6'd38 :
																  (setBoundsALU_len[24] ?
																     6'd39 :
																     (setBoundsALU_len[23] ?
																	6'd40 :
																	(setBoundsALU_len[22] ?
																	   6'd41 :
																	   (setBoundsALU_len[21] ?
																	      6'd42 :
																	      (setBoundsALU_len[20] ?
																		 6'd43 :
																		 (setBoundsALU_len[19] ?
																		    6'd44 :
																		    (setBoundsALU_len[18] ?
																		       6'd45 :
																		       (setBoundsALU_len[17] ?
																			  6'd46 :
																			  (setBoundsALU_len[16] ?
																			     6'd47 :
																			     (setBoundsALU_len[15] ?
																				6'd48 :
																				(setBoundsALU_len[14] ?
																				   6'd49 :
																				   (setBoundsALU_len[13] ?
																				      6'd50 :
																				      6'd51))))))))))))))))))))))))))))))))))))))))))))))))))) ;
  assign _theResult_____2_fst__h9561 =
	     ((setBoundsALU_len &
	       { 10'd0,
		 setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:10] }) !=
	      64'd0 &&
	      (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	       setBoundsALU_len[61] ||
	       setBoundsALU_len[60] ||
	       setBoundsALU_len[59] ||
	       setBoundsALU_len[58] ||
	       setBoundsALU_len[57] ||
	       setBoundsALU_len[56] ||
	       setBoundsALU_len[55] ||
	       setBoundsALU_len[54] ||
	       setBoundsALU_len[53] ||
	       setBoundsALU_len[52] ||
	       setBoundsALU_len[51] ||
	       setBoundsALU_len[50] ||
	       setBoundsALU_len[49] ||
	       setBoundsALU_len[48] ||
	       setBoundsALU_len[47] ||
	       setBoundsALU_len[46] ||
	       setBoundsALU_len[45] ||
	       setBoundsALU_len[44] ||
	       setBoundsALU_len[43] ||
	       setBoundsALU_len[42] ||
	       setBoundsALU_len[41] ||
	       setBoundsALU_len[40] ||
	       setBoundsALU_len[39] ||
	       setBoundsALU_len[38] ||
	       setBoundsALU_len[37] ||
	       setBoundsALU_len[36] ||
	       setBoundsALU_len[35] ||
	       setBoundsALU_len[34] ||
	       setBoundsALU_len[33] ||
	       setBoundsALU_len[32] ||
	       setBoundsALU_len[31] ||
	       setBoundsALU_len[30] ||
	       setBoundsALU_len[29] ||
	       setBoundsALU_len[28] ||
	       setBoundsALU_len[27] ||
	       setBoundsALU_len[26] ||
	       setBoundsALU_len[25] ||
	       setBoundsALU_len[24] ||
	       setBoundsALU_len[23] ||
	       setBoundsALU_len[22] ||
	       setBoundsALU_len[21] ||
	       setBoundsALU_len[20] ||
	       setBoundsALU_len[19] ||
	       setBoundsALU_len[18] ||
	       setBoundsALU_len[17] ||
	       setBoundsALU_len[16] ||
	       setBoundsALU_len[15] ||
	       setBoundsALU_len[14] ||
	       setBoundsALU_len[13] ||
	       setBoundsALU_len[12])) ?
	       newLengthRounded__h9559 :
	       newLength___2__h9558 ;
  assign _theResult_____3_bounds_baseBits__h10184 =
	     (!setBoundsALU_len[63] && !setBoundsALU_len[62] &&
	      !setBoundsALU_len[61] &&
	      !setBoundsALU_len[60] &&
	      !setBoundsALU_len[59] &&
	      !setBoundsALU_len[58] &&
	      !setBoundsALU_len[57] &&
	      !setBoundsALU_len[56] &&
	      !setBoundsALU_len[55] &&
	      !setBoundsALU_len[54] &&
	      !setBoundsALU_len[53] &&
	      !setBoundsALU_len[52] &&
	      !setBoundsALU_len[51] &&
	      !setBoundsALU_len[50] &&
	      !setBoundsALU_len[49] &&
	      !setBoundsALU_len[48] &&
	      !setBoundsALU_len[47] &&
	      !setBoundsALU_len[46] &&
	      !setBoundsALU_len[45] &&
	      !setBoundsALU_len[44] &&
	      !setBoundsALU_len[43] &&
	      !setBoundsALU_len[42] &&
	      !setBoundsALU_len[41] &&
	      !setBoundsALU_len[40] &&
	      !setBoundsALU_len[39] &&
	      !setBoundsALU_len[38] &&
	      !setBoundsALU_len[37] &&
	      !setBoundsALU_len[36] &&
	      !setBoundsALU_len[35] &&
	      !setBoundsALU_len[34] &&
	      !setBoundsALU_len[33] &&
	      !setBoundsALU_len[32] &&
	      !setBoundsALU_len[31] &&
	      !setBoundsALU_len[30] &&
	      !setBoundsALU_len[29] &&
	      !setBoundsALU_len[28] &&
	      !setBoundsALU_len[27] &&
	      !setBoundsALU_len[26] &&
	      !setBoundsALU_len[25] &&
	      !setBoundsALU_len[24] &&
	      !setBoundsALU_len[23] &&
	      !setBoundsALU_len[22] &&
	      !setBoundsALU_len[21] &&
	      !setBoundsALU_len[20] &&
	      !setBoundsALU_len[19] &&
	      !setBoundsALU_len[18] &&
	      !setBoundsALU_len[17] &&
	      !setBoundsALU_len[16] &&
	      !setBoundsALU_len[15] &&
	      !setBoundsALU_len[14] &&
	      !setBoundsALU_len[13] &&
	      !setBoundsALU_len[12]) ?
	       result_cap_addrBits__h9233 :
	       ret_bounds_baseBits__h10208 ;
  assign _theResult_____3_bounds_topBits__h10183 =
	     (!setBoundsALU_len[63] && !setBoundsALU_len[62] &&
	      !setBoundsALU_len[61] &&
	      !setBoundsALU_len[60] &&
	      !setBoundsALU_len[59] &&
	      !setBoundsALU_len[58] &&
	      !setBoundsALU_len[57] &&
	      !setBoundsALU_len[56] &&
	      !setBoundsALU_len[55] &&
	      !setBoundsALU_len[54] &&
	      !setBoundsALU_len[53] &&
	      !setBoundsALU_len[52] &&
	      !setBoundsALU_len[51] &&
	      !setBoundsALU_len[50] &&
	      !setBoundsALU_len[49] &&
	      !setBoundsALU_len[48] &&
	      !setBoundsALU_len[47] &&
	      !setBoundsALU_len[46] &&
	      !setBoundsALU_len[45] &&
	      !setBoundsALU_len[44] &&
	      !setBoundsALU_len[43] &&
	      !setBoundsALU_len[42] &&
	      !setBoundsALU_len[41] &&
	      !setBoundsALU_len[40] &&
	      !setBoundsALU_len[39] &&
	      !setBoundsALU_len[38] &&
	      !setBoundsALU_len[37] &&
	      !setBoundsALU_len[36] &&
	      !setBoundsALU_len[35] &&
	      !setBoundsALU_len[34] &&
	      !setBoundsALU_len[33] &&
	      !setBoundsALU_len[32] &&
	      !setBoundsALU_len[31] &&
	      !setBoundsALU_len[30] &&
	      !setBoundsALU_len[29] &&
	      !setBoundsALU_len[28] &&
	      !setBoundsALU_len[27] &&
	      !setBoundsALU_len[26] &&
	      !setBoundsALU_len[25] &&
	      !setBoundsALU_len[24] &&
	      !setBoundsALU_len[23] &&
	      !setBoundsALU_len[22] &&
	      !setBoundsALU_len[21] &&
	      !setBoundsALU_len[20] &&
	      !setBoundsALU_len[19] &&
	      !setBoundsALU_len[18] &&
	      !setBoundsALU_len[17] &&
	      !setBoundsALU_len[16] &&
	      !setBoundsALU_len[15] &&
	      !setBoundsALU_len[14] &&
	      !setBoundsALU_len[13] &&
	      !setBoundsALU_len[12]) ?
	       ret_bounds_topBits__h9643 :
	       { ret_bounds_topBits__h9643[13:3], 3'd0 } ;
  assign _theResult_____4_snd_bounds_topBits__h9647 =
	     NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d475 ?
	       x__h10257[14:1] + 14'b00000000001000 :
	       x__h10257[14:1] ;
  assign baseMask___1__h9560 =
	     (setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d323 &&
	      NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d325) ?
	       { 11'd2047,
		 ~setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:9] } :
	       y__h9578 ;
  assign base__h95 = { 2'b0, setBoundsALU_cap[159:96] } ;
  assign carries__h134 = x__h8783 ^ top__h98 ;
  assign carryMask__h133 = x__h8809 & y__h8797 ;
  assign lengthShifted__h126 = setBoundsALU_len >> setBoundsALU_cap[43:38] ;
  assign lmaskLo__h103 =
	     { 11'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:9] } ;
  assign lmaskLor__h102 =
	     { 12'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:10] } ;
  assign lowMask__h132 = ~x__h8809 ;
  assign mwLsbMask__h111 = lmaskLor__h102 ^ lmaskLo__h103 ;
  assign newLengthRounded__h9557 = newLength__h122 + oneInLsb__h9556 ;
  assign newLengthRounded__h9559 = newLengthRounded__h9557 & y__h9578 ;
  assign newLength___2__h9558 =
	     { 2'd0,
	       setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d316 } ;
  assign newLength__h122 = { 2'b0, setBoundsALU_len } ;
  assign oneInLsb__h9556 =
	     { 11'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC__q1[63:9] } ;
  assign repBound__h10345 =
	     _theResult_____3_bounds_baseBits__h10184[13:11] - 3'b001 ;
  assign reqTopBits__h130 =
	     { 1'b0, setBoundsALU_cap[95:82] } +
	     { 1'b0, lengthShifted__h126[13:0] } ;
  assign res_addrBits__h9246 = { 2'd0, x__h9550[63:52] } ;
  assign res_addrBits__h9258 = { 2'd0, x__h9616[63:52] } ;
  assign result_cap_addrBits__h9233 =
	     (setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d351 &&
	      (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	       setBoundsALU_len[61] ||
	       setBoundsALU_len[60] ||
	       setBoundsALU_len[59] ||
	       setBoundsALU_len[58] ||
	       setBoundsALU_len[57] ||
	       setBoundsALU_len[56] ||
	       setBoundsALU_len[55] ||
	       setBoundsALU_len[54] ||
	       setBoundsALU_len[53] ||
	       setBoundsALU_len[52] ||
	       setBoundsALU_len[51] ||
	       setBoundsALU_len[50] ||
	       setBoundsALU_len[49] ||
	       setBoundsALU_len[48] ||
	       setBoundsALU_len[47] ||
	       setBoundsALU_len[46] ||
	       setBoundsALU_len[45] ||
	       setBoundsALU_len[44] ||
	       setBoundsALU_len[43] ||
	       setBoundsALU_len[42] ||
	       setBoundsALU_len[41] ||
	       setBoundsALU_len[40] ||
	       setBoundsALU_len[39] ||
	       setBoundsALU_len[38] ||
	       setBoundsALU_len[37] ||
	       setBoundsALU_len[36] ||
	       setBoundsALU_len[35] ||
	       setBoundsALU_len[34] ||
	       setBoundsALU_len[33] ||
	       setBoundsALU_len[32] ||
	       setBoundsALU_len[31] ||
	       setBoundsALU_len[30] ||
	       setBoundsALU_len[29] ||
	       setBoundsALU_len[28] ||
	       setBoundsALU_len[27] ||
	       setBoundsALU_len[26] ||
	       setBoundsALU_len[25] ||
	       setBoundsALU_len[24] ||
	       setBoundsALU_len[23] ||
	       setBoundsALU_len[22] ||
	       setBoundsALU_len[21] ||
	       setBoundsALU_len[20] ||
	       setBoundsALU_len[19] ||
	       setBoundsALU_len[18] ||
	       setBoundsALU_len[17] ||
	       setBoundsALU_len[16] ||
	       setBoundsALU_len[15] ||
	       setBoundsALU_len[14] ||
	       setBoundsALU_len[13] ||
	       setBoundsALU_len[12])) ?
	       x__h9658[14:1] :
	       x__h9658[13:0] ;
  assign ret_bounds_baseBits__h10208 =
	     { result_cap_addrBits__h9233[13:3], 3'd0 } ;
  assign ret_bounds_topBits__h10288 =
	     NOT_0b0_CONCAT_setBoundsALU_cap_BITS_159_TO_96_ETC___d325 ?
	       x__h10296[13:0] :
	       x__h10257[13:0] ;
  assign ret_bounds_topBits__h9643 =
	     (setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d351 &&
	      (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	       setBoundsALU_len[61] ||
	       setBoundsALU_len[60] ||
	       setBoundsALU_len[59] ||
	       setBoundsALU_len[58] ||
	       setBoundsALU_len[57] ||
	       setBoundsALU_len[56] ||
	       setBoundsALU_len[55] ||
	       setBoundsALU_len[54] ||
	       setBoundsALU_len[53] ||
	       setBoundsALU_len[52] ||
	       setBoundsALU_len[51] ||
	       setBoundsALU_len[50] ||
	       setBoundsALU_len[49] ||
	       setBoundsALU_len[48] ||
	       setBoundsALU_len[47] ||
	       setBoundsALU_len[46] ||
	       setBoundsALU_len[45] ||
	       setBoundsALU_len[44] ||
	       setBoundsALU_len[43] ||
	       setBoundsALU_len[42] ||
	       setBoundsALU_len[41] ||
	       setBoundsALU_len[40] ||
	       setBoundsALU_len[39] ||
	       setBoundsALU_len[38] ||
	       setBoundsALU_len[37] ||
	       setBoundsALU_len[36] ||
	       setBoundsALU_len[35] ||
	       setBoundsALU_len[34] ||
	       setBoundsALU_len[33] ||
	       setBoundsALU_len[32] ||
	       setBoundsALU_len[31] ||
	       setBoundsALU_len[30] ||
	       setBoundsALU_len[29] ||
	       setBoundsALU_len[28] ||
	       setBoundsALU_len[27] ||
	       setBoundsALU_len[26] ||
	       setBoundsALU_len[25] ||
	       setBoundsALU_len[24] ||
	       setBoundsALU_len[23] ||
	       setBoundsALU_len[22] ||
	       setBoundsALU_len[21] ||
	       setBoundsALU_len[20] ||
	       setBoundsALU_len[19] ||
	       setBoundsALU_len[18] ||
	       setBoundsALU_len[17] ||
	       setBoundsALU_len[16] ||
	       setBoundsALU_len[15] ||
	       setBoundsALU_len[14] ||
	       setBoundsALU_len[13] ||
	       setBoundsALU_len[12])) ?
	       _theResult_____4_snd_bounds_topBits__h9647 :
	       ret_bounds_topBits__h10288 ;
  assign setBoundsALU_cap_BITS_159_TO_96_AND_0_CONCAT_s_ETC___d181 =
	     (setBoundsALU_cap[159:96] &
	      { 10'd0,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:10] }) ==
	     64'd0 ||
	     !setBoundsALU_len[63] && !setBoundsALU_len[62] &&
	     !setBoundsALU_len[61] &&
	     !setBoundsALU_len[60] &&
	     !setBoundsALU_len[59] &&
	     !setBoundsALU_len[58] &&
	     !setBoundsALU_len[57] &&
	     !setBoundsALU_len[56] &&
	     !setBoundsALU_len[55] &&
	     !setBoundsALU_len[54] &&
	     !setBoundsALU_len[53] &&
	     !setBoundsALU_len[52] &&
	     !setBoundsALU_len[51] &&
	     !setBoundsALU_len[50] &&
	     !setBoundsALU_len[49] &&
	     !setBoundsALU_len[48] &&
	     !setBoundsALU_len[47] &&
	     !setBoundsALU_len[46] &&
	     !setBoundsALU_len[45] &&
	     !setBoundsALU_len[44] &&
	     !setBoundsALU_len[43] &&
	     !setBoundsALU_len[42] &&
	     !setBoundsALU_len[41] &&
	     !setBoundsALU_len[40] &&
	     !setBoundsALU_len[39] &&
	     !setBoundsALU_len[38] &&
	     !setBoundsALU_len[37] &&
	     !setBoundsALU_len[36] &&
	     !setBoundsALU_len[35] &&
	     !setBoundsALU_len[34] &&
	     !setBoundsALU_len[33] &&
	     !setBoundsALU_len[32] &&
	     !setBoundsALU_len[31] &&
	     !setBoundsALU_len[30] &&
	     !setBoundsALU_len[29] &&
	     !setBoundsALU_len[28] &&
	     !setBoundsALU_len[27] &&
	     !setBoundsALU_len[26] &&
	     !setBoundsALU_len[25] &&
	     !setBoundsALU_len[24] &&
	     !setBoundsALU_len[23] &&
	     !setBoundsALU_len[22] &&
	     !setBoundsALU_len[21] &&
	     !setBoundsALU_len[20] &&
	     !setBoundsALU_len[19] &&
	     !setBoundsALU_len[18] &&
	     !setBoundsALU_len[17] &&
	     !setBoundsALU_len[16] &&
	     !setBoundsALU_len[15] &&
	     !setBoundsALU_len[14] &&
	     !setBoundsALU_len[13] &&
	     !setBoundsALU_len[12] ;
  assign setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d211 =
	     { setBoundsALU_cap[3:2], setBoundsALU_cap[37:24] } -
	     { 1'b0, reqTopBits__h130 } ;
  assign setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d228 =
	     setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d211 ==
	     16'd1 &&
	     ((carries__h134 & carryMask__h133) == 66'd0 ||
	      (top__h98 & lowMask__h132) == 66'd0) ;
  assign setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d232 =
	     setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d211 ==
	     16'd0 &&
	     (carries__h134 & carryMask__h133) == 66'd0 &&
	     (top__h98 & lowMask__h132) == 66'd0 ;
  assign setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d316 =
	     setBoundsALU_len &
	     { 10'd1023,
	       ~setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:10] } ;
  assign setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d323 =
	     setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d316 ==
	     (setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21 ^
	      { 10'd0,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:10] }) ;
  assign setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d347 =
	     setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d316 ==
	     (setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21 ^
	      { 9'd0,
		setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:9] }) &&
	     NOT_0_CONCAT_setBoundsALU_len_OR_0_CONCAT_setB_ETC___d346 ;
  assign setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d350 =
	     setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d323 &&
	     (NOT_0_CONCAT_setBoundsALU_len_OR_0_CONCAT_setB_ETC___d346 ||
	      (top__h98 & lmaskLor__h102) != 66'd0) ;
  assign setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d351 =
	     setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d347 &&
	     (top__h98 & lmaskLor__h102) != 66'd0 ||
	     setBoundsALU_len_AND_1023_CONCAT_INV_setBounds_ETC___d350 ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d12 =
	     setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d9 |
	     { 4'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d9[63:4] } ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d15 =
	     setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d12 |
	     { 8'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d12[63:8] } ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d18 =
	     setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d15 |
	     { 16'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d15[63:16] } ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21 =
	     setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d18 |
	     { 32'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d18[63:32] } ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d6 =
	     setBoundsALU_len | { 1'd0, setBoundsALU_len[63:1] } ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d9 =
	     setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d6 |
	     { 2'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d6[63:2] } ;
  assign setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC__q1 =
	     setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21 ^
	     { 1'd0,
	       setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:1] } ;
  assign setBoundsALU_len_SRL_setBoundsALU_cap_BITS_43__ETC___d234 =
	     lengthShifted__h126[63:14] == 50'd0 &&
	     ((setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d211 ^
	       16'h8000) >
	      16'd32769 ||
	      setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d228 ||
	      setBoundsALU_cap_BITS_3_TO_2_03_CONCAT_setBoun_ETC___d232) ;
  assign top__h98 = base__h95 + newLength__h122 ;
  assign x__h10257 =
	     top__h98 >>
	     _51_MINUS_IF_setBoundsALU_len_BIT_63_6_THEN_0_E_ETC___d404 ;
  assign x__h10296 = x__h10257[14:0] + 15'b000000000001000 ;
  assign x__h8783 = { 2'b0, setBoundsALU_len ^ setBoundsALU_cap[159:96] } ;
  assign x__h8809 = 66'h3FFFFFFFFFFFFFFFF << setBoundsALU_cap[43:38] ;
  assign x__h9385 = mwLsbMask__h111 & base__h95 ;
  assign x__h9550 =
	     (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	      setBoundsALU_len[61] ||
	      setBoundsALU_len[60] ||
	      setBoundsALU_len[59] ||
	      setBoundsALU_len[58] ||
	      setBoundsALU_len[57] ||
	      setBoundsALU_len[56] ||
	      setBoundsALU_len[55] ||
	      setBoundsALU_len[54] ||
	      setBoundsALU_len[53] ||
	      setBoundsALU_len[52] ||
	      setBoundsALU_len[51] ||
	      setBoundsALU_len[50] ||
	      setBoundsALU_len[49] ||
	      setBoundsALU_len[48] ||
	      setBoundsALU_len[47] ||
	      setBoundsALU_len[46] ||
	      setBoundsALU_len[45] ||
	      setBoundsALU_len[44] ||
	      setBoundsALU_len[43] ||
	      setBoundsALU_len[42] ||
	      setBoundsALU_len[41] ||
	      setBoundsALU_len[40] ||
	      setBoundsALU_len[39] ||
	      setBoundsALU_len[38] ||
	      setBoundsALU_len[37] ||
	      setBoundsALU_len[36] ||
	      setBoundsALU_len[35] ||
	      setBoundsALU_len[34] ||
	      setBoundsALU_len[33] ||
	      setBoundsALU_len[32] ||
	      setBoundsALU_len[31] ||
	      setBoundsALU_len[30] ||
	      setBoundsALU_len[29] ||
	      setBoundsALU_len[28] ||
	      setBoundsALU_len[27] ||
	      setBoundsALU_len[26] ||
	      setBoundsALU_len[25] ||
	      setBoundsALU_len[24] ||
	      setBoundsALU_len[23] ||
	      setBoundsALU_len[22] ||
	      setBoundsALU_len[21] ||
	      setBoundsALU_len[20] ||
	      setBoundsALU_len[19] ||
	      setBoundsALU_len[18] ||
	      setBoundsALU_len[17] ||
	      setBoundsALU_len[16] ||
	      setBoundsALU_len[15] ||
	      setBoundsALU_len[14] ||
	      setBoundsALU_len[13] ||
	      setBoundsALU_len[12]) ?
	       _theResult_____2_fst__h9561 :
	       newLength__h122 ;
  assign x__h9616 =
	     (setBoundsALU_len[63] || setBoundsALU_len[62] ||
	      setBoundsALU_len[61] ||
	      setBoundsALU_len[60] ||
	      setBoundsALU_len[59] ||
	      setBoundsALU_len[58] ||
	      setBoundsALU_len[57] ||
	      setBoundsALU_len[56] ||
	      setBoundsALU_len[55] ||
	      setBoundsALU_len[54] ||
	      setBoundsALU_len[53] ||
	      setBoundsALU_len[52] ||
	      setBoundsALU_len[51] ||
	      setBoundsALU_len[50] ||
	      setBoundsALU_len[49] ||
	      setBoundsALU_len[48] ||
	      setBoundsALU_len[47] ||
	      setBoundsALU_len[46] ||
	      setBoundsALU_len[45] ||
	      setBoundsALU_len[44] ||
	      setBoundsALU_len[43] ||
	      setBoundsALU_len[42] ||
	      setBoundsALU_len[41] ||
	      setBoundsALU_len[40] ||
	      setBoundsALU_len[39] ||
	      setBoundsALU_len[38] ||
	      setBoundsALU_len[37] ||
	      setBoundsALU_len[36] ||
	      setBoundsALU_len[35] ||
	      setBoundsALU_len[34] ||
	      setBoundsALU_len[33] ||
	      setBoundsALU_len[32] ||
	      setBoundsALU_len[31] ||
	      setBoundsALU_len[30] ||
	      setBoundsALU_len[29] ||
	      setBoundsALU_len[28] ||
	      setBoundsALU_len[27] ||
	      setBoundsALU_len[26] ||
	      setBoundsALU_len[25] ||
	      setBoundsALU_len[24] ||
	      setBoundsALU_len[23] ||
	      setBoundsALU_len[22] ||
	      setBoundsALU_len[21] ||
	      setBoundsALU_len[20] ||
	      setBoundsALU_len[19] ||
	      setBoundsALU_len[18] ||
	      setBoundsALU_len[17] ||
	      setBoundsALU_len[16] ||
	      setBoundsALU_len[15] ||
	      setBoundsALU_len[14] ||
	      setBoundsALU_len[13] ||
	      setBoundsALU_len[12]) ?
	       baseMask___1__h9560 :
	       66'h3FFFFFFFFFFFFFFFF ;
  assign x__h9658 =
	     base__h95 >>
	     _51_MINUS_IF_setBoundsALU_len_BIT_63_6_THEN_0_E_ETC___d404 ;
  assign y__h8797 = { lowMask__h132[64:0], 1'd0 } ;
  assign y__h9386 = mwLsbMask__h111 & newLength__h122 ;
  assign y__h9578 =
	     { 12'd4095,
	       ~setBoundsALU_len_OR_0_CONCAT_setBoundsALU_len__ETC___d21[63:10] } ;
  always@(setBoundsALU_boundsOp or setBoundsALU_cap)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1: res_capFat_perms_soft__h9788 = setBoundsALU_cap[81:78];
      default: res_capFat_perms_soft__h9788 = 4'd0;
    endcase
  end
  always@(setBoundsALU_boundsOp or setBoundsALU_cap)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1: x__h10131 = setBoundsALU_cap[64:57];
      default: x__h10131 = 8'd0;
    endcase
  end
  always@(setBoundsALU_boundsOp or setBoundsALU_cap)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1: x__h10142 = setBoundsALU_cap[56:49];
      default: x__h10142 = 8'd0;
    endcase
  end
  always@(setBoundsALU_boundsOp or repBound__h10345)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1: res_tempFields_repBoundTopBits__h10389 = repBound__h10345;
      default: res_tempFields_repBoundTopBits__h10389 = 3'd7;
    endcase
  end
  always@(setBoundsALU_boundsOp or setBoundsALU_cap)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1:
	  CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q2 =
	      setBoundsALU_cap[48:45];
      default: CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q2 = 4'd15;
    endcase
  end
  always@(setBoundsALU_boundsOp or
	  IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d464 or
	  IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d485)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1:
	  CASE_setBoundsALU_boundsOp_0_IF_setBoundsALU_l_ETC__q3 =
	      { IF_setBoundsALU_len_AND_1023_CONCAT_INV_setBou_ETC___d464,
		IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT_set_ETC___d485 };
      default: CASE_setBoundsALU_boundsOp_0_IF_setBoundsALU_l_ETC__q3 =
		   34'h344000000;
    endcase
  end
  always@(setBoundsALU_boundsOp or x__h9616 or setBoundsALU_cap or x__h9550)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1:
	  CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q4 =
	      setBoundsALU_cap[159:96];
      2'd2:
	  CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q4 =
	      x__h9550[63:0];
      2'd3:
	  CASE_setBoundsALU_boundsOp_0_setBoundsALU_cap__ETC__q4 =
	      x__h9616[63:0];
    endcase
  end
  always@(setBoundsALU_boundsOp or
	  res_addrBits__h9258 or
	  result_cap_addrBits__h9233 or res_addrBits__h9246)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1:
	  CASE_setBoundsALU_boundsOp_0_result_cap_addrBi_ETC__q5 =
	      result_cap_addrBits__h9233;
      2'd2:
	  CASE_setBoundsALU_boundsOp_0_result_cap_addrBi_ETC__q5 =
	      res_addrBits__h9246;
      2'd3:
	  CASE_setBoundsALU_boundsOp_0_result_cap_addrBi_ETC__q5 =
	      res_addrBits__h9258;
    endcase
  end
  always@(setBoundsALU_boundsOp or
	  IF_IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT__ETC___d516)
  begin
    case (setBoundsALU_boundsOp)
      2'd0, 2'd1:
	  CASE_setBoundsALU_boundsOp_0_IF_IF_NOT_setBoun_ETC__q6 =
	      IF_IF_NOT_setBoundsALU_len_BIT_63_6_7_AND_NOT__ETC___d516;
      default: CASE_setBoundsALU_boundsOp_0_IF_IF_NOT_setBoun_ETC__q6 = 4'd0;
    endcase
  end
endmodule  // module_setBoundsALU

