//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:19:21 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// decodeBrPred                   O   130
// decodeBrPred_pc                I   129
// decodeBrPred_dInst             I   137
// decodeBrPred_histTaken         I     1
// decodeBrPred_is_32b_inst       I     1
//
// Combinational paths from inputs to outputs:
//   (decodeBrPred_pc,
//    decodeBrPred_dInst,
//    decodeBrPred_histTaken,
//    decodeBrPred_is_32b_inst) -> decodeBrPred
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_decodeBrPred(decodeBrPred_pc,
			   decodeBrPred_dInst,
			   decodeBrPred_histTaken,
			   decodeBrPred_is_32b_inst,
			   decodeBrPred);
  // value method decodeBrPred
  input  [128 : 0] decodeBrPred_pc;
  input  [136 : 0] decodeBrPred_dInst;
  input  decodeBrPred_histTaken;
  input  decodeBrPred_is_32b_inst;
  output [129 : 0] decodeBrPred;

  // signals for module outputs
  wire [129 : 0] decodeBrPred;

  // remaining internal signals
  reg [128 : 0] CASE_decodeBrPred_dInst_BITS_136_TO_132_8_jTar_ETC__q4;
  wire [128 : 0] jTarget__h28, pcPlusN__h24;
  wire [63 : 0] IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20,
		address__h1676,
		thin_address__h121,
		x__h1131,
		x__h1198;
  wire [49 : 0] highBitsfilter__h186,
		highOffsetBits__h187,
		signBits__h184,
		x__h214;
  wire [31 : 0] decodeBrPred_dInst_BITS_31_TO_0__q2;
  wire [25 : 0] IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83;
  wire [13 : 0] b_base__h1176,
		cr_addrBits__h361,
		repBoundBits__h193,
		toBoundsM1__h197,
		toBounds__h196,
		x__h1169;
  wire [11 : 0] IF_INV_decodeBrPred_pc_BITS_94_TO_90_BIT_0_THE_ETC__q3,
		b_top__h1175,
		inc__h1626;
  wire [5 : 0] IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37;
  wire [4 : 0] INV_decodeBrPred_pc_BITS_94_TO_90__q1;
  wire [2 : 0] b_expBotHalf__h616, b_expTopHalf__h614, repBound__h1162;
  wire IF_IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_ETC___d64,
       IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d70;

  // value method decodeBrPred
  assign decodeBrPred =
	     { decodeBrPred_dInst[136:132] != 5'd9 &&
	       decodeBrPred_dInst[136:132] != 5'd11 &&
	       decodeBrPred_dInst[136:132] != 5'd13,
	       CASE_decodeBrPred_dInst_BITS_136_TO_132_8_jTar_ETC__q4 } ;

  // remaining internal signals
  assign IF_IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_ETC___d64 =
	     IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20[63] ?
	       x__h1131[13:0] >= toBounds__h196 &&
	       repBoundBits__h193 != cr_addrBits__h361 :
	       x__h1131[13:0] < toBoundsM1__h197 ;
  assign IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37 =
	     INV_decodeBrPred_pc_BITS_94_TO_90__q1[0] ?
	       { b_expTopHalf__h614, b_expBotHalf__h616 } :
	       6'd0 ;
  assign IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83 =
	     INV_decodeBrPred_pc_BITS_94_TO_90__q1[0] ?
	       { IF_INV_decodeBrPred_pc_BITS_94_TO_90_BIT_0_THE_ETC__q3[11:3],
		 IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37[5:3],
		 x__h1169[13:3],
		 IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37[2:0] } :
	       { b_top__h1175, b_base__h1176 } ;
  assign IF_INV_decodeBrPred_pc_BITS_94_TO_90_BIT_0_THE_ETC__q3 =
	     INV_decodeBrPred_pc_BITS_94_TO_90__q1[0] ?
	       { decodeBrPred_pc[89:81], 3'd0 } :
	       b_top__h1175 ;
  assign IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20 =
	     { {32{decodeBrPred_dInst_BITS_31_TO_0__q2[31]}},
	       decodeBrPred_dInst_BITS_31_TO_0__q2 } ;
  assign IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d70 =
	     (highOffsetBits__h187 == 50'd0 &&
	      IF_IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_ETC___d64 ||
	      IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37 >=
	      6'd50) &&
	     decodeBrPred_pc[128] ;
  assign INV_decodeBrPred_pc_BITS_94_TO_90__q1 = ~decodeBrPred_pc[94:90] ;
  assign address__h1676 =
	     decodeBrPred_pc[63:0] + { {52{inc__h1626[11]}}, inc__h1626 } ;
  assign b_base__h1176 =
	     { decodeBrPred_pc[77:67],
	       ~decodeBrPred_pc[66],
	       decodeBrPred_pc[65:64] } ;
  assign b_expBotHalf__h616 =
	     { ~decodeBrPred_pc[66], decodeBrPred_pc[65:64] } ;
  assign b_expTopHalf__h614 =
	     { ~decodeBrPred_pc[80:79], decodeBrPred_pc[78] } ;
  assign b_top__h1175 =
	     { decodeBrPred_pc[89:81],
	       ~decodeBrPred_pc[80:79],
	       decodeBrPred_pc[78] } ;
  assign cr_addrBits__h361 =
	     INV_decodeBrPred_pc_BITS_94_TO_90__q1[0] ?
	       x__h1198[13:0] :
	       decodeBrPred_pc[13:0] ;
  assign decodeBrPred_dInst_BITS_31_TO_0__q2 = decodeBrPred_dInst[31:0] ;
  assign highBitsfilter__h186 =
	     50'h3FFFFFFFFFFFF <<
	     IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37 ;
  assign highOffsetBits__h187 = x__h214 & highBitsfilter__h186 ;
  assign inc__h1626 = decodeBrPred_is_32b_inst ? 12'd4 : 12'd2 ;
  assign jTarget__h28 =
	     { IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d70,
	       decodeBrPred_pc[127:90],
	       IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83[25:17],
	       ~IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83[16:15],
	       IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83[14:3],
	       ~IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83[2],
	       IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d83[1:0],
	       thin_address__h121 } ;
  assign pcPlusN__h24 = { decodeBrPred_pc[128:64], address__h1676 } ;
  assign repBoundBits__h193 = { repBound__h1162, 11'd0 } ;
  assign repBound__h1162 = x__h1169[13:11] - 3'b001 ;
  assign signBits__h184 =
	     {50{IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20[63]}} ;
  assign thin_address__h121 =
	     decodeBrPred_pc[63:0] +
	     IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20 ;
  assign toBoundsM1__h197 = repBoundBits__h193 + ~cr_addrBits__h361 ;
  assign toBounds__h196 = repBoundBits__h193 - cr_addrBits__h361 ;
  assign x__h1131 =
	     IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20 >>
	     IF_INV_decodeBrPred_pc_BITS_94_TO_90_5_6_BIT_0_ETC___d37 ;
  assign x__h1169 =
	     INV_decodeBrPred_pc_BITS_94_TO_90__q1[0] ?
	       { decodeBrPred_pc[77:67], 3'd0 } :
	       b_base__h1176 ;
  assign x__h1198 =
	     decodeBrPred_pc[63:0] >>
	     { b_expTopHalf__h614, b_expBotHalf__h616 } ;
  assign x__h214 =
	     IF_decodeBrPred_dInst_BIT_32_6_THEN_SEXT_IF_de_ETC___d20[63:14] ^
	     signBits__h184 ;
  always@(decodeBrPred_dInst or
	  pcPlusN__h24 or jTarget__h28 or decodeBrPred_histTaken)
  begin
    case (decodeBrPred_dInst[136:132])
      5'd8, 5'd12:
	  CASE_decodeBrPred_dInst_BITS_136_TO_132_8_jTar_ETC__q4 =
	      jTarget__h28;
      5'd10:
	  CASE_decodeBrPred_dInst_BITS_136_TO_132_8_jTar_ETC__q4 =
	      decodeBrPred_histTaken ? jTarget__h28 : pcPlusN__h24;
      default: CASE_decodeBrPred_dInst_BITS_136_TO_132_8_jTar_ETC__q4 =
		   pcPlusN__h24;
    endcase
  end
endmodule  // module_decodeBrPred

