//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:17:25 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// specialRWALU                   O   161
// specialRWALU_cap               I   161
// specialRWALU_oldCap            I   161
// specialRWALU_scrType           I     5
//
// Combinational paths from inputs to outputs:
//   (specialRWALU_cap,
//    specialRWALU_oldCap,
//    specialRWALU_scrType) -> specialRWALU
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_specialRWALU(specialRWALU_cap,
			   specialRWALU_oldCap,
			   specialRWALU_scrType,
			   specialRWALU);
  // value method specialRWALU
  input  [160 : 0] specialRWALU_cap;
  input  [160 : 0] specialRWALU_oldCap;
  input  [4 : 0] specialRWALU_scrType;
  output [160 : 0] specialRWALU;

  // signals for module outputs
  wire [160 : 0] specialRWALU;

  // remaining internal signals
  reg [71 : 0] CASE_specialRWALU_scrType_BITS_4_TO_2_0_specia_ETC__q5;
  reg [63 : 0] IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15,
	       res_capFat_address__h2781;
  reg [13 : 0] res_capFat_addrBits__h2782;
  reg [9 : 0] IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197;
  reg [4 : 0] CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q2;
  reg [2 : 0] CASE_specialRWALU_scrType_BITS_4_TO_2_2_repBou_ETC__q3;
  reg CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q1,
      CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q4,
      IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104;
  wire [149 : 0] IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125;
  wire [63 : 0] new_csr__h1263,
		new_csr__h2155,
		new_csr__h78,
		x__h1303,
		x__h168,
		x__h1766,
		x__h2195,
		y__h1556;
  wire [49 : 0] deltaAddrHi__h1276,
		deltaAddrHi__h141,
		deltaAddrHi__h1739,
		deltaAddrHi__h2168,
		deltaAddrUpper__h1278,
		deltaAddrUpper__h143,
		mask__h1277,
		specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34;
  wire [9 : 0] IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d195;
  wire [5 : 0] IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d194;
  wire [4 : 0] specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d190,
	       specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d179;
  wire [3 : 0] IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d141,
	       IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d154;
  wire [2 : 0] repBound__h3307, repBound__h3329;
  wire [1 : 0] x__h1284, x__h149, x__h1747, x__h2176;
  wire IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131,
       IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144,
       specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180,
       specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169,
       specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166,
       specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163,
       specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130,
       specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129;

  // value method specialRWALU
  assign specialRWALU =
	     { IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104,
	       IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125,
	       IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 } ;

  // remaining internal signals
  assign IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131 =
	     x__h168[13:11] < repBound__h3307 ;
  assign IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144 =
	     x__h1303[13:11] < repBound__h3307 ;
  assign IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d141 =
	     { (specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 ==
		IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131) ?
		 2'd0 :
		 ((specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 &&
		   !IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131) ?
		    2'd1 :
		    2'd3),
	       (specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 ==
		IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131) ?
		 2'd0 :
		 ((specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 &&
		   !IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d154 =
	     { (specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 ==
		IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144) ?
		 2'd0 :
		 ((specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 &&
		   !IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144) ?
		    2'd1 :
		    2'd3),
	       (specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 ==
		IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144) ?
		 2'd0 :
		 ((specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 &&
		   !IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d125 =
	     { res_capFat_address__h2781,
	       res_capFat_addrBits__h2782,
	       CASE_specialRWALU_scrType_BITS_4_TO_2_0_specia_ETC__q5 } ;
  assign IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d194 =
	     { CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q1,
	       CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q2 } ;
  assign IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d195 =
	     { CASE_specialRWALU_scrType_BITS_4_TO_2_2_repBou_ETC__q3,
	       CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q4,
	       IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d194 } ;
  assign deltaAddrHi__h1276 =
	     { {48{x__h1284[1]}}, x__h1284 } << specialRWALU_oldCap[43:38] ;
  assign deltaAddrHi__h141 =
	     { {48{x__h149[1]}}, x__h149 } << specialRWALU_oldCap[43:38] ;
  assign deltaAddrHi__h1739 =
	     { {48{x__h1747[1]}}, x__h1747 } << specialRWALU_cap[43:38] ;
  assign deltaAddrHi__h2168 =
	     { {48{x__h2176[1]}}, x__h2176 } << specialRWALU_cap[43:38] ;
  assign deltaAddrUpper__h1278 =
	     (IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15[63:14] &
	      mask__h1277) -
	     specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34 ;
  assign deltaAddrUpper__h143 =
	     (IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15[63:14] &
	      mask__h1277) -
	     specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34 ;
  assign mask__h1277 = 50'h3FFFFFFFFFFFF << specialRWALU_oldCap[43:38] ;
  assign new_csr__h1263 =
	     { IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15[63:1],
	       1'd0 } ;
  assign new_csr__h2155 = { specialRWALU_cap[159:97], 1'd0 } ;
  assign new_csr__h78 =
	     { IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15[63:2],
	       1'd0,
	       IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15[0] } ;
  assign repBound__h3307 = specialRWALU_oldCap[23:21] - 3'b001 ;
  assign repBound__h3329 = specialRWALU_cap[23:21] - 3'b001 ;
  assign specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180 =
	     x__h2195[13:11] < repBound__h3329 ;
  assign specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d190 =
	     { specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180,
	       (specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 ==
		specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180) ?
		 2'd0 :
		 ((specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 &&
		   !specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180) ?
		    2'd1 :
		    2'd3),
	       (specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 ==
		specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180) ?
		 2'd0 :
		 ((specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 &&
		   !specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d180) ?
		    2'd1 :
		    2'd3) } ;
  assign specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169 =
	     x__h1766[13:11] < repBound__h3329 ;
  assign specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d179 =
	     { specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169,
	       (specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 ==
		specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169) ?
		 2'd0 :
		 ((specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 &&
		   !specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169) ?
		    2'd1 :
		    2'd3),
	       (specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 ==
		specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169) ?
		 2'd0 :
		 ((specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 &&
		   !specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d169) ?
		    2'd1 :
		    2'd3) } ;
  assign specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166 =
	     specialRWALU_cap[23:21] < repBound__h3329 ;
  assign specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163 =
	     specialRWALU_cap[37:35] < repBound__h3329 ;
  assign specialRWALU_oldCap_BITS_159_TO_110_3_AND_1125_ETC___d34 =
	     specialRWALU_oldCap[159:110] & mask__h1277 ;
  assign specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 =
	     specialRWALU_oldCap[23:21] < repBound__h3307 ;
  assign specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 =
	     specialRWALU_oldCap[37:35] < repBound__h3307 ;
  assign x__h1284 =
	     { 1'b0, x__h1303[13:11] < specialRWALU_oldCap[9:7] } -
	     { 1'b0, specialRWALU_oldCap[4] } ;
  assign x__h1303 = new_csr__h1263 >> specialRWALU_oldCap[43:38] ;
  assign x__h149 =
	     { 1'b0, x__h168[13:11] < specialRWALU_oldCap[9:7] } -
	     { 1'b0, specialRWALU_oldCap[4] } ;
  assign x__h168 = new_csr__h78 >> specialRWALU_oldCap[43:38] ;
  assign x__h1747 =
	     { 1'b0, x__h1766[13:11] < specialRWALU_cap[9:7] } -
	     { 1'b0, specialRWALU_cap[4] } ;
  assign x__h1766 =
	     { specialRWALU_cap[159:98], 1'd0, specialRWALU_cap[96] } >>
	     specialRWALU_cap[43:38] ;
  assign x__h2176 =
	     { 1'b0, x__h2195[13:11] < specialRWALU_cap[9:7] } -
	     { 1'b0, specialRWALU_cap[4] } ;
  assign x__h2195 = new_csr__h2155 >> specialRWALU_cap[43:38] ;
  assign y__h1556 = ~specialRWALU_cap[159:96] ;
  always@(specialRWALU_scrType or
	  specialRWALU_oldCap or y__h1556 or specialRWALU_cap)
  begin
    case (specialRWALU_scrType[1:0])
      2'd0:
	  IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 =
	      specialRWALU_cap[159:96];
      2'd1:
	  IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 =
	      specialRWALU_oldCap[159:96] | specialRWALU_cap[159:96];
      default: IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d15 =
		   specialRWALU_oldCap[159:96] & y__h1556;
    endcase
  end
  always@(specialRWALU_scrType or
	  specialRWALU_cap or
	  new_csr__h78 or new_csr__h1263 or new_csr__h2155)
  begin
    case (specialRWALU_scrType[4:2])
      3'd0: res_capFat_address__h2781 = new_csr__h78;
      3'd1: res_capFat_address__h2781 = new_csr__h1263;
      3'd2:
	  res_capFat_address__h2781 =
	      { specialRWALU_cap[159:98], 1'd0, specialRWALU_cap[96] };
      3'd3: res_capFat_address__h2781 = new_csr__h2155;
      default: res_capFat_address__h2781 = specialRWALU_cap[159:96];
    endcase
  end
  always@(specialRWALU_scrType or
	  specialRWALU_cap or x__h168 or x__h1303 or x__h1766 or x__h2195)
  begin
    case (specialRWALU_scrType[4:2])
      3'd0: res_capFat_addrBits__h2782 = x__h168[13:0];
      3'd1: res_capFat_addrBits__h2782 = x__h1303[13:0];
      3'd2: res_capFat_addrBits__h2782 = x__h1766[13:0];
      3'd3: res_capFat_addrBits__h2782 = x__h2195[13:0];
      default: res_capFat_addrBits__h2782 = specialRWALU_cap[95:82];
    endcase
  end
  always@(specialRWALU_scrType or
	  specialRWALU_cap or
	  specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166)
  begin
    case (specialRWALU_scrType[4:2])
      3'd2, 3'd3:
	  CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q1 =
	      specialRWALU_cap_BITS_23_TO_21_58_ULT_specialR_ETC___d166;
      default: CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q1 =
		   specialRWALU_cap[5];
    endcase
  end
  always@(specialRWALU_scrType or
	  specialRWALU_cap or
	  specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d179 or
	  specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d190)
  begin
    case (specialRWALU_scrType[4:2])
      3'd2:
	  CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q2 =
	      specialRWALU_cap_BITS_159_TO_98_6_CONCAT_0_CON_ETC___d179;
      3'd3:
	  CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q2 =
	      specialRWALU_cap_BITS_159_TO_97_7_CONCAT_0_8_S_ETC___d190;
      default: CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q2 =
		   specialRWALU_cap[4:0];
    endcase
  end
  always@(specialRWALU_scrType or specialRWALU_cap or repBound__h3329)
  begin
    case (specialRWALU_scrType[4:2])
      3'd2, 3'd3:
	  CASE_specialRWALU_scrType_BITS_4_TO_2_2_repBou_ETC__q3 =
	      repBound__h3329;
      default: CASE_specialRWALU_scrType_BITS_4_TO_2_2_repBou_ETC__q3 =
		   specialRWALU_cap[9:7];
    endcase
  end
  always@(specialRWALU_scrType or
	  specialRWALU_cap or
	  specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163)
  begin
    case (specialRWALU_scrType[4:2])
      3'd2, 3'd3:
	  CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q4 =
	      specialRWALU_cap_BITS_37_TO_35_62_ULT_specialR_ETC___d163;
      default: CASE_specialRWALU_scrType_BITS_4_TO_2_2_specia_ETC__q4 =
		   specialRWALU_cap[6];
    endcase
  end
  always@(specialRWALU_scrType or
	  specialRWALU_cap or
	  deltaAddrHi__h141 or
	  deltaAddrUpper__h143 or
	  specialRWALU_oldCap or
	  deltaAddrHi__h1276 or
	  deltaAddrUpper__h1278 or deltaAddrHi__h1739 or deltaAddrHi__h2168)
  begin
    case (specialRWALU_scrType[4:2])
      3'd0:
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 =
	      deltaAddrHi__h141 == deltaAddrUpper__h143 &&
	      specialRWALU_oldCap[48:45] == 4'd15 &&
	      specialRWALU_oldCap[160];
      3'd1:
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 =
	      deltaAddrHi__h1276 == deltaAddrUpper__h1278 &&
	      specialRWALU_oldCap[48:45] == 4'd15 &&
	      specialRWALU_oldCap[160];
      3'd2:
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 =
	      deltaAddrHi__h1739 == 50'd0 &&
	      specialRWALU_cap[48:45] == 4'd15 &&
	      specialRWALU_cap[160];
      3'd3:
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 =
	      deltaAddrHi__h2168 == 50'd0 &&
	      (specialRWALU_cap[48:45] == 4'd15 || !specialRWALU_cap[96]) &&
	      specialRWALU_cap[160];
      default: IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d104 =
		   specialRWALU_cap[160];
    endcase
  end
  always@(specialRWALU_scrType or specialRWALU_cap or specialRWALU_oldCap)
  begin
    case (specialRWALU_scrType[4:2])
      3'd0, 3'd1:
	  CASE_specialRWALU_scrType_BITS_4_TO_2_0_specia_ETC__q5 =
	      specialRWALU_oldCap[81:10];
      default: CASE_specialRWALU_scrType_BITS_4_TO_2_0_specia_ETC__q5 =
		   specialRWALU_cap[81:10];
    endcase
  end
  always@(specialRWALU_scrType or
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d195 or
	  repBound__h3307 or
	  specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129 or
	  specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130 or
	  IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131 or
	  IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d141 or
	  IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144 or
	  IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d154)
  begin
    case (specialRWALU_scrType[4:2])
      3'd0:
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 =
	      { repBound__h3307,
		specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129,
		specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130,
		IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_TH_ETC___d131,
		IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d141 };
      3'd1:
	  IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 =
	      { repBound__h3307,
		specialRWALU_oldCap_BITS_37_TO_35_28_ULT_speci_ETC___d129,
		specialRWALU_oldCap_BITS_23_TO_21_26_ULT_speci_ETC___d130,
		IF_IF_specialRWALU_scrType_BITS_4_TO_2_EQ_1_2__ETC___d144,
		IF_specialRWALU_oldCap_BITS_37_TO_35_28_ULT_sp_ETC___d154 };
      default: IF_specialRWALU_scrType_BITS_4_TO_2_EQ_0_THEN__ETC___d197 =
		   IF_specialRWALU_scrType_BITS_4_TO_2_EQ_2_5_OR__ETC___d195;
    endcase
  end
endmodule  // module_specialRWALU

