//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:17:26 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// capModify                      O   161
// capModify_a                    I   161
// capModify_b                    I   161
// capModify_func                 I    10
//
// Combinational paths from inputs to outputs:
//   (capModify_a, capModify_b, capModify_func) -> capModify
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_capModify(capModify_a,
			capModify_b,
			capModify_func,
			capModify);
  // value method capModify
  input  [160 : 0] capModify_a;
  input  [160 : 0] capModify_b;
  input  [9 : 0] capModify_func;
  output [160 : 0] capModify;

  // signals for module outputs
  reg [160 : 0] capModify;

  // remaining internal signals
  reg [63 : 0] CASE_capModify_func_BITS_9_TO_5_4_capModify_a__ETC__q12,
	       a_type__h25;
  reg [34 : 0] IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677;
  reg [33 : 0] CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q11;
  reg [13 : 0] CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q6,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453;
  reg [9 : 0] IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729;
  reg [7 : 0] CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q8,
	      CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q9,
	      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620,
	      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632;
  reg [3 : 0] CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q10,
	      CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q14,
	      CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q7,
	      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467,
	      IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647;
  reg [2 : 0] CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q13;
  reg [1 : 0] mask__h2702;
  reg IF_capModify_func_BITS_9_TO_5_EQ_11_08_OR_capM_ETC___d406,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608,
      IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413;
  wire [160 : 0] capModify_func_BITS_4_TO_2_9_EQ_2_00_OR_capMod_ETC___d185,
		 setBoundsALU___d97;
  wire [149 : 0] IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d681,
		 capModify_b_BITS_159_TO_96_1_CONCAT_IF_capModi_ETC___d171;
  wire [64 : 0] IF_capModify_a_BITS_43_TO_38_ULT_51_45_AND_NOT_ETC___d372,
		IF_capModify_b_BITS_43_TO_38_96_ULT_51_73_AND__ETC___d400,
		addTop__h6259,
		addTop__h6853,
		result__h6795,
		result__h7390,
		ret__h6261,
		ret__h6855;
  wire [63 : 0] a__h4126,
		a_capFat_address__h4862,
		addBase__h6086,
		addBase__h6170,
		address__h3899,
		capModify_a_BITS_159_TO_110_0_AND_112589990684_ETC___d58,
		cap_address__h5443,
		pointer__h1810,
		result_d_address__h2718,
		ret___1_address__h3519,
		x__h2620,
		x__h2849,
		x__h3939,
		x__h8069,
		x__h8169;
  wire [50 : 0] mask__h6260, mask__h6854;
  wire [49 : 0] capModify_a_BITS_159_TO_110_PLUS_SEXT_capModif_ETC__q3,
		capModify_b_BITS_159_TO_110_AND_11258999068426_ETC___d208,
		capModify_b_BITS_159_TO_110_PLUS_SEXT_capModif_ETC__q5,
		deltaAddrHi__h2822,
		deltaAddrHi__h3912,
		deltaAddrUpper__h2824,
		deltaAddrUpper__h3914,
		highOffsetBits__h1817,
		mask__h6171,
		mask__h7509,
		signBits__h1814,
		x__h1844;
  wire [34 : 0] INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_34_ETC___d672;
  wire [30 : 0] _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456;
  wire [15 : 0] x__h6137, x__h6221, x__h6319, x__h6913;
  wire [13 : 0] a_capFat_addrBits__h4863,
		b_baseBits__h11018,
		b_base__h11288,
		b_topBits__h11017,
		newAddrBits__h2701,
		repBoundBits__h1823,
		res_addrBits__h2757,
		res_addrBits__h3210,
		result_d_addrBits__h2719,
		toBoundsM1_A__h1822,
		toBoundsM1_B__h1825,
		toBoundsM1__h1827,
		toBounds_A__h1821,
		toBounds_B__h1824,
		toBounds__h1826;
  wire [11 : 0] b_top__h11287, topBits__h10928;
  wire [9 : 0] IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_THEN_7_ETC___d703;
  wire [7 : 0] a_capFat_mte__h4867, a_capFat_tloc__h4868;
  wire [5 : 0] x__h8207;
  wire [4 : 0] IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d241,
	       IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d89,
	       INV_capModify_b_BITS_126_TO_122__q1;
  wire [3 : 0] IF_IF_INV_capModify_b_BITS_126_TO_122_32_33_BI_ETC___d721,
	       a_capFat_perms_soft__h8272,
	       thin_otype__h5675;
  wire [2 : 0] repBound__h11411,
	       repBound__h11496,
	       repBound__h11507,
	       tb__h11504,
	       tmp_expBotHalf__h8162,
	       tmp_expTopHalf__h8160;
  wire [1 : 0] IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_OR_cap_ETC___d695,
	       IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_OR_cap_ETC___d700,
	       capModify_a_BITS_1_TO_0__q2,
	       capModify_b_BITS_1_TO_0__q4,
	       carry_out__h10930,
	       impliedTopBits__h10932,
	       len_correction__h10931,
	       x__h11278,
	       x__h2830,
	       x__h3920;
  wire IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d708,
       IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d709,
       IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711,
       IF_NOT_capModify_b_BIT_160_05_66_OR_NOT_capMod_ETC___d277,
       IF_capModify_b_BIT_159_THEN_NOT_capModify_b_BI_ETC___d38,
       IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d255,
       IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d273,
       IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231,
       IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79,
       IF_capModify_func_BIT_0_4_THEN_capModify_b_BIT_ETC___d287,
       NOT_capModify_b_BITS_159_TO_96_1_SRL_capModify_ETC___d29,
       NOT_capModify_b_BIT_160_05_66_OR_NOT_capModify_ETC___d275,
       SEXT__0b0_CONCAT_IF_capModify_func_BIT_0_4_THE_ETC___d222,
       a_capFat_flags__h4865,
       capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688,
       capModify_a_BITS_23_TO_21_3_ULT_capModify_a_BI_ETC___d77,
       capModify_a_BITS_37_TO_35_5_ULT_capModify_a_BI_ETC___d76,
       capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230,
       capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229,
       capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d248,
       capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d252,
       capModify_b_BIT_160_05_AND_capModify_b_BITS_48_ETC___d344,
       capModify_b_BIT_5_77_EQ_capModify_b_BIT_4_79___d250,
       capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_79___d246,
       capModify_func_BIT_0_4_OR_capModify_b_BIT_160__ETC___d286;

  // value method capModify
  always@(capModify_func or
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 or
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d681 or
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 or
	  highOffsetBits__h1817 or
	  IF_capModify_b_BIT_159_THEN_NOT_capModify_b_BI_ETC___d38 or
	  capModify_a or
	  result_d_address__h2718 or
	  result_d_addrBits__h2719 or
	  repBound__h11411 or
	  capModify_a_BITS_37_TO_35_5_ULT_capModify_a_BI_ETC___d76 or
	  capModify_a_BITS_23_TO_21_3_ULT_capModify_a_BI_ETC___d77 or
	  IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d89 or
	  setBoundsALU___d97 or
	  capModify_func_BITS_4_TO_2_9_EQ_2_00_OR_capMod_ETC___d185 or
	  SEXT__0b0_CONCAT_IF_capModify_func_BIT_0_4_THE_ETC___d222 or
	  address__h3899 or
	  x__h3939 or
	  capModify_b or
	  repBound__h11496 or
	  capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229 or
	  capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230 or
	  IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d241)
  begin
    case (capModify_func[9:5])
      5'd0:
	  capModify =
	      { (highOffsetBits__h1817 == 50'd0 &&
		 IF_capModify_b_BIT_159_THEN_NOT_capModify_b_BI_ETC___d38 ||
		 capModify_a[43:38] >= 6'd50) &&
		capModify_a[160] &&
		capModify_a[48:45] == 4'd15,
		result_d_address__h2718,
		result_d_addrBits__h2719,
		capModify_a[81:10],
		repBound__h11411,
		capModify_a_BITS_37_TO_35_5_ULT_capModify_a_BI_ETC___d76,
		capModify_a_BITS_23_TO_21_3_ULT_capModify_a_BI_ETC___d77,
		IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d89 };
      5'd1: capModify = setBoundsALU___d97;
      5'd2:
	  capModify =
	      capModify_func_BITS_4_TO_2_9_EQ_2_00_OR_capMod_ETC___d185;
      5'd3:
	  capModify =
	      { SEXT__0b0_CONCAT_IF_capModify_func_BIT_0_4_THE_ETC___d222,
		address__h3899,
		x__h3939[13:0],
		capModify_b[81:10],
		repBound__h11496,
		capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229,
		capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230,
		IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d241 };
      default: capModify =
		   { IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413,
		     IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d681,
		     IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 };
    endcase
  end

  // remaining internal signals
  module_setBoundsALU instance_setBoundsALU_0(.setBoundsALU_cap({ capModify_a[160] &&
								  thin_otype__h5675 ==
								  4'd15,
								  capModify_a[159:0] }),
					      .setBoundsALU_len(cap_address__h5443),
					      .setBoundsALU_boundsOp(capModify_func[1:0]),
					      .setBoundsALU(setBoundsALU___d97));
  assign IF_IF_INV_capModify_b_BITS_126_TO_122_32_33_BI_ETC___d721 =
	     { (IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d708 ==
		IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711) ?
		 2'd0 :
		 ((IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d708 &&
		   !IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711) ?
		    2'd1 :
		    2'd3),
	       (IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d709 ==
		IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711) ?
		 2'd0 :
		 ((IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d709 &&
		   !IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d708 =
	     tb__h11504 < repBound__h11507 ;
  assign IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d709 =
	     b_baseBits__h11018[13:11] < repBound__h11507 ;
  assign IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711 =
	     res_addrBits__h3210[13:11] < repBound__h11507 ;
  assign IF_NOT_capModify_b_BIT_160_05_66_OR_NOT_capMod_ETC___d277 =
	     NOT_capModify_b_BIT_160_05_66_OR_NOT_capModify_ETC___d275 ?
	       capModify_a[160] :
	       capModify_a[160] && capModify_b[48:45] == 4'd15 &&
	       capModify_b[73] &&
	       capModify_b[159:96] <= 64'd11 ;
  assign IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_OR_cap_ETC___d695 =
	     (capModify_a[159:96] == 64'd0 ||
	      capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229 ==
	      capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688) ?
	       2'd0 :
	       ((capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229 &&
		 !capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688) ?
		  2'd1 :
		  2'd3) ;
  assign IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_OR_cap_ETC___d700 =
	     (capModify_a[159:96] == 64'd0 ||
	      capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230 ==
	      capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688) ?
	       2'd0 :
	       ((capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230 &&
		 !capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688) ?
		  2'd1 :
		  2'd3) ;
  assign IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_THEN_7_ETC___d703 =
	     { (capModify_a[159:96] == 64'd0) ? 3'd7 : repBound__h11496,
	       capModify_a[159:96] == 64'd0 ||
	       capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229,
	       capModify_a[159:96] == 64'd0 ||
	       capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230,
	       capModify_a[159:96] == 64'd0 ||
	       capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688,
	       IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_OR_cap_ETC___d695,
	       IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_OR_cap_ETC___d700 } ;
  assign IF_capModify_a_BITS_43_TO_38_ULT_51_45_AND_NOT_ETC___d372 =
	     (capModify_a[43:38] < 6'd51 &&
	      ret__h6261[64:63] -
	      { 1'b0,
		(capModify_a[43:38] == 6'd50) ?
		  capModify_a[23] :
		  capModify_a_BITS_159_TO_110_PLUS_SEXT_capModif_ETC__q3[49] } >
	      2'd1) ?
	       result__h6795 :
	       ret__h6261 ;
  assign IF_capModify_b_BITS_43_TO_38_96_ULT_51_73_AND__ETC___d400 =
	     (capModify_b[43:38] < 6'd51 &&
	      ret__h6855[64:63] -
	      { 1'b0,
		(capModify_b[43:38] == 6'd50) ?
		  capModify_b[23] :
		  capModify_b_BITS_159_TO_110_PLUS_SEXT_capModif_ETC__q5[49] } >
	      2'd1) ?
	       result__h7390 :
	       ret__h6855 ;
  assign IF_capModify_b_BIT_159_THEN_NOT_capModify_b_BI_ETC___d38 =
	     capModify_b[159] ?
	       NOT_capModify_b_BITS_159_TO_96_1_SRL_capModify_ETC___d29 :
	       (capModify_func[0] ?
		  x__h2620[13:0] < toBoundsM1__h1827 :
		  x__h2620[13:0] <= toBoundsM1__h1827) ;
  assign IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d255 =
	     (capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_79___d246 ?
		capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d248 :
		capModify_b[6]) &&
	     (capModify_b_BIT_5_77_EQ_capModify_b_BIT_4_79___d250 ?
		!capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d252 :
		capModify_b[4]) ;
  assign IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d273 =
	     (capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_79___d246 ?
		!capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d248 :
		!capModify_b[6]) ||
	     (capModify_b_BIT_5_77_EQ_capModify_b_BIT_4_79___d250 ?
		capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d252 :
		!capModify_b[4]) ;
  assign IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d681 =
	     { CASE_capModify_func_BITS_9_TO_5_4_capModify_a__ETC__q12,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647,
	       IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677 } ;
  assign IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231 =
	     x__h3939[13:11] < repBound__h11496 ;
  assign IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d241 =
	     { IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231,
	       (capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229 ==
		IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231) ?
		 2'd0 :
		 ((capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229 &&
		   !IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231) ?
		    2'd1 :
		    2'd3),
	       (capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230 ==
		IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231) ?
		 2'd0 :
		 ((capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230 &&
		   !IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d231) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79 =
	     result_d_addrBits__h2719[13:11] < repBound__h11411 ;
  assign IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d89 =
	     { IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79,
	       (capModify_a_BITS_37_TO_35_5_ULT_capModify_a_BI_ETC___d76 ==
		IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79) ?
		 2'd0 :
		 ((capModify_a_BITS_37_TO_35_5_ULT_capModify_a_BI_ETC___d76 &&
		   !IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79) ?
		    2'd1 :
		    2'd3),
	       (capModify_a_BITS_23_TO_21_3_ULT_capModify_a_BI_ETC___d77 ==
		IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79) ?
		 2'd0 :
		 ((capModify_a_BITS_23_TO_21_3_ULT_capModify_a_BI_ETC___d77 &&
		   !IF_capModify_func_BIT_0_4_THEN_capModify_a_BIT_ETC___d79) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_capModify_func_BIT_0_4_THEN_capModify_b_BIT_ETC___d287 =
	     (capModify_func[0] ? capModify_b[160] : capModify_a[160]) &&
	     capModify_func_BIT_0_4_OR_capModify_b_BIT_160__ETC___d286 ;
  assign INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_34_ETC___d672 =
	     { INV_capModify_b_BITS_126_TO_122__q1[0],
	       INV_capModify_b_BITS_126_TO_122__q1[0] ? x__h8207 : 6'd0,
	       b_topBits__h11017,
	       b_baseBits__h11018 } ;
  assign INV_capModify_b_BITS_126_TO_122__q1 = ~capModify_b[126:122] ;
  assign NOT_capModify_b_BITS_159_TO_96_1_SRL_capModify_ETC___d29 =
	     x__h2620[13:0] >= toBounds__h1826 &&
	     (!capModify_func[0] ||
	      repBoundBits__h1823 != capModify_a[95:82]) ;
  assign NOT_capModify_b_BIT_160_05_66_OR_NOT_capModify_ETC___d275 =
	     !capModify_b[160] || capModify_a[48:45] != 4'd15 ||
	     IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d273 ||
	     capModify_b[159:96] == 64'hFFFFFFFFFFFFFFFF ;
  assign SEXT__0b0_CONCAT_IF_capModify_func_BIT_0_4_THE_ETC___d222 =
	     deltaAddrHi__h3912 == deltaAddrUpper__h3914 &&
	     capModify_b[160] &&
	     capModify_b[48:45] == 4'd15 &&
	     (capModify_func[0] ||
	      capModify_a[48:45] != 4'd15 && capModify_a[48:45] != 4'd14 &&
	      capModify_a[48:45] != 4'd13 &&
	      capModify_a[48:45] != 4'd12) ;
  assign _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 =
	     { 12'd0, capModify_a[81:78], 3'h0, capModify_a[77:66] } &
	     capModify_b[126:96] ;
  assign a__h4126 = { 60'd0, capModify_a[48:45] } ;
  assign a_capFat_addrBits__h4863 =
	     capModify_func[0] ? capModify_b[95:82] : capModify_a[95:82] ;
  assign a_capFat_address__h4862 =
	     capModify_func[0] ? capModify_b[159:96] : capModify_a[159:96] ;
  assign a_capFat_flags__h4865 =
	     capModify_func[0] ? capModify_b[65] : capModify_a[65] ;
  assign a_capFat_mte__h4867 =
	     capModify_func[0] ? capModify_b[64:57] : capModify_a[64:57] ;
  assign a_capFat_perms_soft__h8272 =
	     capModify_func[0] ? capModify_b[81:78] : capModify_a[81:78] ;
  assign a_capFat_tloc__h4868 =
	     capModify_func[0] ? capModify_b[56:49] : capModify_a[56:49] ;
  assign addBase__h6086 =
	     { {48{x__h6137[15]}}, x__h6137 } << capModify_a[43:38] ;
  assign addBase__h6170 =
	     { {48{x__h6221[15]}}, x__h6221 } << capModify_b[43:38] ;
  assign addTop__h6259 =
	     { {49{x__h6319[15]}}, x__h6319 } << capModify_a[43:38] ;
  assign addTop__h6853 =
	     { {49{x__h6913[15]}}, x__h6913 } << capModify_b[43:38] ;
  assign address__h3899 =
	     capModify_func[0] ? capModify_a[159:96] : a_type__h25 ;
  assign b_baseBits__h11018 =
	     INV_capModify_b_BITS_126_TO_122__q1[0] ?
	       { capModify_b[109:99], 3'd0 } :
	       b_base__h11288 ;
  assign b_base__h11288 =
	     { capModify_b[109:99], ~capModify_b[98], capModify_b[97:96] } ;
  assign b_topBits__h11017 = { impliedTopBits__h10932, topBits__h10928 } ;
  assign b_top__h11287 =
	     { capModify_b[121:113],
	       ~capModify_b[112:111],
	       capModify_b[110] } ;
  assign capModify_a_BITS_159_TO_110_0_AND_112589990684_ETC___d58 =
	     { capModify_a[159:110] & mask__h7509, 14'd0 } + addBase__h6086 ;
  assign capModify_a_BITS_159_TO_110_PLUS_SEXT_capModif_ETC__q3 =
	     capModify_a[159:110] +
	     ({ {48{capModify_a_BITS_1_TO_0__q2[1]}},
		capModify_a_BITS_1_TO_0__q2 } <<
	      capModify_a[43:38]) ;
  assign capModify_a_BITS_159_TO_96_8_SRL_capModify_b_B_ETC___d688 =
	     x__h2849[13:11] < repBound__h11496 ;
  assign capModify_a_BITS_1_TO_0__q2 = capModify_a[1:0] ;
  assign capModify_a_BITS_23_TO_21_3_ULT_capModify_a_BI_ETC___d77 =
	     capModify_a[23:21] < repBound__h11411 ;
  assign capModify_a_BITS_37_TO_35_5_ULT_capModify_a_BI_ETC___d76 =
	     capModify_a[37:35] < repBound__h11411 ;
  assign capModify_b_BITS_159_TO_110_AND_11258999068426_ETC___d208 =
	     capModify_b[159:110] & mask__h6171 ;
  assign capModify_b_BITS_159_TO_110_PLUS_SEXT_capModif_ETC__q5 =
	     capModify_b[159:110] +
	     ({ {48{capModify_b_BITS_1_TO_0__q4[1]}},
		capModify_b_BITS_1_TO_0__q4 } <<
	      capModify_b[43:38]) ;
  assign capModify_b_BITS_159_TO_96_1_CONCAT_IF_capModi_ETC___d171 =
	     { capModify_b[159:96],
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q6,
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q7,
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[77],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[76],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[75],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[74],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[73],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[72],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[71],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[70],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[69],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[68],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[67],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[66],
	       (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[65],
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q8,
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q9,
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q10,
	       capModify_func[4:2] != 3'd2 && capModify_func[4:2] != 3'd3 &&
	       capModify_func[4:2] != 3'd4 ||
	       capModify_b[44],
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q11 } ;
  assign capModify_b_BITS_1_TO_0__q4 = capModify_b[1:0] ;
  assign capModify_b_BITS_23_TO_21_26_ULT_capModify_b_B_ETC___d230 =
	     capModify_b[23:21] < repBound__h11496 ;
  assign capModify_b_BITS_37_TO_35_28_ULT_capModify_b_B_ETC___d229 =
	     capModify_b[37:35] < repBound__h11496 ;
  assign capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d248 =
	     capModify_b[95:82] < capModify_b[37:24] ;
  assign capModify_b_BITS_95_TO_82_07_ULT_capModify_b_B_ETC___d252 =
	     capModify_b[95:82] < capModify_b[23:10] ;
  assign capModify_b_BIT_160_05_AND_capModify_b_BITS_48_ETC___d344 =
	     capModify_b[160] && capModify_b[48:45] == 4'd15 &&
	     capModify_a[43:38] <= 6'd52 &&
	     (capModify_a[43:38] != 6'd52 ||
	      !capModify_a[37] && capModify_a[23:22] == 2'b0) &&
	     (capModify_a[43:38] != 6'd51 || !capModify_a[23]) &&
	     { 12'd0,
	       capModify_a[81:78] & capModify_b[81:78],
	       3'd0,
	       capModify_a[77:66] & capModify_b[77:66] } ==
	     { 12'd0, capModify_a[81:78], 3'h0, capModify_a[77:66] } &&
	     capModify_a_BITS_159_TO_110_0_AND_112589990684_ETC___d58 >=
	     { capModify_b_BITS_159_TO_110_AND_11258999068426_ETC___d208,
	       14'd0 } +
	     addBase__h6170 ;
  assign capModify_b_BIT_5_77_EQ_capModify_b_BIT_4_79___d250 =
	     capModify_b[5] == capModify_b[4] ;
  assign capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_79___d246 =
	     capModify_b[6] == capModify_b[4] ;
  assign capModify_func_BITS_4_TO_2_9_EQ_2_00_OR_capMod_ETC___d185 =
	     { (capModify_func[4:2] == 3'd2 || capModify_func[4:2] == 3'd3 ||
		capModify_func[4:2] == 3'd4) &&
	       capModify_b[160],
	       capModify_b_BITS_159_TO_96_1_CONCAT_IF_capModi_ETC___d171,
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q13,
	       capModify_func[4:2] != 3'd2 && capModify_func[4:2] != 3'd3 &&
	       capModify_func[4:2] != 3'd4 ||
	       capModify_b[6],
	       capModify_func[4:2] != 3'd2 && capModify_func[4:2] != 3'd3 &&
	       capModify_func[4:2] != 3'd4 ||
	       capModify_b[5],
	       capModify_func[4:2] != 3'd2 && capModify_func[4:2] != 3'd3 &&
	       capModify_func[4:2] != 3'd4 ||
	       capModify_b[4],
	       CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q14 } ;
  assign capModify_func_BIT_0_4_OR_capModify_b_BIT_160__ETC___d286 =
	     capModify_func[0] ||
	     capModify_b[160] && capModify_b[48:45] == 4'd15 &&
	     capModify_a[48:45] != 4'd15 &&
	     capModify_a[48:45] != 4'd14 &&
	     capModify_a[48:45] != 4'd13 &&
	     capModify_a[48:45] != 4'd12 &&
	     capModify_b[159:96] == a_type__h25 &&
	     capModify_b[75] &&
	     IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d255 ;
  assign cap_address__h5443 = capModify_b[159:96] ;
  assign carry_out__h10930 =
	     (topBits__h10928 < b_baseBits__h11018[11:0]) ? 2'b01 : 2'b0 ;
  assign deltaAddrHi__h2822 =
	     { {48{x__h2830[1]}}, x__h2830 } << capModify_b[43:38] ;
  assign deltaAddrHi__h3912 =
	     { {48{x__h3920[1]}}, x__h3920 } << capModify_b[43:38] ;
  assign deltaAddrUpper__h2824 =
	     (capModify_a[159:110] & mask__h6171) -
	     capModify_b_BITS_159_TO_110_AND_11258999068426_ETC___d208 ;
  assign deltaAddrUpper__h3914 =
	     (address__h3899[63:14] & mask__h6171) -
	     capModify_b_BITS_159_TO_110_AND_11258999068426_ETC___d208 ;
  assign highOffsetBits__h1817 = x__h1844 & mask__h7509 ;
  assign impliedTopBits__h10932 = x__h11278 + len_correction__h10931 ;
  assign len_correction__h10931 =
	     INV_capModify_b_BITS_126_TO_122__q1[0] ? 2'b01 : 2'b0 ;
  assign mask__h6171 = 50'h3FFFFFFFFFFFF << capModify_b[43:38] ;
  assign mask__h6260 = 51'h7FFFFFFFFFFFF << capModify_a[43:38] ;
  assign mask__h6854 = 51'h7FFFFFFFFFFFF << capModify_b[43:38] ;
  assign mask__h7509 = 50'h3FFFFFFFFFFFF << capModify_a[43:38] ;
  assign newAddrBits__h2701 = capModify_a[23:10] + x__h2620[13:0] ;
  assign pointer__h1810 = capModify_a[159:96] + capModify_b[159:96] ;
  assign repBoundBits__h1823 = { capModify_a[9:7], 11'd0 } ;
  assign repBound__h11411 = capModify_a[23:21] - 3'b001 ;
  assign repBound__h11496 = capModify_b[23:21] - 3'b001 ;
  assign repBound__h11507 = b_baseBits__h11018[13:11] - 3'b001 ;
  assign res_addrBits__h2757 = { 2'd0, capModify_b[159:148] } ;
  assign res_addrBits__h3210 =
	     INV_capModify_b_BITS_126_TO_122__q1[0] ?
	       x__h8169[13:0] :
	       capModify_a[109:96] ;
  assign result__h6795 = { ~ret__h6261[64], ret__h6261[63:0] } ;
  assign result__h7390 = { ~ret__h6855[64], ret__h6855[63:0] } ;
  assign result_d_addrBits__h2719 =
	     capModify_func[0] ?
	       x__h8069[13:0] :
	       { mask__h2702, 12'd4095 } & newAddrBits__h2701 ;
  assign result_d_address__h2718 =
	     capModify_func[0] ? pointer__h1810 : ret___1_address__h3519 ;
  assign ret___1_address__h3519 =
	     capModify_a_BITS_159_TO_110_0_AND_112589990684_ETC___d58 +
	     capModify_b[159:96] ;
  assign ret__h6261 =
	     { { 1'b0, capModify_a[159:110] } & mask__h6260, 14'd0 } +
	     addTop__h6259 ;
  assign ret__h6855 =
	     { { 1'b0, capModify_b[159:110] } & mask__h6854, 14'd0 } +
	     addTop__h6853 ;
  assign signBits__h1814 = {50{capModify_b[159]}} ;
  assign tb__h11504 = { impliedTopBits__h10932, topBits__h10928[11] } ;
  assign thin_otype__h5675 = capModify_a[48:45] ;
  assign tmp_expBotHalf__h8162 = { ~capModify_b[98], capModify_b[97:96] } ;
  assign tmp_expTopHalf__h8160 = { ~capModify_b[112:111], capModify_b[110] } ;
  assign toBoundsM1_A__h1822 = { 3'b110, ~capModify_a[20:10] } ;
  assign toBoundsM1_B__h1825 = repBoundBits__h1823 + ~capModify_a[95:82] ;
  assign toBoundsM1__h1827 =
	     capModify_func[0] ? toBoundsM1_B__h1825 : toBoundsM1_A__h1822 ;
  assign toBounds_A__h1821 = 14'd14336 - { 3'b0, capModify_a[20:10] } ;
  assign toBounds_B__h1824 = repBoundBits__h1823 - capModify_a[95:82] ;
  assign toBounds__h1826 =
	     capModify_func[0] ? toBounds_B__h1824 : toBounds_A__h1821 ;
  assign topBits__h10928 =
	     INV_capModify_b_BITS_126_TO_122__q1[0] ?
	       { capModify_b[121:113], 3'd0 } :
	       b_top__h11287 ;
  assign x__h11278 = b_baseBits__h11018[13:12] + carry_out__h10930 ;
  assign x__h1844 = capModify_b[159:110] ^ signBits__h1814 ;
  assign x__h2620 = capModify_b[159:96] >> capModify_a[43:38] ;
  assign x__h2830 =
	     { 1'b0, x__h2849[13:11] < capModify_b[9:7] } -
	     { 1'b0, capModify_b[4] } ;
  assign x__h2849 = capModify_a[159:96] >> capModify_b[43:38] ;
  assign x__h3920 =
	     { 1'b0, x__h3939[13:11] < capModify_b[9:7] } -
	     { 1'b0, capModify_b[4] } ;
  assign x__h3939 = address__h3899 >> capModify_b[43:38] ;
  assign x__h6137 = { capModify_a[1:0], capModify_a[23:10] } ;
  assign x__h6221 = { capModify_b[1:0], capModify_b[23:10] } ;
  assign x__h6319 = { capModify_a[3:2], capModify_a[37:24] } ;
  assign x__h6913 = { capModify_b[3:2], capModify_b[37:24] } ;
  assign x__h8069 = pointer__h1810 >> capModify_a[43:38] ;
  assign x__h8169 = capModify_a[159:96] >> x__h8207 ;
  assign x__h8207 = { tmp_expTopHalf__h8160, tmp_expBotHalf__h8162 } ;
  always@(capModify_a)
  begin
    case (capModify_a[43:38])
      6'd51: mask__h2702 = 2'b01;
      6'd52: mask__h2702 = 2'b0;
      default: mask__h2702 = 2'b11;
    endcase
  end
  always@(capModify_a or a__h4126)
  begin
    case (capModify_a[48:45])
      4'd12: a_type__h25 = 64'hFFFFFFFFFFFFFFFC;
      4'd13: a_type__h25 = 64'hFFFFFFFFFFFFFFFD;
      4'd14: a_type__h25 = 64'hFFFFFFFFFFFFFFFE;
      4'd15: a_type__h25 = 64'hFFFFFFFFFFFFFFFF;
      default: a_type__h25 = a__h4126;
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578 =
	      capModify_a[67];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[1];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578 =
	      capModify_b[145];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578 =
	      capModify_a[159:96] != 64'd0 && capModify_b[67];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d578 =
		   capModify_a[67];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558 =
	      capModify_a[69];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[3];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558 =
	      capModify_b[147];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558 =
	      capModify_a[159:96] != 64'd0 && capModify_b[69];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d558 =
		   capModify_a[69];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538 =
	      capModify_a[71];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[5];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538 =
	      capModify_b[149];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538 =
	      capModify_a[159:96] != 64'd0 && capModify_b[71];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d538 =
		   capModify_a[71];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518 =
	      capModify_a[73];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[7];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518 =
	      capModify_b[151];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518 =
	      capModify_a[159:96] != 64'd0 && capModify_b[73];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d518 =
		   capModify_a[73];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498 =
	      capModify_a[75];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[9];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498 =
	      capModify_b[153];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498 =
	      capModify_a[159:96] != 64'd0 && capModify_b[75];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d498 =
		   capModify_a[75];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478 =
	      capModify_a[77];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[11];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478 =
	      capModify_b[155];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478 =
	      capModify_a[159:96] != 64'd0 && capModify_b[77];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d478 =
		   capModify_a[77];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  capModify_b or
	  NOT_capModify_b_BIT_160_05_66_OR_NOT_capModify_ETC___d275 or
	  INV_capModify_b_BITS_126_TO_122__q1)
  begin
    case (capModify_func[9:5])
      5'd4:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
	      capModify_b[99:96];
      5'd5:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
	      NOT_capModify_b_BIT_160_05_66_OR_NOT_capModify_ETC___d275 ?
		capModify_a[48:45] :
		capModify_b[99:96];
      5'd6: IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 = 4'd14;
      5'd7: IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 = 4'd15;
      5'd8, 5'd9, 5'd11, 5'd12:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
	      capModify_a[48:45];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
	      INV_capModify_b_BITS_126_TO_122__q1[4:1];
      5'd13:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
	      (capModify_a[48:45] == 4'd14) ? capModify_a[48:45] : 4'd15;
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
	      (capModify_a[159:96] == 64'd0) ? 4'd15 : capModify_b[48:45];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_14__ETC___d647 =
		   capModify_a[48:45];
    endcase
  end
  always@(capModify_func or capModify_a or a_capFat_mte__h4867 or capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd8, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620 =
	      capModify_a[64:57];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620 =
	      a_capFat_mte__h4867;
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620 =
	      capModify_b[142:135];
      5'd11:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620 =
	      capModify_b[103:96];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620 =
	      (capModify_a[159:96] == 64'd0) ? 8'd0 : capModify_b[64:57];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d620 =
		   capModify_a[64:57];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  a_capFat_perms_soft__h8272 or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467 =
	      capModify_a[81:78];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467 =
	      a_capFat_perms_soft__h8272;
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[18:15];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467 =
	      capModify_b[159:156];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467 =
	      (capModify_a[159:96] == 64'd0) ? 4'd0 : capModify_b[81:78];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d467 =
		   capModify_a[81:78];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  capModify_b_BIT_160_05_AND_capModify_b_BITS_48_ETC___d344 or
	  IF_capModify_a_BITS_43_TO_38_ULT_51_45_AND_NOT_ETC___d372 or
	  IF_capModify_b_BITS_43_TO_38_96_ULT_51_73_AND__ETC___d400)
  begin
    case (capModify_func[9:5])
      5'd11, 5'd12:
	  IF_capModify_func_BITS_9_TO_5_EQ_11_08_OR_capM_ETC___d406 =
	      capModify_a[160] && capModify_a[48:45] == 4'd15;
      5'd13:
	  IF_capModify_func_BITS_9_TO_5_EQ_11_08_OR_capM_ETC___d406 =
	      capModify_b_BIT_160_05_AND_capModify_b_BITS_48_ETC___d344 &&
	      IF_capModify_a_BITS_43_TO_38_ULT_51_45_AND_NOT_ETC___d372 <=
	      IF_capModify_b_BITS_43_TO_38_96_ULT_51_73_AND__ETC___d400;
      default: IF_capModify_func_BITS_9_TO_5_EQ_11_08_OR_capM_ETC___d406 =
		   capModify_func[9:5] == 5'd14 && capModify_a[160];
    endcase
  end
  always@(capModify_func or
	  IF_capModify_func_BITS_9_TO_5_EQ_11_08_OR_capM_ETC___d406 or
	  capModify_a or
	  capModify_b or
	  IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d255 or
	  IF_NOT_capModify_b_BIT_160_05_66_OR_NOT_capMod_ETC___d277 or
	  IF_capModify_func_BIT_0_4_THEN_capModify_b_BIT_ETC___d287 or
	  deltaAddrHi__h2822 or deltaAddrUpper__h2824)
  begin
    case (capModify_func[9:5])
      5'd4:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 =
	      capModify_a[160] && capModify_a[48:45] == 4'd15 &&
	      capModify_b[160] &&
	      IF_capModify_b_BIT_6_75_EQ_capModify_b_BIT_4_7_ETC___d255 &&
	      capModify_b[48:45] == 4'd15 &&
	      capModify_b[73] &&
	      capModify_b[159:96] <= 64'd11;
      5'd5:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 =
	      IF_NOT_capModify_b_BIT_160_05_66_OR_NOT_capMod_ETC___d277;
      5'd6, 5'd8, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 =
	      capModify_a[160] && capModify_a[48:45] == 4'd15;
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 =
	      IF_capModify_func_BIT_0_4_THEN_capModify_b_BIT_ETC___d287;
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 =
	      capModify_a[159:96] != 64'd0 &&
	      deltaAddrHi__h2822 == deltaAddrUpper__h2824 &&
	      capModify_b[160] &&
	      capModify_b[48:45] == 4'd15;
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_THEN_cap_ETC___d413 =
		   capModify_func[9:5] != 5'd10 &&
		   IF_capModify_func_BITS_9_TO_5_EQ_11_08_OR_capM_ETC___d406;
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  capModify_b or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590 =
	      capModify_a[66];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590 =
	      capModify_a[66] && capModify_b[66];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[0];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590 =
	      capModify_b[144];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590 =
	      capModify_a[159:96] != 64'd0 && capModify_b[66];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d590 =
		   capModify_a[66];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568 =
	      capModify_a[68];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[2];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568 =
	      capModify_b[146];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568 =
	      capModify_a[159:96] != 64'd0 && capModify_b[68];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d568 =
		   capModify_a[68];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548 =
	      capModify_a[70];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[4];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548 =
	      capModify_b[148];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548 =
	      capModify_a[159:96] != 64'd0 && capModify_b[70];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d548 =
		   capModify_a[70];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528 =
	      capModify_a[72];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[6];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528 =
	      capModify_b[150];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528 =
	      capModify_a[159:96] != 64'd0 && capModify_b[72];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d528 =
		   capModify_a[72];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508 =
	      capModify_a[74];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[8];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508 =
	      capModify_b[152];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508 =
	      capModify_a[159:96] != 64'd0 && capModify_b[74];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d508 =
		   capModify_a[74];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456 or
	  capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd7, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488 =
	      capModify_a[76];
      5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488 =
	      _0_CONCAT_capModify_a_BITS_81_TO_78_27_CONCAT_0_ETC___d456[10];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488 =
	      capModify_b[154];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488 =
	      capModify_a[159:96] != 64'd0 && capModify_b[76];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d488 =
		   capModify_a[76];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  capModify_b or
	  INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_34_ETC___d672)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd8, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677 =
	      capModify_a[44:10];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677 =
	      capModify_func[0] ? capModify_b[44:10] : capModify_a[44:10];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677 =
	      INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_34_ETC___d672;
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677 =
	      { capModify_a[159:96] == 64'd0 || capModify_b[44],
		(capModify_a[159:96] == 64'd0) ?
		  34'h344000000 :
		  capModify_b[43:10] };
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d677 =
		   capModify_a[44:10];
    endcase
  end
  always@(capModify_func or
	  capModify_a or a_capFat_tloc__h4868 or capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd8, 5'd9, 5'd11:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632 =
	      capModify_a[56:49];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632 =
	      a_capFat_tloc__h4868;
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632 =
	      capModify_b[134:127];
      5'd12:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632 =
	      capModify_b[103:96];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632 =
	      (capModify_a[159:96] == 64'd0) ? 8'd0 : capModify_b[56:49];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d632 =
		   capModify_a[56:49];
    endcase
  end
  always@(capModify_func or
	  capModify_a or a_capFat_flags__h4865 or capModify_b)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd8:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608 =
	      capModify_a[65];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608 =
	      a_capFat_flags__h4865;
      5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608 =
	      capModify_b[96];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608 =
	      capModify_b[143];
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608 =
	      capModify_a[159:96] != 64'd0 && capModify_b[65];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d608 =
		   capModify_a[65];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  a_capFat_addrBits__h4863 or res_addrBits__h3210 or x__h2849)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd8, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453 =
	      capModify_a[95:82];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453 =
	      a_capFat_addrBits__h4863;
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453 =
	      res_addrBits__h3210;
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453 =
	      (capModify_a[159:96] == 64'd0) ? 14'd0 : x__h2849[13:0];
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d453 =
		   capModify_a[95:82];
    endcase
  end
  always@(capModify_func or res_addrBits__h2757 or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q6 =
	      capModify_b[95:82];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q6 =
		   res_addrBits__h2757;
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q7 =
	      capModify_b[81:78];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q7 = 4'd0;
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q8 =
	      capModify_b[64:57];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q8 = 8'd0;
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q9 =
	      capModify_b[56:49];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q9 = 8'd0;
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q10 =
	      capModify_b[48:45];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q10 =
		   4'd15;
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q11 =
	      capModify_b[43:10];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q11 =
		   34'h344000000;
    endcase
  end
  always@(capModify_func or capModify_a or a_capFat_address__h4862)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6:
	  CASE_capModify_func_BITS_9_TO_5_4_capModify_a__ETC__q12 =
	      capModify_a[159:96];
      5'd7:
	  CASE_capModify_func_BITS_9_TO_5_4_capModify_a__ETC__q12 =
	      a_capFat_address__h4862;
      default: CASE_capModify_func_BITS_9_TO_5_4_capModify_a__ETC__q12 =
		   capModify_a[159:96];
    endcase
  end
  always@(capModify_func or
	  capModify_a or
	  capModify_b or
	  repBound__h11507 or
	  IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d708 or
	  IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d709 or
	  IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711 or
	  IF_IF_INV_capModify_b_BITS_126_TO_122_32_33_BI_ETC___d721 or
	  IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_THEN_7_ETC___d703)
  begin
    case (capModify_func[9:5])
      5'd4, 5'd5, 5'd6, 5'd8, 5'd9:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 =
	      capModify_a[9:0];
      5'd7:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 =
	      capModify_func[0] ? capModify_b[9:0] : capModify_a[9:0];
      5'd10:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 =
	      { repBound__h11507,
		IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d708,
		IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d709,
		IF_INV_capModify_b_BITS_126_TO_122_32_33_BIT_0_ETC___d711,
		IF_IF_INV_capModify_b_BITS_126_TO_122_32_33_BI_ETC___d721 };
      5'd16:
	  IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 =
	      IF_capModify_a_BITS_159_TO_96_8_EQ_0_92_THEN_7_ETC___d703;
      default: IF_capModify_func_BITS_9_TO_5_EQ_6_44_OR_capMo_ETC___d729 =
		   capModify_a[9:0];
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q13 =
	      capModify_b[9:7];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q13 = 3'd7;
    endcase
  end
  always@(capModify_func or capModify_b)
  begin
    case (capModify_func[4:2])
      3'd2, 3'd3, 3'd4:
	  CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q14 =
	      capModify_b[3:0];
      default: CASE_capModify_func_BITS_4_TO_2_2_capModify_b__ETC__q14 = 4'd0;
    endcase
  end
endmodule  // module_capModify

