/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sun May 31 11:17:13 BST 2026
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_sysTime.h"
 *     void (*vlog_startup_routines[])() = { sysTime_vpi_register, 0u };
 * 
 * For a Verilog simulator which requires a .tab file, use the following entry:
 * $imported_sysTime call=sysTime_calltf size=64 acc=rw:%TASK
 * 
 * For a Verilog simulator which requires a .sft file, use the following entry:
 * $imported_sysTime vpiSysFuncSized 64 unsigned
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
unsigned long long sysTime();

/* VPI wrapper function */
PLI_INT32 sysTime_calltf(PLI_BYTE8 *user_data)
{
  vpiHandle hCall;
  unsigned long long vpi_result;
  vpiHandle *handle_array;
  
  /* retrieve handle array */
  hCall = vpi_handle(vpiSysTfCall, 0);
  handle_array = vpi_get_userdata(hCall);
  if (handle_array == NULL)
  {
    vpiHandle hArgList;
    hArgList = vpi_iterate(vpiArgument, hCall);
    handle_array = malloc(sizeof(vpiHandle) * 1u);
    handle_array[0u] = hCall;
    vpi_put_userdata(hCall, handle_array);
    vpi_free_object(hArgList);
  }
  
  /* create return value */
  make_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* call the imported C function */
  vpi_result = sysTime();
  
  /* copy out return value */
  put_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  vpi_free_object(hCall);
  
  return 0;
}

/* sft: $imported_sysTime vpiSysFuncSized 64 unsigned */

/* tab: $imported_sysTime call=sysTime_calltf size=64 acc=rw:%TASK */

PLI_INT32 sysTime_sizetf(PLI_BYTE8 *user_data)
{
  return 64u;
}

/* VPI wrapper registration function */
void sysTime_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysFunc;
  tf_data.sysfunctype = vpiSizedFunc;
  tf_data.tfname = "$imported_sysTime";
  tf_data.calltf = sysTime_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = sysTime_sizetf;
  tf_data.user_data = "$imported_sysTime";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
