/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sun May 31 11:17:13 BST 2026
 * 
 */
#ifndef __vpi_wrapper_bub_fifo_DPI_C_WriteByte_h__
#define __vpi_wrapper_bub_fifo_DPI_C_WriteByte_h__

#include <vpi_user.h>

/* registration function */
void bub_fifo_DPI_C_WriteByte_vpi_register();

/* VPI wrapper function */
PLI_INT32 bub_fifo_DPI_C_WriteByte_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_bub_fifo_DPI_C_WriteByte_h__ */
