/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Sun May 31 11:20:21 BST 2026
 * 
 */
#ifndef __vpi_wrapper_mem_init_h__
#define __vpi_wrapper_mem_init_h__

#include <vpi_user.h>

/* registration function */
void mem_init_vpi_register();

/* VPI wrapper function */
PLI_INT32 mem_init_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_mem_init_h__ */
