//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:22:14 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_nextPc                     O     1 const
// pred_0_pred                    O    35
// RDY_pred_0_pred                O     1 const
// pred_1_pred                    O    35
// RDY_pred_1_pred                O     1 const
// RDY_update                     O     1 const
// RDY_flush                      O     1 const
// flush_done                     O     1 const
// RDY_flush_done                 O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// nextPc_nextPc                  I    64
// update_taken                   I     1
// update_train                   I    34
// update_mispred                 I     1
// EN_nextPc                      I     1
// EN_update                      I     1
// EN_flush                       I     1 unused
// EN_pred_0_pred                 I     1
// EN_pred_1_pred                 I     1
//
// Combinational paths from inputs to outputs:
//   EN_pred_0_pred -> pred_1_pred
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTourPred(CLK,
		  RST_N,

		  nextPc_nextPc,
		  EN_nextPc,
		  RDY_nextPc,

		  EN_pred_0_pred,
		  pred_0_pred,
		  RDY_pred_0_pred,

		  EN_pred_1_pred,
		  pred_1_pred,
		  RDY_pred_1_pred,

		  update_taken,
		  update_train,
		  update_mispred,
		  EN_update,
		  RDY_update,

		  EN_flush,
		  RDY_flush,

		  flush_done,
		  RDY_flush_done);
  input  CLK;
  input  RST_N;

  // action method nextPc
  input  [63 : 0] nextPc_nextPc;
  input  EN_nextPc;
  output RDY_nextPc;

  // actionvalue method pred_0_pred
  input  EN_pred_0_pred;
  output [34 : 0] pred_0_pred;
  output RDY_pred_0_pred;

  // actionvalue method pred_1_pred
  input  EN_pred_1_pred;
  output [34 : 0] pred_1_pred;
  output RDY_pred_1_pred;

  // action method update
  input  update_taken;
  input  [33 : 0] update_train;
  input  update_mispred;
  input  EN_update;
  output RDY_update;

  // action method flush
  input  EN_flush;
  output RDY_flush;

  // value method flush_done
  output flush_done;
  output RDY_flush_done;

  // signals for module outputs
  wire [34 : 0] pred_0_pred, pred_1_pred;
  wire RDY_flush,
       RDY_flush_done,
       RDY_nextPc,
       RDY_pred_0_pred,
       RDY_pred_1_pred,
       RDY_update,
       flush_done;

  // inlined wires
  wire [1 : 0] predCnt_lat_0$wget,
	       predCnt_lat_1$wget,
	       predRes_lat_0$wget,
	       predRes_lat_1$wget;

  // register globalTakenVec
  reg [1 : 0] globalTakenVec;
  wire [1 : 0] globalTakenVec$D_IN;
  wire globalTakenVec$EN;

  // register pcIndex
  reg [19 : 0] pcIndex;
  wire [19 : 0] pcIndex$D_IN;
  wire pcIndex$EN;

  // register pc_reg
  reg [63 : 0] pc_reg;
  wire [63 : 0] pc_reg$D_IN;
  wire pc_reg$EN;

  // register predCnt_rl
  reg [1 : 0] predCnt_rl;
  wire [1 : 0] predCnt_rl$D_IN;
  wire predCnt_rl$EN;

  // register predRes_rl
  reg [1 : 0] predRes_rl;
  wire [1 : 0] predRes_rl$D_IN;
  wire predRes_rl$EN;

  // register prevGHist
  reg [11 : 0] prevGHist;
  wire [11 : 0] prevGHist$D_IN;
  wire prevGHist$EN;

  // register useLocalVec
  reg [1 : 0] useLocalVec;
  wire [1 : 0] useLocalVec$D_IN;
  wire useLocalVec$EN;

  // ports of submodule choiceBht
  wire [11 : 0] choiceBht$ADDR_1,
		choiceBht$ADDR_2,
		choiceBht$ADDR_3,
		choiceBht$ADDR_4,
		choiceBht$ADDR_5,
		choiceBht$ADDR_IN;
  wire [1 : 0] choiceBht$D_IN,
	       choiceBht$D_OUT_1,
	       choiceBht$D_OUT_2,
	       choiceBht$D_OUT_3;
  wire choiceBht$WE;

  // ports of submodule gHistReg
  wire [11 : 0] gHistReg$history, gHistReg$redirect_newHist;
  wire [1 : 0] gHistReg$addHistory_num, gHistReg$addHistory_taken;
  wire gHistReg$EN_addHistory, gHistReg$EN_redirect;

  // ports of submodule globalBht
  wire [11 : 0] globalBht$ADDR_1,
		globalBht$ADDR_2,
		globalBht$ADDR_3,
		globalBht$ADDR_4,
		globalBht$ADDR_5,
		globalBht$ADDR_IN;
  wire [1 : 0] globalBht$D_IN,
	       globalBht$D_OUT_1,
	       globalBht$D_OUT_2,
	       globalBht$D_OUT_3;
  wire globalBht$WE;

  // ports of submodule localBht
  wire [9 : 0] localBht$ADDR_1,
	       localBht$ADDR_2,
	       localBht$ADDR_3,
	       localBht$ADDR_4,
	       localBht$ADDR_5,
	       localBht$ADDR_IN;
  wire [2 : 0] localBht$D_IN,
	       localBht$D_OUT_1,
	       localBht$D_OUT_2,
	       localBht$D_OUT_3;
  wire localBht$WE;

  // ports of submodule localHistTab
  wire [9 : 0] localHistTab$ADDR_1,
	       localHistTab$ADDR_2,
	       localHistTab$ADDR_3,
	       localHistTab$ADDR_4,
	       localHistTab$ADDR_5,
	       localHistTab$ADDR_IN,
	       localHistTab$D_IN,
	       localHistTab$D_OUT_1,
	       localHistTab$D_OUT_2;
  wire localHistTab$WE;

  // rule scheduling signals
  wire CAN_FIRE_RL_canonGlobalHist,
       CAN_FIRE_RL_predCnt_canon,
       CAN_FIRE_RL_predRes_canon,
       CAN_FIRE_flush,
       CAN_FIRE_nextPc,
       CAN_FIRE_pred_0_pred,
       CAN_FIRE_pred_1_pred,
       CAN_FIRE_update,
       WILL_FIRE_RL_canonGlobalHist,
       WILL_FIRE_RL_predCnt_canon,
       WILL_FIRE_RL_predRes_canon,
       WILL_FIRE_flush,
       WILL_FIRE_nextPc,
       WILL_FIRE_pred_0_pred,
       WILL_FIRE_pred_1_pred,
       WILL_FIRE_update;

  // remaining internal signals
  reg CASE_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_ETC__q2,
      CASE_predCnt_rl_0_useLocalVec_BIT_0_1_useLocal_ETC__q1,
      SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64,
      SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81;
  wire [13 : 0] x__h2510;
  wire [11 : 0] y_avValue_train_globalHist__h4069,
		y_avValue_train_globalHist__h4474;
  wire [7 : 0] nextPc_nextPc_BITS_7_TO_0_PLUS_4__q3;
  wire [2 : 0] IF_update_taken_THEN_7_ELSE_1___d100,
	       localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104;
  wire [1 : 0] IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11,
	       IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24,
	       IF_update_taken_THEN_3_ELSE_1___d116,
	       IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136,
	       choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140,
	       globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120,
	       upd__h1259,
	       upd__h1286,
	       upd__h1851,
	       upd__h1878,
	       x__h3630,
	       x__h4272,
	       y__h4054,
	       y__h4462;
  wire IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65,
       IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82;

  // action method nextPc
  assign RDY_nextPc = 1'd1 ;
  assign CAN_FIRE_nextPc = 1'd1 ;
  assign WILL_FIRE_nextPc = EN_nextPc ;

  // actionvalue method pred_0_pred
  assign pred_0_pred =
	     { IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65,
	       y_avValue_train_globalHist__h4069,
	       localHistTab$D_OUT_2,
	       SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64,
	       localBht$D_OUT_3[2],
	       pcIndex[9:0] } ;
  assign RDY_pred_0_pred = 1'd1 ;
  assign CAN_FIRE_pred_0_pred = 1'd1 ;
  assign WILL_FIRE_pred_0_pred = EN_pred_0_pred ;

  // actionvalue method pred_1_pred
  assign pred_1_pred =
	     { IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82,
	       y_avValue_train_globalHist__h4474,
	       localHistTab$D_OUT_1,
	       SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81,
	       localBht$D_OUT_2[2],
	       pcIndex[19:10] } ;
  assign RDY_pred_1_pred = 1'd1 ;
  assign CAN_FIRE_pred_1_pred = 1'd1 ;
  assign WILL_FIRE_pred_1_pred = EN_pred_1_pred ;

  // action method update
  assign RDY_update = 1'd1 ;
  assign CAN_FIRE_update = 1'd1 ;
  assign WILL_FIRE_update = EN_update ;

  // action method flush
  assign RDY_flush = 1'd1 ;
  assign CAN_FIRE_flush = 1'd1 ;
  assign WILL_FIRE_flush = EN_flush ;

  // value method flush_done
  assign flush_done = 1'd1 ;
  assign RDY_flush_done = 1'd1 ;

  // submodule choiceBht
  RegFile #(.addr_width(32'd12),
	    .data_width(32'd2),
	    .lo(12'd0),
	    .hi(12'd4095)) choiceBht(.CLK(CLK),
				     .ADDR_1(choiceBht$ADDR_1),
				     .ADDR_2(choiceBht$ADDR_2),
				     .ADDR_3(choiceBht$ADDR_3),
				     .ADDR_4(choiceBht$ADDR_4),
				     .ADDR_5(choiceBht$ADDR_5),
				     .ADDR_IN(choiceBht$ADDR_IN),
				     .D_IN(choiceBht$D_IN),
				     .WE(choiceBht$WE),
				     .D_OUT_1(choiceBht$D_OUT_1),
				     .D_OUT_2(choiceBht$D_OUT_2),
				     .D_OUT_3(choiceBht$D_OUT_3),
				     .D_OUT_4(),
				     .D_OUT_5());

  // submodule gHistReg
  mkTourGHistReg gHistReg(.CLK(CLK),
			  .RST_N(RST_N),
			  .addHistory_num(gHistReg$addHistory_num),
			  .addHistory_taken(gHistReg$addHistory_taken),
			  .redirect_newHist(gHistReg$redirect_newHist),
			  .EN_addHistory(gHistReg$EN_addHistory),
			  .EN_redirect(gHistReg$EN_redirect),
			  .history(gHistReg$history),
			  .RDY_history(),
			  .RDY_addHistory(),
			  .RDY_redirect());

  // submodule globalBht
  RegFile #(.addr_width(32'd12),
	    .data_width(32'd2),
	    .lo(12'd0),
	    .hi(12'd4095)) globalBht(.CLK(CLK),
				     .ADDR_1(globalBht$ADDR_1),
				     .ADDR_2(globalBht$ADDR_2),
				     .ADDR_3(globalBht$ADDR_3),
				     .ADDR_4(globalBht$ADDR_4),
				     .ADDR_5(globalBht$ADDR_5),
				     .ADDR_IN(globalBht$ADDR_IN),
				     .D_IN(globalBht$D_IN),
				     .WE(globalBht$WE),
				     .D_OUT_1(globalBht$D_OUT_1),
				     .D_OUT_2(globalBht$D_OUT_2),
				     .D_OUT_3(globalBht$D_OUT_3),
				     .D_OUT_4(),
				     .D_OUT_5());

  // submodule localBht
  RegFile #(.addr_width(32'd10),
	    .data_width(32'd3),
	    .lo(10'd0),
	    .hi(10'd1023)) localBht(.CLK(CLK),
				    .ADDR_1(localBht$ADDR_1),
				    .ADDR_2(localBht$ADDR_2),
				    .ADDR_3(localBht$ADDR_3),
				    .ADDR_4(localBht$ADDR_4),
				    .ADDR_5(localBht$ADDR_5),
				    .ADDR_IN(localBht$ADDR_IN),
				    .D_IN(localBht$D_IN),
				    .WE(localBht$WE),
				    .D_OUT_1(localBht$D_OUT_1),
				    .D_OUT_2(localBht$D_OUT_2),
				    .D_OUT_3(localBht$D_OUT_3),
				    .D_OUT_4(),
				    .D_OUT_5());

  // submodule localHistTab
  RegFile #(.addr_width(32'd10),
	    .data_width(32'd10),
	    .lo(10'd0),
	    .hi(10'd1023)) localHistTab(.CLK(CLK),
					.ADDR_1(localHistTab$ADDR_1),
					.ADDR_2(localHistTab$ADDR_2),
					.ADDR_3(localHistTab$ADDR_3),
					.ADDR_4(localHistTab$ADDR_4),
					.ADDR_5(localHistTab$ADDR_5),
					.ADDR_IN(localHistTab$ADDR_IN),
					.D_IN(localHistTab$D_IN),
					.WE(localHistTab$WE),
					.D_OUT_1(localHistTab$D_OUT_1),
					.D_OUT_2(localHistTab$D_OUT_2),
					.D_OUT_3(),
					.D_OUT_4(),
					.D_OUT_5());

  // rule RL_canonGlobalHist
  assign CAN_FIRE_RL_canonGlobalHist = 1'd1 ;
  assign WILL_FIRE_RL_canonGlobalHist = 1'd1 ;

  // rule RL_predCnt_canon
  assign CAN_FIRE_RL_predCnt_canon = 1'd1 ;
  assign WILL_FIRE_RL_predCnt_canon = 1'd1 ;

  // rule RL_predRes_canon
  assign CAN_FIRE_RL_predRes_canon = 1'd1 ;
  assign WILL_FIRE_RL_predRes_canon = 1'd1 ;

  // inlined wires
  assign predCnt_lat_0$wget = predCnt_rl + 2'd1 ;
  assign predCnt_lat_1$wget =
	     IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 + 2'd1 ;
  assign predRes_lat_0$wget =
	     IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65 ?
	       predRes_rl | x__h3630 :
	       predRes_rl & y__h4054 ;
  assign predRes_lat_1$wget =
	     IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82 ?
	       IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 |
	       x__h4272 :
	       IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 &
	       y__h4462 ;

  // register globalTakenVec
  assign globalTakenVec$D_IN =
	     { globalBht$D_OUT_1[1], globalBht$D_OUT_2[1] } ;
  assign globalTakenVec$EN = 1'd1 ;

  // register pcIndex
  assign pcIndex$D_IN =
	     { nextPc_nextPc[10:8],
	       nextPc_nextPc_BITS_7_TO_0_PLUS_4__q3[7:1],
	       nextPc_nextPc[10:1] } ;
  assign pcIndex$EN = EN_nextPc ;

  // register pc_reg
  assign pc_reg$D_IN = nextPc_nextPc ;
  assign pc_reg$EN = EN_nextPc ;

  // register predCnt_rl
  assign predCnt_rl$D_IN = 2'd0 ;
  assign predCnt_rl$EN = 1'd1 ;

  // register predRes_rl
  assign predRes_rl$D_IN = 2'd0 ;
  assign predRes_rl$EN = 1'd1 ;

  // register prevGHist
  assign prevGHist$D_IN = x__h2510[11:0] ;
  assign prevGHist$EN = 1'd1 ;

  // register useLocalVec
  assign useLocalVec$D_IN = { choiceBht$D_OUT_1[1], choiceBht$D_OUT_2[1] } ;
  assign useLocalVec$EN = 1'd1 ;

  // submodule choiceBht
  assign choiceBht$ADDR_1 = { 1'd0, x__h2510[11:1] } ;
  assign choiceBht$ADDR_2 = x__h2510[11:0] ;
  assign choiceBht$ADDR_3 = update_train[33:22] ;
  assign choiceBht$ADDR_4 = 12'h0 ;
  assign choiceBht$ADDR_5 = 12'h0 ;
  assign choiceBht$ADDR_IN = update_train[33:22] ;
  assign choiceBht$D_IN =
	     (!choiceBht$D_OUT_3[1] &&
	      !IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136[1] &&
	      choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140[1]) ?
	       2'd1 :
	       ((choiceBht$D_OUT_3[1] &&
		 IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136[1] &&
		 !choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140[1]) ?
		  2'd2 :
		  choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140) ;
  assign choiceBht$WE = EN_update && update_train[11] != update_train[10] ;

  // submodule gHistReg
  assign gHistReg$addHistory_num =
	     EN_pred_1_pred ?
	       upd__h1259 :
	       IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 ;
  assign gHistReg$addHistory_taken =
	     EN_pred_1_pred ?
	       upd__h1851 :
	       IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 ;
  assign gHistReg$redirect_newHist = { update_taken, update_train[33:23] } ;
  assign gHistReg$EN_addHistory = 1'd1 ;
  assign gHistReg$EN_redirect = EN_update && update_mispred ;

  // submodule globalBht
  assign globalBht$ADDR_1 = { 1'd0, x__h2510[11:1] } ;
  assign globalBht$ADDR_2 = x__h2510[11:0] ;
  assign globalBht$ADDR_3 = update_train[33:22] ;
  assign globalBht$ADDR_4 = 12'h0 ;
  assign globalBht$ADDR_5 = 12'h0 ;
  assign globalBht$ADDR_IN = update_train[33:22] ;
  assign globalBht$D_IN =
	     (!globalBht$D_OUT_3[1] &&
	      !IF_update_taken_THEN_3_ELSE_1___d116[1] &&
	      globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120[1]) ?
	       2'd1 :
	       ((globalBht$D_OUT_3[1] &&
		 IF_update_taken_THEN_3_ELSE_1___d116[1] &&
		 !globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120[1]) ?
		  2'd2 :
		  globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120) ;
  assign globalBht$WE = EN_update ;

  // submodule localBht
  assign localBht$ADDR_1 = update_train[21:12] ;
  assign localBht$ADDR_2 = localHistTab$D_OUT_1 ;
  assign localBht$ADDR_3 = localHistTab$D_OUT_2 ;
  assign localBht$ADDR_4 = 10'h0 ;
  assign localBht$ADDR_5 = 10'h0 ;
  assign localBht$ADDR_IN = update_train[21:12] ;
  assign localBht$D_IN =
	     (!localBht$D_OUT_1[2] &&
	      !IF_update_taken_THEN_7_ELSE_1___d100[2] &&
	      localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104[2]) ?
	       3'd3 :
	       ((localBht$D_OUT_1[2] &&
		 IF_update_taken_THEN_7_ELSE_1___d100[2] &&
		 !localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104[2]) ?
		  3'd4 :
		  localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104) ;
  assign localBht$WE = EN_update ;

  // submodule localHistTab
  assign localHistTab$ADDR_1 = pcIndex[19:10] ;
  assign localHistTab$ADDR_2 = pcIndex[9:0] ;
  assign localHistTab$ADDR_3 = 10'h0 ;
  assign localHistTab$ADDR_4 = 10'h0 ;
  assign localHistTab$ADDR_5 = 10'h0 ;
  assign localHistTab$ADDR_IN = update_train[9:0] ;
  assign localHistTab$D_IN = { update_taken, update_train[21:13] } ;
  assign localHistTab$WE = EN_update ;

  // remaining internal signals
  assign IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d65 =
	     CASE_predCnt_rl_0_useLocalVec_BIT_0_1_useLocal_ETC__q1 ?
	       localBht$D_OUT_3[2] :
	       SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 ;
  assign IF_SEL_ARR_useLocalVec_0_BIT_0_1_useLocalVec_0_ETC___d82 =
	     CASE_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_ETC__q2 ?
	       localBht$D_OUT_2[2] :
	       SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 ;
  assign IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 =
	     EN_pred_0_pred ? upd__h1286 : predCnt_rl ;
  assign IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24 =
	     EN_pred_0_pred ? upd__h1878 : predRes_rl ;
  assign IF_update_taken_THEN_3_ELSE_1___d116 = update_taken ? 2'd3 : 2'd1 ;
  assign IF_update_taken_THEN_7_ELSE_1___d100 = update_taken ? 3'd7 : 3'd1 ;
  assign IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136 =
	     (update_train[10] == update_taken) ? 2'd3 : 2'd1 ;
  assign choiceBht_sub_update_train_BITS_33_TO_22_12_32_ETC___d140 =
	     choiceBht$D_OUT_3 +
	     IF_update_train_BIT_10_29_EQ_update_taken_35_T_ETC___d136 ;
  assign globalBht_sub_update_train_BITS_33_TO_22_12_13_ETC___d120 =
	     globalBht$D_OUT_3 + IF_update_taken_THEN_3_ELSE_1___d116 ;
  assign localBht_sub_update_train_BITS_21_TO_12_6_7_PL_ETC___d104 =
	     localBht$D_OUT_1 + IF_update_taken_THEN_7_ELSE_1___d100 ;
  assign nextPc_nextPc_BITS_7_TO_0_PLUS_4__q3 = nextPc_nextPc[7:0] + 8'd4 ;
  assign upd__h1259 = predCnt_lat_1$wget ;
  assign upd__h1286 = predCnt_lat_0$wget ;
  assign upd__h1851 = predRes_lat_1$wget ;
  assign upd__h1878 = predRes_lat_0$wget ;
  assign x__h2510 =
	     { EN_pred_1_pred ?
		 upd__h1851 :
		 IF_predRes_lat_0_whas__0_THEN_IF_predRes_lat_0_ETC___d24,
	       gHistReg$history } >>
	     (EN_pred_1_pred ?
		upd__h1259 :
		IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11) ;
  assign x__h3630 = 2'd1 << predCnt_rl ;
  assign x__h4272 =
	     2'd1 <<
	     IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 ;
  assign y__h4054 = ~x__h3630 ;
  assign y__h4462 = ~x__h4272 ;
  assign y_avValue_train_globalHist__h4069 = prevGHist >> predCnt_rl ;
  assign y_avValue_train_globalHist__h4474 =
	     prevGHist >>
	     IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 ;
  always@(predCnt_rl or globalTakenVec)
  begin
    case (predCnt_rl)
      2'd0:
	  SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 =
	      globalTakenVec[0];
      2'd1:
	  SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 =
	      globalTakenVec[1];
      default: SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d64 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(predCnt_rl or useLocalVec)
  begin
    case (predCnt_rl)
      2'd0:
	  CASE_predCnt_rl_0_useLocalVec_BIT_0_1_useLocal_ETC__q1 =
	      useLocalVec[0];
      2'd1:
	  CASE_predCnt_rl_0_useLocalVec_BIT_0_1_useLocal_ETC__q1 =
	      useLocalVec[1];
      default: CASE_predCnt_rl_0_useLocalVec_BIT_0_1_useLocal_ETC__q1 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 or
	  globalTakenVec)
  begin
    case (IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11)
      2'd0:
	  SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 =
	      globalTakenVec[0];
      2'd1:
	  SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 =
	      globalTakenVec[1];
      default: SEL_ARR_globalTakenVec_0_BIT_0_1_globalTakenVe_ETC___d81 =
		   1'bx /* unspecified value */ ;
    endcase
  end
  always@(IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11 or
	  useLocalVec)
  begin
    case (IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_0_wh_ETC___d11)
      2'd0:
	  CASE_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_ETC__q2 =
	      useLocalVec[0];
      2'd1:
	  CASE_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_ETC__q2 =
	      useLocalVec[1];
      default: CASE_IF_predCnt_lat_0_whas_THEN_IF_predCnt_lat_ETC__q2 =
		   1'bx /* unspecified value */ ;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        predCnt_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
	predRes_rl <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (predCnt_rl$EN)
	  predCnt_rl <= `BSV_ASSIGNMENT_DELAY predCnt_rl$D_IN;
	if (predRes_rl$EN)
	  predRes_rl <= `BSV_ASSIGNMENT_DELAY predRes_rl$D_IN;
      end
    if (globalTakenVec$EN)
      globalTakenVec <= `BSV_ASSIGNMENT_DELAY globalTakenVec$D_IN;
    if (pcIndex$EN) pcIndex <= `BSV_ASSIGNMENT_DELAY pcIndex$D_IN;
    if (pc_reg$EN) pc_reg <= `BSV_ASSIGNMENT_DELAY pc_reg$D_IN;
    if (prevGHist$EN) prevGHist <= `BSV_ASSIGNMENT_DELAY prevGHist$D_IN;
    if (useLocalVec$EN) useLocalVec <= `BSV_ASSIGNMENT_DELAY useLocalVec$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    globalTakenVec = 2'h2;
    pcIndex = 20'hAAAAA;
    pc_reg = 64'hAAAAAAAAAAAAAAAA;
    predCnt_rl = 2'h2;
    predRes_rl = 2'h2;
    prevGHist = 12'hAAA;
    useLocalVec = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTourPred

