//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Sun May 31 11:17:26 BST 2026
//
//
// Ports:
// Name                         I/O  size props
// brAddrCalc                     O   161
// brAddrCalc_pc                  I   161
// brAddrCalc_val                 I   161
// brAddrCalc_iType               I     5
// brAddrCalc_imm                 I    64
// brAddrCalc_taken               I     1
// brAddrCalc_orig_inst           I    32
// brAddrCalc_cap                 I     1
//
// Combinational paths from inputs to outputs:
//   (brAddrCalc_pc,
//    brAddrCalc_val,
//    brAddrCalc_iType,
//    brAddrCalc_imm,
//    brAddrCalc_taken,
//    brAddrCalc_orig_inst,
//    brAddrCalc_cap) -> brAddrCalc
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_brAddrCalc(brAddrCalc_pc,
			 brAddrCalc_val,
			 brAddrCalc_iType,
			 brAddrCalc_imm,
			 brAddrCalc_taken,
			 brAddrCalc_orig_inst,
			 brAddrCalc_cap,
			 brAddrCalc);
  // value method brAddrCalc
  input  [160 : 0] brAddrCalc_pc;
  input  [160 : 0] brAddrCalc_val;
  input  [4 : 0] brAddrCalc_iType;
  input  [63 : 0] brAddrCalc_imm;
  input  brAddrCalc_taken;
  input  [31 : 0] brAddrCalc_orig_inst;
  input  brAddrCalc_cap;
  output [160 : 0] brAddrCalc;

  // signals for module outputs
  reg [160 : 0] brAddrCalc;

  // remaining internal signals
  reg [63 : 0] IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21,
	       _theResult___snd_fst_capFat_address__h885;
  reg [34 : 0] CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q2;
  reg [15 : 0] CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q3,
	       x__h2125;
  reg [13 : 0] _theResult___snd_fst_capFat_addrBits__h886,
	       _theResult___snd_fst_capFat_bounds_baseBits__h906,
	       _theResult___snd_fst_capFat_bounds_topBits__h905;
  reg [7 : 0] x__h2006, x__h2007;
  reg [5 : 0] IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29;
  reg [3 : 0] _theResult___snd_fst_capFat_perms_soft__h1881;
  reg [2 : 0] _theResult___snd_fst_tempFields_repBoundTopBits__h1503;
  reg CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q1,
      IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74,
      thin_flags__h1868;
  wire [71 : 0] IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d137;
  wire [63 : 0] IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d172,
		_theResult___fst__h278,
		_theResult___snd_fst_capFat_address__h874,
		addBase__h2074,
		address__h126,
		offset___1__h289,
		pointer__h309,
		result_d_address__h1565,
		ret___1_address__h1771,
		targetAddr_capFat_address__h187,
		thin_address__h1873,
		x__h1438,
		x__h2457,
		x__h2488;
  wire [54 : 0] IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d136;
  wire [49 : 0] IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92,
		deltaAddrHi__h1582,
		deltaAddrUpper__h1584,
		highBitsfilter__h315,
		highOffsetBits__h316,
		signBits__h313,
		x__h343;
  wire [34 : 0] IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d133;
  wire [15 : 0] IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102,
		IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117,
		IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d184;
  wire [13 : 0] IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d176,
		_theResult___snd_fst_capFat_addrBits__h875,
		_theResult___snd_fst_capFat_bounds_baseBits__h903,
		_theResult___snd_fst_capFat_bounds_topBits__h902,
		repBoundBits__h322,
		toBoundsM1_A__h321,
		toBoundsM1_B__h324,
		toBoundsM1__h326,
		toBounds_A__h320,
		toBounds_B__h323,
		toBounds__h325;
  wire [11 : 0] inc__h125;
  wire [9 : 0] IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d223,
	       IF_brAddrCalc_taken_THEN_IF_brAddrCalc_iType_E_ETC___d222;
  wire [7 : 0] IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d188,
	       IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d190,
	       _theResult___snd_fst_capFat_mte__h879,
	       _theResult___snd_fst_capFat_tloc__h880;
  wire [5 : 0] IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28,
	       IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d196;
  wire [3 : 0] IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d159,
	       IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d193,
	       IF_brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCa_ETC___d219,
	       _theResult___snd_fst_capFat_perms_soft__h1879;
  wire [2 : 0] _theResult___snd_fst_tempFields_repBoundTopBits__h1497,
	       repBound__h2642,
	       repBound__h2652;
  wire [1 : 0] x__h1590;
  wire IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d66,
       IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149,
       IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96,
       IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73,
       IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81,
       IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d165,
       IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d186,
       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146,
       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147,
       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d75,
       _theResult___snd_fst_capFat_flags__h877,
       brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209,
       brAddrCalc_pc_BITS_23_TO_21_03_ULT_brAddrCalc__ETC___d207,
       brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCalc__ETC___d206;

  // value method brAddrCalc
  always@(brAddrCalc_iType or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d165 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d172 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d176 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d184 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d186 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d188 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d190 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d193 or
	  brAddrCalc_pc or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d196 or
	  IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d223 or
	  IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 or
	  targetAddr_capFat_address__h187 or
	  x__h2457 or
	  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d137 or
	  repBound__h2642 or
	  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146 or
	  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147 or
	  IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149 or
	  IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d159)
  begin
    case (brAddrCalc_iType)
      5'd8, 5'd9, 5'd11, 5'd12, 5'd13:
	  brAddrCalc =
	      { IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96,
		targetAddr_capFat_address__h187,
		x__h2457[13:0],
		IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d137,
		repBound__h2642,
		IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146,
		IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147,
		IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149,
		IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d159 };
      default: brAddrCalc =
		   { IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d165,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d172,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d176,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d184,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d186,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d188,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d190,
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d193,
		     brAddrCalc_pc[44],
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d196,
		     brAddrCalc_pc[37:10],
		     IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d223 };
    endcase
  end

  // remaining internal signals
  assign IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d159 =
	     { (IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146 ==
		IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149) ?
		 2'd0 :
		 ((IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146 &&
		   !IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149) ?
		    2'd1 :
		    2'd3),
	       (IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147 ==
		IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149) ?
		 2'd0 :
		 ((IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147 &&
		   !IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d66 =
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21[63] ?
	       x__h1438[13:0] >= toBounds__h325 &&
	       repBoundBits__h322 !=
	       _theResult___snd_fst_capFat_addrBits__h886 :
	       x__h1438[13:0] < toBoundsM1__h326 ;
  assign IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149 =
	     x__h2457[13:11] < repBound__h2642 ;
  assign IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 =
	     (brAddrCalc_iType != 5'd9 && brAddrCalc_iType != 5'd11 &&
	      brAddrCalc_iType != 5'd13 ||
	      brAddrCalc_cap) ?
	       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d75 :
	       deltaAddrHi__h1582 == deltaAddrUpper__h1584 &&
	       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 ;
  assign IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102 =
	     brAddrCalc_cap ?
	       { brAddrCalc_val[1:0], brAddrCalc_val[23:10] } :
	       { brAddrCalc_pc[1:0], brAddrCalc_pc[23:10] } ;
  assign IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28 =
	     brAddrCalc_cap ? brAddrCalc_val[43:38] : brAddrCalc_pc[43:38] ;
  assign IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d133 =
	     brAddrCalc_cap ? brAddrCalc_val[44:10] : brAddrCalc_pc[44:10] ;
  assign IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117 =
	     brAddrCalc_cap ? brAddrCalc_val[81:66] : brAddrCalc_pc[81:66] ;
  assign IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73 =
	     brAddrCalc_cap ? brAddrCalc_val[160] : brAddrCalc_pc[160] ;
  assign IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81 =
	     brAddrCalc_cap ? brAddrCalc_val[4] : brAddrCalc_pc[4] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d165 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ?
		  IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d96 :
		  brAddrCalc_pc[160]) :
	       brAddrCalc_pc[160] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d172 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ?
		  targetAddr_capFat_address__h187 :
		  address__h126) :
	       address__h126 ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d176 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ? x__h2457[13:0] : x__h2488[13:0]) :
	       x__h2488[13:0] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d184 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ?
		  { _theResult___snd_fst_capFat_perms_soft__h1881,
		    brAddrCalc_pc[77:66] } :
		  brAddrCalc_pc[81:66]) :
	       brAddrCalc_pc[81:66] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d186 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ? thin_flags__h1868 : brAddrCalc_pc[65]) :
	       brAddrCalc_pc[65] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d188 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ? x__h2006 : brAddrCalc_pc[64:57]) :
	       brAddrCalc_pc[64:57] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d190 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ? x__h2007 : brAddrCalc_pc[56:49]) :
	       brAddrCalc_pc[56:49] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d193 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ? 4'd15 : brAddrCalc_pc[48:45]) :
	       brAddrCalc_pc[48:45] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d196 =
	     (brAddrCalc_iType == 5'd10) ?
	       (brAddrCalc_taken ?
		  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 :
		  brAddrCalc_pc[43:38]) :
	       brAddrCalc_pc[43:38] ;
  assign IF_brAddrCalc_iType_EQ_10_63_THEN_IF_brAddrCal_ETC___d223 =
	     (brAddrCalc_iType == 5'd10) ?
	       IF_brAddrCalc_taken_THEN_IF_brAddrCalc_iType_E_ETC___d222 :
	       { repBound__h2652,
		 brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCalc__ETC___d206,
		 brAddrCalc_pc_BITS_23_TO_21_03_ULT_brAddrCalc__ETC___d207,
		 brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209,
		 IF_brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCa_ETC___d219 } ;
  assign IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d136 =
	     { x__h2006,
	       x__h2007,
	       4'd15,
	       CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q2 } ;
  assign IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d137 =
	     { CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q3,
	       thin_flags__h1868,
	       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d136 } ;
  assign IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146 =
	     _theResult___snd_fst_capFat_bounds_topBits__h905[13:11] <
	     repBound__h2642 ;
  assign IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147 =
	     _theResult___snd_fst_capFat_bounds_baseBits__h906[13:11] <
	     repBound__h2642 ;
  assign IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d75 =
	     (highOffsetBits__h316 == 50'd0 &&
	      IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d66 ||
	      IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 >=
	      6'd50) &&
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 ;
  assign IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92 =
	     _theResult___snd_fst_capFat_address__h885[63:14] &
	     highBitsfilter__h315 ;
  assign IF_brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCa_ETC___d219 =
	     { (brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCalc__ETC___d206 ==
		brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209) ?
		 2'd0 :
		 ((brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCalc__ETC___d206 &&
		   !brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209) ?
		    2'd1 :
		    2'd3),
	       (brAddrCalc_pc_BITS_23_TO_21_03_ULT_brAddrCalc__ETC___d207 ==
		brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209) ?
		 2'd0 :
		 ((brAddrCalc_pc_BITS_23_TO_21_03_ULT_brAddrCalc__ETC___d207 &&
		   !brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209) ?
		    2'd1 :
		    2'd3) } ;
  assign IF_brAddrCalc_taken_THEN_IF_brAddrCalc_iType_E_ETC___d222 =
	     brAddrCalc_taken ?
	       { repBound__h2642,
		 IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d146,
		 IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d147,
		 IF_NOT_brAddrCalc_iType_EQ_9_0_AND_NOT_brAddrC_ETC___d149,
		 IF_IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iTyp_ETC___d159 } :
	       { repBound__h2652,
		 brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCalc__ETC___d206,
		 brAddrCalc_pc_BITS_23_TO_21_03_ULT_brAddrCalc__ETC___d207,
		 brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209,
		 IF_brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCa_ETC___d219 } ;
  assign _theResult___fst__h278 =
	     brAddrCalc_cap ? brAddrCalc_imm : offset___1__h289 ;
  assign _theResult___snd_fst_capFat_addrBits__h875 =
	     brAddrCalc_cap ? brAddrCalc_val[95:82] : brAddrCalc_pc[95:82] ;
  assign _theResult___snd_fst_capFat_address__h874 =
	     brAddrCalc_cap ? brAddrCalc_val[159:96] : brAddrCalc_pc[159:96] ;
  assign _theResult___snd_fst_capFat_bounds_baseBits__h903 =
	     brAddrCalc_cap ? brAddrCalc_val[23:10] : brAddrCalc_pc[23:10] ;
  assign _theResult___snd_fst_capFat_bounds_topBits__h902 =
	     brAddrCalc_cap ? brAddrCalc_val[37:24] : brAddrCalc_pc[37:24] ;
  assign _theResult___snd_fst_capFat_flags__h877 =
	     brAddrCalc_cap ? brAddrCalc_val[65] : brAddrCalc_pc[65] ;
  assign _theResult___snd_fst_capFat_mte__h879 =
	     brAddrCalc_cap ? brAddrCalc_val[64:57] : brAddrCalc_pc[64:57] ;
  assign _theResult___snd_fst_capFat_perms_soft__h1879 =
	     brAddrCalc_cap ? brAddrCalc_val[81:78] : brAddrCalc_pc[81:78] ;
  assign _theResult___snd_fst_capFat_tloc__h880 =
	     brAddrCalc_cap ? brAddrCalc_val[56:49] : brAddrCalc_pc[56:49] ;
  assign _theResult___snd_fst_tempFields_repBoundTopBits__h1497 =
	     brAddrCalc_cap ? brAddrCalc_val[9:7] : brAddrCalc_pc[9:7] ;
  assign addBase__h2074 =
	     { {48{x__h2125[15]}}, x__h2125 } <<
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 ;
  assign address__h126 =
	     brAddrCalc_pc[159:96] + { {52{inc__h125[11]}}, inc__h125 } ;
  assign brAddrCalc_pc_BITS_159_TO_96_8_PLUS_SEXT_IF_br_ETC___d209 =
	     x__h2488[13:11] < repBound__h2652 ;
  assign brAddrCalc_pc_BITS_23_TO_21_03_ULT_brAddrCalc__ETC___d207 =
	     brAddrCalc_pc[23:21] < repBound__h2652 ;
  assign brAddrCalc_pc_BITS_37_TO_35_05_ULT_brAddrCalc__ETC___d206 =
	     brAddrCalc_pc[37:35] < repBound__h2652 ;
  assign deltaAddrHi__h1582 =
	     { {48{x__h1590[1]}}, x__h1590 } <<
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 ;
  assign deltaAddrUpper__h1584 =
	     (IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21[63:14] &
	      highBitsfilter__h315) -
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92 ;
  assign highBitsfilter__h315 =
	     50'h3FFFFFFFFFFFF <<
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 ;
  assign highOffsetBits__h316 = x__h343 & highBitsfilter__h315 ;
  assign inc__h125 = (brAddrCalc_orig_inst[1:0] == 2'b11) ? 12'd4 : 12'd2 ;
  assign offset___1__h289 = brAddrCalc_val[159:96] + brAddrCalc_imm ;
  assign pointer__h309 =
	     _theResult___snd_fst_capFat_address__h885 +
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 ;
  assign repBoundBits__h322 =
	     { _theResult___snd_fst_tempFields_repBoundTopBits__h1503,
	       11'd0 } ;
  assign repBound__h2642 =
	     _theResult___snd_fst_capFat_bounds_baseBits__h906[13:11] -
	     3'b001 ;
  assign repBound__h2652 = brAddrCalc_pc[23:21] - 3'b001 ;
  assign result_d_address__h1565 =
	     ((brAddrCalc_iType == 5'd9 || brAddrCalc_iType == 5'd11 ||
	       brAddrCalc_iType == 5'd13) &&
	      !brAddrCalc_cap) ?
	       ret___1_address__h1771 :
	       pointer__h309 ;
  assign ret___1_address__h1771 =
	     { IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d92,
	       14'd0 } +
	     addBase__h2074 +
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 ;
  assign signBits__h313 =
	     {50{IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21[63]}} ;
  assign targetAddr_capFat_address__h187 =
	     { thin_address__h1873[63:1], 1'b0 } ;
  assign thin_address__h1873 =
	     (brAddrCalc_iType != 5'd9 && brAddrCalc_iType != 5'd11 &&
	      brAddrCalc_iType != 5'd13 ||
	      brAddrCalc_cap) ?
	       result_d_address__h1565 :
	       IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 ;
  assign toBoundsM1_A__h321 =
	     { 3'b110,
	       ~_theResult___snd_fst_capFat_bounds_baseBits__h906[10:0] } ;
  assign toBoundsM1_B__h324 =
	     repBoundBits__h322 +
	     ~_theResult___snd_fst_capFat_addrBits__h886 ;
  assign toBoundsM1__h326 =
	     ((brAddrCalc_iType == 5'd9 || brAddrCalc_iType == 5'd11 ||
	       brAddrCalc_iType == 5'd13) &&
	      !brAddrCalc_cap) ?
	       toBoundsM1_A__h321 :
	       toBoundsM1_B__h324 ;
  assign toBounds_A__h320 =
	     14'd14336 -
	     { 3'b0,
	       _theResult___snd_fst_capFat_bounds_baseBits__h906[10:0] } ;
  assign toBounds_B__h323 =
	     repBoundBits__h322 - _theResult___snd_fst_capFat_addrBits__h886 ;
  assign toBounds__h325 =
	     ((brAddrCalc_iType == 5'd9 || brAddrCalc_iType == 5'd11 ||
	       brAddrCalc_iType == 5'd13) &&
	      !brAddrCalc_cap) ?
	       toBounds_A__h320 :
	       toBounds_B__h323 ;
  assign x__h1438 =
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 >>
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 ;
  assign x__h1590 =
	     { 1'b0,
	       x__h1438[13:11] <
	       _theResult___snd_fst_tempFields_repBoundTopBits__h1503 } -
	     { 1'b0,
	       CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q1 } ;
  assign x__h2457 =
	     targetAddr_capFat_address__h187 >>
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 ;
  assign x__h2488 = address__h126 >> brAddrCalc_pc[43:38] ;
  assign x__h343 =
	     IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21[63:14] ^
	     signBits__h313 ;
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_bounds_baseBits__h903)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  _theResult___snd_fst_capFat_bounds_baseBits__h906 =
	      _theResult___snd_fst_capFat_bounds_baseBits__h903;
      default: _theResult___snd_fst_capFat_bounds_baseBits__h906 =
		   brAddrCalc_pc[23:10];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_perms_soft__h1879)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  _theResult___snd_fst_capFat_perms_soft__h1881 =
	      _theResult___snd_fst_capFat_perms_soft__h1879;
      default: _theResult___snd_fst_capFat_perms_soft__h1881 =
		   brAddrCalc_pc[81:78];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_address__h874)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  _theResult___snd_fst_capFat_address__h885 =
	      _theResult___snd_fst_capFat_address__h874;
      default: _theResult___snd_fst_capFat_address__h885 =
		   brAddrCalc_pc[159:96];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_addrBits__h875)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  _theResult___snd_fst_capFat_addrBits__h886 =
	      _theResult___snd_fst_capFat_addrBits__h875;
      default: _theResult___snd_fst_capFat_addrBits__h886 =
		   brAddrCalc_pc[95:82];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_flags__h877)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  thin_flags__h1868 = _theResult___snd_fst_capFat_flags__h877;
      default: thin_flags__h1868 = brAddrCalc_pc[65];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_mte__h879)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13: x__h2006 = _theResult___snd_fst_capFat_mte__h879;
      default: x__h2006 = brAddrCalc_pc[64:57];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_tloc__h880)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13: x__h2007 = _theResult___snd_fst_capFat_tloc__h880;
      default: x__h2007 = brAddrCalc_pc[56:49];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  _theResult___snd_fst_tempFields_repBoundTopBits__h1497)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  _theResult___snd_fst_tempFields_repBoundTopBits__h1503 =
	      _theResult___snd_fst_tempFields_repBoundTopBits__h1497;
      default: _theResult___snd_fst_tempFields_repBoundTopBits__h1503 =
		   brAddrCalc_pc[9:7];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or _theResult___snd_fst_capFat_bounds_topBits__h902)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  _theResult___snd_fst_capFat_bounds_topBits__h905 =
	      _theResult___snd_fst_capFat_bounds_topBits__h902;
      default: _theResult___snd_fst_capFat_bounds_topBits__h905 =
		   brAddrCalc_pc[37:24];
    endcase
  end
  always@(brAddrCalc_iType or brAddrCalc_imm or _theResult___fst__h278)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 =
	      _theResult___fst__h278;
      default: IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d21 =
		   brAddrCalc_imm;
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 =
	      IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_43__ETC___d28;
      default: IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d29 =
		   brAddrCalc_pc[43:38];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q1 =
	      IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_4_9__ETC___d81;
      default: CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q1 =
		   brAddrCalc_pc[4];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  x__h2125 =
	      IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_1_T_ETC___d102;
      default: x__h2125 = { brAddrCalc_pc[1:0], brAddrCalc_pc[23:10] };
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 =
	      IF_brAddrCalc_cap_THEN_brAddrCalc_val_BIT_160__ETC___d73;
      default: IF_brAddrCalc_iType_EQ_9_OR_brAddrCalc_iType_E_ETC___d74 =
		   brAddrCalc_pc[160];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d133)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q2 =
	      IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_44__ETC___d133;
      default: CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q2 =
		   brAddrCalc_pc[44:10];
    endcase
  end
  always@(brAddrCalc_iType or
	  brAddrCalc_pc or
	  IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117)
  begin
    case (brAddrCalc_iType)
      5'd9, 5'd11, 5'd13:
	  CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q3 =
	      IF_brAddrCalc_cap_THEN_brAddrCalc_val_BITS_81__ETC___d117;
      default: CASE_brAddrCalc_iType_9_IF_brAddrCalc_cap_THEN_ETC__q3 =
		   brAddrCalc_pc[81:66];
    endcase
  end
endmodule  // module_brAddrCalc

